#set page(width: 1860pt, height: 900pt, margin: 0pt, fill: none)
#let c(x,t) = place(dx: x*1pt, dy: 0pt, box(width: 620pt, inset: 16pt, text(fill: white, size: 25pt, weight: "bold", font: "Helvetica", t)))
#c(0,"AGE 25 - composite, for approval")
#c(620,"AGE 45 - approved")
#c(1240,"AGE 60 - approved canonical")
