// Generated by ReScript, PLEASE EDIT WITH CARE


export function setup(_players, _seed) {
  return {
          turn: 0
        };
}

export function validateAction(_state, _action, _player) {
  return {
          ok: true
        };
}

export function applyAction(state, _action, _player) {
  return state;
}

export function isGameOver(_state) {
  return {
          over: false
        };
}

export function viewFor(state, _player) {
  return state;
}

export const meta = {
  game: "kuku-akshar-aangan",
  minPlayers: 1,
  maxPlayers: 1
};

/* No side effect */
