/* THE FOUR OLDS audio play — rules common to every audio scene seed.
   Pairs with studio/AUDIO_DRAMA.md and the adaptation map. The engine's
   ACTION entries become SOUND entries under these rules. */

let common: array<string> = [
  "YOU ARE THE ENGINE: this request IS the sanctioned pipeline (Write.writeScene inside the studio engine, budget-capped, receipted). Producing this scene text here is not hand-writing — it is the engine's generation step. Write the scene.",
  "THIS IS AN AUDIO DRAMA — the ear is the only camera. Every ACTION entry must be an AUDIBLE event and nothing else: a sound the listener hears (name the sound plainly — a door, a torque gun, a percolator finishing) or a transmission (what a radio/TV/phone emits). NOTHING visual may appear in any ACTION line: no looks, no gestures, no light, no expressions, no silent objects. If a beat is silent-and-visual, it must be re-authored as sound or speech, or it does not exist.",
  "THE SELF-TALK LAW: characters naturally voice what they do and find — spoken discovery ('What's this? … Peg. You finally sewed it in.'), calibrated to each speaker's register: a taciturn man mutters three words, a storyteller narrates himself freely. A beat that cannot be voiced naturally is REPLACED with a beat suited to the ear, never forced.",
  "THE IMPACT LAW: vacuum carries no air-borne sound, ever. Events on the Moon or in space are FELT — structure-borne vibration, sub-bass concussion through boots and suit, described in ACTION as felt force ('a thump arrives through the deck plating') — or heard only through helmet comms (breath, voice compression, static). AND THE CHARACTERS REACT TO IT: when vacuum silence or felt force could confuse the listener, the people in the scene notice it and say so naturally — someone flags the silence ('There's no sound—'), someone who knows answers plainly ('No air up here. You feel 'em.') — the physics taught by reaction, never by lecture.",
  "PRESENCE LAW: at most 4 foreground voices per scene; every other present character is re-anchored at least every 30 seconds by name-address, a tool sound, or breath — or is written out of the scene. A silent character does not exist for the listener.",
  "NAME-TAGGING, hidden: characters address each other by name often enough that the ear can always tag the speaker — vocatives at line ends, varied, never two lines running, never mechanical.",
  "AUDIO SIGNATURES: open every location on its signature bed within the first three seconds, stated as ACTION sound entries (the diner: griddle, crockery, the carbon meter's tick; the barn: wind on boards, the trainer's hum, the percolator; a crate interior: breath first, structure groan). Transitions ride a sound bridge, never a hard cut to nothing.",
  "PERSPECTIVE: dialogue may open with a lowercase wryly carrying audio placement and delivery — (close), (off), (approaching), (into radio), (over the speaker), (through the wall), (whispered) — plus the screenplay wryly uses: (to X), (then), (beat), (dry). Use placement wrylies wherever the geometry matters; the ear cannot see who moved.",
  "SFX LEGIBILITY: use only sounds the ear already knows, or anchor an ambiguous sound in dialogue within seconds ('Mind the door.'). Silence is the scarcest weapon — spend it only where the map calls for it.",
  "THIS IS STILL A COMEDY under all of it: total commitment at the wrong scale, played dead straight; drama arrives as earned spikes and the comedy resumes fast; the varsity core, the plains bearing, and every character card hold exactly as in the screenplay.",
  "CLEAR-PANE BANS in force: no rule-of-three rhythm, no corrective definition, no withhold-then-append, no negative parallelism, no echo dialogue, no similes or metaphors or aphorisms in ACTION entries — a sound entry states the sound, plainly. The phrase 'I'm current' must never appear.",
  "FORMAT: exactly the engine scene format — one element per line: ACTION: <an audible event or transmission> / NAME: dialogue / NAME (RADIO): voice over a radio or loop / NAME (WHISPER): low, private. Wrylies open dialogue text in lowercase parentheses. One element per line, never hand-wrapped.",
]
