/* EP1 assembly plan — casting beats, result beats, motion. Generated. */
open Drakosha_Assembly

let plan: plan = {
  segments: [
    {segId: "s01", visual: Frame("f01"), lines: [LineId(1)], hold: None, word: None, cue: Ambience("sockdrag", 0.35), motion: Still},
    {segId: "s02", visual: Frame("f01"), lines: [LineId(2)], hold: None, word: None, cue: Ambience("sockdrag", 0.3), motion: Still},
    {segId: "s03", visual: Frame("f02"), lines: [LineId(3)], hold: None, word: None, cue: Ambience("clock", 0.18), motion: Still},
    {segId: "s04", visual: Frame("f02"), lines: [LineId(4)], hold: None, word: None, cue: Ambience("clock", 0.18), motion: Still},
    {segId: "s05", visual: Frame("f02"), lines: [LineId(5)], hold: None, word: None, cue: Ambience("clock", 0.18), motion: Still},
    {segId: "s06", visual: Frame("f02"), lines: [LineId(6)], hold: None, word: None, cue: Ambience("clock", 0.18), motion: Still},
    {segId: "s07", visual: Frame("f03"), lines: [LineId(7)], hold: None, word: None, cue: Ambience("rccar", 0.4), motion: Still},
    {segId: "s08", visual: Frame("f03"), lines: [LineId(8)], hold: None, word: None, cue: Ambience("rccar", 0.3), motion: Still},
    {segId: "s09", visual: Frame("f04"), lines: [LineId(9)], hold: None, word: None, cue: Ambience("carstuck", 0.4), motion: Still},
    {segId: "s10", visual: Frame("f04"), lines: [LineId(10)], hold: None, word: None, cue: Ambience("carstuck", 0.35), motion: Still},
    {segId: "g11", visual: Clip("2026-08-09_EP1_scene2_job10.mp4"), lines: [LineId(11)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "g12_13", visual: Clip("2026-08-09_EP1_scene2_job11.mp4"), lines: [LineId(12), LineId(13)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "g14", visual: Clip("2026-08-09_EP1_scene2_job13.mp4"), lines: [LineId(14)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "g15_16_17", visual: Clip("2026-08-09_EP1_scene2_job14.mp4"), lines: [LineId(15), LineId(16), LineId(17)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s18", visual: Frame("f14"), lines: [LineId(18)], hold: None, word: None, cue: Ambience("mortar", 0.4), motion: Still},
    {segId: "s19", visual: Frame("f15"), lines: [LineId(19)], hold: None, word: None, cue: Ambience("rumble", 0.45), motion: Still},
    {segId: "s20", visual: Frame("f17"), lines: [LineId(20)], hold: None, word: None, cue: OneShot("sootburst", 0.3), motion: Still},
    {segId: "s21", visual: Frame("f17"), lines: [LineId(21)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s22", visual: Frame("f18"), lines: [LineId(22)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s23", visual: Frame("f18"), lines: [LineId(23)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s24", visual: Frame("f18"), lines: [LineId(24)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s25", visual: Frame("f18"), lines: [LineId(25)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s26", visual: Frame("f18"), lines: [LineId(26)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s27", visual: Frame("f18"), lines: [LineId(27)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s28", visual: Frame("f20"), lines: [LineId(28)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s29", visual: Frame("f20"), lines: [LineId(29)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s30", visual: Frame("f20"), lines: [LineId(30)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s31", visual: Frame("f20"), lines: [LineId(31)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s32", visual: Frame("f20"), lines: [LineId(32)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s33", visual: Frame("f20"), lines: [LineId(33)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s34", visual: Frame("f21"), lines: [LineId(34)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s35", visual: Frame("f21"), lines: [LineId(35)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s36", visual: Frame("f21"), lines: [LineId(36)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s37", visual: Frame("f22"), lines: [LineId(37)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s38", visual: Frame("f22"), lines: [LineId(38)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s39", visual: Frame("f22"), lines: [LineId(39)], hold: None, word: Some("vzhukh"), cue: OneShot("vzhukh", 0.55), motion: Still},
    {segId: "s40", visual: Frame("f23_v2"), lines: [LineId(40)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s41", visual: Frame("f23_v2"), lines: [LineId(41)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s42", visual: Frame("f23_v2"), lines: [LineId(42)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s43", visual: Frame("f24"), lines: [LineId(43)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s44", visual: Frame("f24"), lines: [LineId(44)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s45", visual: Frame("f25"), lines: [LineId(45)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s46", visual: Frame("f25"), lines: [LineId(46)], hold: None, word: Some("letters"), cue: Ambience("stove", 0.15), motion: Still},
    {segId: "s47", visual: Frame("f25"), lines: [LineId(47)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s48", visual: Frame("f25"), lines: [LineId(48)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s49", visual: Frame("f25"), lines: [LineId(49)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s50", visual: Frame("f26"), lines: [LineId(50)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s51", visual: Frame("f26"), lines: [LineId(51)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "cast52", visual: Frame("cast_frosya"), lines: [LineId(52)], hold: None, word: Some("sok"), cue: OneShot("chime", 0.5), motion: Still},
    {segId: "res52", visual: Frame("f27"), lines: [], hold: Some(1.8), word: None, cue: NoCue, motion: Pull},
    {segId: "s53", visual: Frame("f28"), lines: [LineId(53)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s54", visual: Frame("f28"), lines: [LineId(54)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "cast55", visual: Frame("cast_frosya"), lines: [LineId(55)], hold: None, word: Some("salat"), cue: OneShot("chime", 0.45), motion: Still},
    {segId: "res55", visual: Frame("f28"), lines: [], hold: Some(1.6), word: None, cue: NoCue, motion: Pull},
    {segId: "s56", visual: Frame("f28"), lines: [LineId(56)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "cast57", visual: Frame("cast_frosya"), lines: [LineId(57)], hold: None, word: Some("mak"), cue: OneShot("chime", 0.45), motion: Still},
    {segId: "res57", visual: Frame("f29"), lines: [], hold: Some(1.6), word: None, cue: NoCue, motion: Pull},
    {segId: "s58", visual: Frame("f29"), lines: [LineId(58)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s59", visual: Frame("f29"), lines: [LineId(59)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s60", visual: Frame("f30"), lines: [LineId(60)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s61", visual: Frame("f30"), lines: [LineId(61)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "cast62", visual: Frame("cast_vasya"), lines: [LineId(62)], hold: None, word: Some("mama"), cue: OneShot("vzhukh", 0.55), motion: Still},
    {segId: "res62", visual: Frame("f31"), lines: [], hold: Some(2.0), word: None, cue: NoCue, motion: Pull},
    {segId: "s63", visual: Frame("f31"), lines: [LineId(63)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s64", visual: Frame("f31"), lines: [LineId(64)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s65", visual: Frame("f31"), lines: [LineId(65)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s66", visual: Frame("f31"), lines: [LineId(66)], hold: None, word: Some("vzhukh"), cue: OneShot("vzhukh", 0.5), motion: Still},
    {segId: "s67", visual: Frame("f32"), lines: [LineId(67)], hold: None, word: Some("mashina"), cue: NoCue, motion: Still},
    {segId: "s68", visual: Frame("f32"), lines: [LineId(68)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s69", visual: Frame("f32"), lines: [LineId(69)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s70", visual: Frame("f32"), lines: [LineId(70)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s71", visual: Frame("f32"), lines: [LineId(71)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "cast72", visual: Frame("cast_frosya"), lines: [LineId(72)], hold: None, word: Some("samokat"), cue: OneShot("chimebig", 0.5), motion: Still},
    {segId: "res72", visual: Frame("f33"), lines: [], hold: Some(2.0), word: None, cue: NoCue, motion: Pull},
    {segId: "s73", visual: Frame("f33"), lines: [LineId(73)], hold: None, word: None, cue: Ambience("scooter", 0.3), motion: Still},
    {segId: "s74", visual: Frame("f33"), lines: [LineId(74)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s75", visual: Frame("f34"), lines: [LineId(75)], hold: None, word: None, cue: Ambience("scooter", 0.4), motion: Push},
    {segId: "s76", visual: Frame("f34"), lines: [LineId(76)], hold: None, word: None, cue: Ambience("scooter", 0.4), motion: Push},
    {segId: "s77", visual: Frame("f34"), lines: [LineId(77)], hold: None, word: None, cue: Ambience("scooter", 0.35), motion: Push},
    {segId: "s78", visual: Frame("f34"), lines: [LineId(78)], hold: None, word: None, cue: Ambience("scooter", 0.4), motion: Push},
    {segId: "cast79", visual: Frame("cast_vasya"), lines: [LineId(79)], hold: None, word: Some("kot"), cue: OneShot("vzhukh", 0.5), motion: Still},
    {segId: "res79", visual: Frame("f35"), lines: [], hold: Some(1.8), word: None, cue: NoCue, motion: Pull},
    {segId: "s80", visual: Frame("f35"), lines: [LineId(80)], hold: None, word: None, cue: NoCue, motion: Push},
    {segId: "ex80", visual: Frame("f46"), lines: [], hold: Some(1.4), word: None, cue: NoCue, motion: Push},
    {segId: "s81", visual: Frame("f35"), lines: [LineId(81)], hold: None, word: None, cue: NoCue, motion: Push},
    {segId: "ex81", visual: Frame("f45"), lines: [], hold: Some(1.6), word: None, cue: NoCue, motion: Push},
    {segId: "cast82", visual: Frame("cast_frosya"), lines: [LineId(82)], hold: None, word: Some("bak"), cue: OneShot("whomp", 0.5), motion: Still},
    {segId: "res82", visual: Frame("f36"), lines: [], hold: Some(2.0), word: None, cue: NoCue, motion: Pull},
    {segId: "s83", visual: Frame("f36"), lines: [LineId(83)], hold: None, word: None, cue: NoCue, motion: Push},
    {segId: "s84", visual: Frame("f36"), lines: [LineId(84)], hold: None, word: None, cue: NoCue, motion: Push},
    {segId: "ex84", visual: Frame("f47"), lines: [], hold: Some(1.6), word: None, cue: NoCue, motion: Push},
    {segId: "cast85", visual: Frame("cast_vasya"), lines: [LineId(85)], hold: None, word: Some("osa"), cue: OneShot("vzhukh", 0.5), motion: Still},
    {segId: "res85", visual: Frame("f37"), lines: [], hold: Some(1.8), word: None, cue: NoCue, motion: Pull},
    {segId: "s86", visual: Frame("f37"), lines: [LineId(86)], hold: None, word: None, cue: Ambience("buzz", 0.4), motion: Push},
    {segId: "s87", visual: Frame("f38"), lines: [LineId(87)], hold: None, word: None, cue: Ambience("buzz", 0.45), motion: Push},
    {segId: "s88", visual: Frame("f39"), lines: [LineId(88)], hold: None, word: None, cue: Ambience("buzz", 0.25), motion: Still},
    {segId: "s89", visual: Frame("f39"), lines: [LineId(89)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s90", visual: Frame("f39"), lines: [LineId(90)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s91", visual: Frame("f39"), lines: [LineId(91)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s92", visual: Frame("f39"), lines: [LineId(92)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s93", visual: Frame("f40"), lines: [LineId(93)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s94", visual: Frame("f40"), lines: [LineId(94)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s95", visual: Frame("f40"), lines: [LineId(95)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s96", visual: Frame("f40"), lines: [LineId(96)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s97", visual: Frame("f40"), lines: [LineId(97)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "cast98", visual: Frame("cast_frosya"), lines: [LineId(98)], hold: None, word: Some("motok"), cue: OneShot("chime", 0.45), motion: Still},
    {segId: "res98", visual: Frame("f40"), lines: [], hold: Some(1.6), word: None, cue: NoCue, motion: Pull},
    {segId: "s99", visual: Frame("f40"), lines: [LineId(99)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "cast100", visual: Frame("cast_vasya"), lines: [LineId(100)], hold: None, word: Some("osa"), cue: OneShot("vzhukh", 0.45), motion: Still},
    {segId: "res100", visual: Frame("f40"), lines: [], hold: Some(1.4), word: None, cue: NoCue, motion: Pull},
    {segId: "s101", visual: Frame("f41"), lines: [LineId(101)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s102", visual: Frame("f41"), lines: [LineId(102)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s103", visual: Frame("f41"), lines: [LineId(103)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s104", visual: Frame("f42"), lines: [LineId(104)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s105", visual: Frame("f42"), lines: [LineId(105)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s106", visual: Frame("f42"), lines: [LineId(106)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s107", visual: Frame("f42"), lines: [LineId(107)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s108", visual: Frame("f42"), lines: [LineId(108)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s109", visual: Frame("f43"), lines: [LineId(109)], hold: None, word: None, cue: Ambience("stove", 0.15), motion: Still},
    {segId: "s110", visual: Frame("f43"), lines: [LineId(110)], hold: None, word: None, cue: OneShot("partyblow", 0.45), motion: Still},
    {segId: "s111", visual: Frame("f43"), lines: [LineId(111)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s112", visual: Frame("f43"), lines: [LineId(112)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s113", visual: Frame("f43"), lines: [LineId(113)], hold: None, word: None, cue: NoCue, motion: Still},
    {segId: "s114", visual: Frame("f44"), lines: [LineId(114)], hold: None, word: Some("mashina"), cue: Ambience("stove", 0.2), motion: Still},
  ],
  scriptLines: [LineId(1), LineId(2), LineId(3), LineId(4), LineId(5), LineId(6), LineId(7), LineId(8), LineId(9), LineId(10), LineId(11), LineId(12), LineId(13), LineId(14), LineId(15), LineId(16), LineId(17), LineId(18), LineId(19), LineId(20), LineId(21), LineId(22), LineId(23), LineId(24), LineId(25), LineId(26), LineId(27), LineId(28), LineId(29), LineId(30), LineId(31), LineId(32), LineId(33), LineId(34), LineId(35), LineId(36), LineId(37), LineId(38), LineId(39), LineId(40), LineId(41), LineId(42), LineId(43), LineId(44), LineId(45), LineId(46), LineId(47), LineId(48), LineId(49), LineId(50), LineId(51), LineId(52), LineId(53), LineId(54), LineId(55), LineId(56), LineId(57), LineId(58), LineId(59), LineId(60), LineId(61), LineId(62), LineId(63), LineId(64), LineId(65), LineId(66), LineId(67), LineId(68), LineId(69), LineId(70), LineId(71), LineId(72), LineId(73), LineId(74), LineId(75), LineId(76), LineId(77), LineId(78), LineId(79), LineId(80), LineId(81), LineId(82), LineId(83), LineId(84), LineId(85), LineId(86), LineId(87), LineId(88), LineId(89), LineId(90), LineId(91), LineId(92), LineId(93), LineId(94), LineId(95), LineId(96), LineId(97), LineId(98), LineId(99), LineId(100), LineId(101), LineId(102), LineId(103), LineId(104), LineId(105), LineId(106), LineId(107), LineId(108), LineId(109), LineId(110), LineId(111), LineId(112), LineId(113), LineId(114)],
}

let () = Js.log(emitScript(plan))
