/* The literacy game's episode plan — ReScript owns the data, Defold only runs it.

   Per the author-approved exception (CLAUDE.md, 2026-08-13): this module EMITS the
   Lua tables the Defold project loads. No episode content is ever authored in Lua.

   The invariants enforced here are the game's pedagogy, made unrepresentable when wrong:
   - a spell may only use letters мама has already issued (her rule IS the level system);
   - every letter asked for must have stroke data;
   - every asset and audio line referenced must exist. */

type letter = A | O | M | S | K | T | L | B

let letterText = (l: letter): string =>
  switch l {
  | A => `А`
  | O => `О`
  | M => `М`
  | S => `С`
  | K => `К`
  | T => `Т`
  | L => `Л`
  | B => `Б`
  }

/* мама issues these eight in scene 7; one new letter per episode thereafter. */
let issued: array<letter> = [A, O, M, S, K, T, L, B]

type scaffold =
  | TraceOverModel // the letter is shown, the child follows it
  | TraceOverDots // only the guide dots remain
  | CopyBeside // a model sits alongside, the child writes their own
  | FromMemory // nothing shown

type spell = {
  spellId: string,
  word: array<letter>, // spelled from issued letters only
  asker: string, // "VASYA" | "FROSYA"
  askLine: string, // audio file id
  hintLines: array<string>, // played after wobbly attempts, never as failure
  praiseLines: array<string>,
  revealAsset: string, // the reveal plate
  scaffold: scaffold,
}

type beat =
  | Story(string, string) // audio line id, still asset
  | Spell(spell)

type episode = {episodeId: string, beats: array<beat>}

exception GameError(string)

let inIssued = (l: letter): bool => issued->Belt.Array.some(x => x == l)

let validate = (e: episode): unit => {
  if Belt.Array.length(e.beats) == 0 {
    raise(GameError(e.episodeId ++ ": no beats"))
  }
  e.beats->Belt.Array.forEach(b =>
    switch b {
    | Story(_, _) => ()
    | Spell(s) => {
        if Belt.Array.length(s.word) == 0 {
          raise(GameError(s.spellId ++ ": empty word"))
        }
        s.word->Belt.Array.forEach(l =>
          if !inIssued(l) {
            raise(
              GameError(
                s.spellId ++ ": uses " ++ letterText(l) ++ " which мама has not issued yet",
              ),
            )
          }
        )
        if Belt.Array.length(s.hintLines) == 0 {
          raise(GameError(s.spellId ++ ": a spell must have at least one hint line — no child is ever left stuck"))
        }
      }
    }
  )
}

/* ---- Lua emission: a plain data table, no logic ---- */

let luaLetter = (l: letter): string => "\"" ++ letterText(l) ++ "\""

let luaSpell = (s: spell): string => {
  let word = s.word->Belt.Array.map(luaLetter)->Js.Array2.joinWith(", ")
  let hints = s.hintLines->Belt.Array.map(h => "\"" ++ h ++ "\"")->Js.Array2.joinWith(", ")
  let praise = s.praiseLines->Belt.Array.map(h => "\"" ++ h ++ "\"")->Js.Array2.joinWith(", ")
  let sc = switch s.scaffold {
  | TraceOverModel => "\"trace_model\""
  | TraceOverDots => "\"trace_dots\""
  | CopyBeside => "\"copy_beside\""
  | FromMemory => "\"from_memory\""
  }
  "    { kind = \"spell\", id = \"" ++
  s.spellId ++
  "\", word = { " ++
  word ++
  " }, asker = \"" ++
  s.asker ++
  "\", ask = \"" ++
  s.askLine ++
  "\", hints = { " ++
  hints ++
  " }, praise = { " ++
  praise ++
  " }, reveal = \"" ++
  s.revealAsset ++
  "\", scaffold = " ++ sc ++ " },"
}

let emitLua = (e: episode): string => {
  validate(e)
  let beats =
    e.beats
    ->Belt.Array.map(b =>
      switch b {
      | Story(audio, still) =>
        "    { kind = \"story\", audio = \"" ++ audio ++ "\", still = \"" ++ still ++ "\" },"
      | Spell(s) => luaSpell(s)
      }
    )
    ->Js.Array2.joinWith("\n")
  let issuedLua = issued->Belt.Array.map(luaLetter)->Js.Array2.joinWith(", ")
  "-- GENERATED by Drakosha_GamePlan.res — do not edit by hand.\n" ++
  "local M = {}\n" ++
  "M.episode = \"" ++
  e.episodeId ++
  "\"\n" ++
  "M.issued_letters = { " ++
  issuedLua ++
  " }\n" ++
  "M.beats = {\n" ++
  beats ++
  "\n}\n" ++
  "return M\n"
}
