// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as $$Crypto from "crypto";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as Drakosha_SeedanceJobs from "./Drakosha_SeedanceJobs.res.mjs";
import * as Drakosha_SeedanceBatch from "./Drakosha_SeedanceBatch.res.mjs";

var refsDir = "../stories/drakosha/ep1prod/scene1/references";

var kfDir = "../stories/drakosha/rnd/keyframes";

var outDir = "../stories/drakosha/production/seedance_batch/emitted";

function sha256(s) {
  return $$Crypto.createHash("sha256").update(s).digest("hex");
}

var framesDir = "../stories/drakosha/production/kuku_flow/frames";

function resolveRef(p) {
  if (p.startsWith("KF:")) {
    return kfDir + "/" + p.slice(3);
  } else if (p.startsWith("FRAME:")) {
    return framesDir + "/" + p.slice(6);
  } else {
    return refsDir + "/" + p;
  }
}

var shootingScript = "../stories/drakosha/2026-08-04_EP1_den-rozhdeniya_SHOOTING_numbered_bilingual.md";

function pad3(n) {
  var x = String(n);
  var match = x.length;
  if (match !== 1) {
    if (match !== 2) {
      return x;
    } else {
      return "0" + x;
    }
  } else {
    return "00" + x;
  }
}

function shRange(shots) {
  var nums = Belt_Array.keepMap(shots.replace(/[^0-9\-]/g, " ").trim().split("-"), (function (x) {
          return Belt_Int.fromString(x.trim());
        }));
  var len = nums.length;
  if (len >= 3) {
    return [];
  }
  switch (len) {
    case 0 :
        return [];
    case 1 :
        var a = nums[0];
        return ["SH" + pad3(a)];
    case 2 :
        var a$1 = nums[0];
        var b = nums[1];
        return Belt_Array.map(Belt_Array.range(a$1, b), (function (n) {
                      return "SH" + pad3(n);
                    }));
    
  }
}

function linesForShot(script, sh) {
  var parts = script.split("### " + sh);
  var rest = Belt_Array.get(parts, 1);
  if (rest === undefined) {
    return [];
  }
  var body = Belt_Array.getExn(rest.split("### "), 0);
  return Belt_Array.keepMap(body.split("\n"), (function (l) {
                var t = l.trim();
                var speakers = [
                  "ФРОСЯ",
                  "ВАСЯ",
                  "МАМА",
                  "ПАПА",
                  "БАБУШКА-ЯГА"
                ];
                var isSpeech = t.startsWith("**") && t.includes(":**") && Belt_Array.some(speakers, (function (sp) {
                        return t.includes("**" + sp);
                      }));
                if (!isSpeech) {
                  return ;
                }
                var match = t.split(":**");
                if (match.length !== 2) {
                  return ;
                }
                var tail = match[1];
                var cleaned = tail.replace(/\*\([^)]*\)\*/g, "").trim();
                if (cleaned.length > 3) {
                  return cleaned;
                }
                
              }));
}

function bare(s) {
  return s.replace(/[^А-яЁё]/g, "").toLowerCase();
}

function assertScriptLinesPresent(record, script, problem) {
  var expected = Belt_Array.concatMany(Belt_Array.map(shRange(record.shots), (function (sh) {
              return linesForShot(script, sh);
            })));
  var creativeBare = bare(record.creative);
  Belt_Array.forEach(expected, (function (line) {
          var b = bare(line);
          var probe = b.length > 24 ? b.slice(0, 24) : b;
          if (probe.length > 8 && !creativeBare.includes(probe)) {
            return problem(record.jobId, "the script gives this shot the line \"" + line.slice(0, 60) + "…\" and the choreography does not contain it. Prompts are assembled from the script, never from notes.");
          }
          
        }));
}

function assertStartFrameBacked(record, problem) {
  var c = record.creative.toLowerCase();
  var claims = c.includes("start image") || c.includes("start frame") || c.includes("supplied start");
  var match = record.startImage;
  if (claims && match === undefined) {
    return problem(record.jobId, "the choreography tells the model it begins on a supplied start image, and no startImage is bound. Either bind one or stop promising it.");
  }
  
}

function assertSetImageBacked(record, refPaths, problem) {
  var describesSet = record.creative.includes("LOCATION MAP");
  var hasSetPlate = Belt_Array.some(refPaths, (function (p) {
          return p.includes("SET-");
        })) || record.startImage !== undefined;
  if (describesSet && !hasSetPlate) {
    return problem(record.jobId, "the choreography describes the set in LOCATION MAP prose but binds no set plate and no start image. The room must be carried by a picture, not by words.");
  }
  
}

function sceneHeadingFor(script, sh) {
  var before = Belt_Array.get(script.split("### " + sh), 0);
  if (before === undefined) {
    return ;
  }
  var heads = before.split("\n## СЦЕНА ");
  var tail = Belt_Array.get(heads, heads.length - 1 | 0);
  if (tail !== undefined) {
    return Belt_Option.map(Belt_Array.get(tail.split("\n"), 0), (function (prim) {
                  return prim.trim();
                }));
  }
  
}

function assertStartFrameSameLocation(record, script, allJobs, problem) {
  var k = record.startImage;
  if (k === undefined) {
    return ;
  }
  var tail = Belt_Array.get(k.split("from-"), 1);
  if (tail === undefined) {
    return ;
  }
  var srcId = Belt_Array.getExn(tail.split("-"), 0);
  var src = Belt_Array.getBy(allJobs, (function (r) {
          return r.jobId === srcId;
        }));
  if (src === undefined) {
    return ;
  }
  var mine = Belt_Option.flatMap(Belt_Array.get(shRange(record.shots), 0), (function (__x) {
          return sceneHeadingFor(script, __x);
        }));
  var theirs = Belt_Option.flatMap(Belt_Array.get(shRange(src.shots), 0), (function (__x) {
          return sceneHeadingFor(script, __x);
        }));
  if (mine !== undefined && theirs !== undefined && mine !== theirs) {
    return problem(record.jobId, "its start frame is lifted from " + srcId + ", but the script puts them in different places — this job is \"СЦЕНА " + mine + "\" and that one is \"СЦЕНА " + theirs + "\". A start frame only chains within one location.");
  }
  
}

var changeMarkers = [
  "widen",
  "opens",
  "drops",
  "falls",
  "tightens",
  "goes from",
  "changes",
  "shifts",
  "by the end",
  "at first",
  "starts",
  "then ",
  "no longer",
  "fades",
  "gives way",
  "turns to",
  "stops"
];

var reactionHeaders = [
  "REACTIONS",
  "REACTION"
];

function assertReactionsWritten(record, problem) {
  if (record.cast.length <= 1) {
    return ;
  }
  var c = record.creative;
  var h = Belt_Array.getBy(reactionHeaders, (function (h) {
          return c.includes(h);
        }));
  if (h === undefined) {
    return problem(record.jobId, "more than one character is in this job and the choreography never says what the NON-SPEAKING ones do with their faces. A reference sheet fixes identity, not expression — without it the model holds the sheet's expression like a mask for the whole shot. Add a REACTIONS block.");
  }
  var after = Belt_Array.getExn(c.split(h), 1);
  var block = Belt_Option.getWithDefault(Belt_Array.getExn(after.split(/\n[A-ZА-Я][A-ZА-Я ,\-]{4,}\n/), 0), after);
  var missing = Belt_Array.keepMap(Belt_Array.keep(record.cast, (function (t) {
              var n = Drakosha_SeedanceBatch.castRuName(t);
              if (n !== undefined && !block.includes(n)) {
                return !block.includes(Drakosha_SeedanceBatch.castEntry(t).tag);
              } else {
                return false;
              }
            })), Drakosha_SeedanceBatch.castRuName);
  if (missing.length !== 0) {
    problem(record.jobId, "the REACTIONS block never mentions " + missing.join(", ") + ". Every character who is in frame while somebody else speaks needs their face written, or they hold their reference sheet's expression throughout.");
  }
  var facialParts = [
    "mouth",
    "brow",
    "eyes",
    "eyelid",
    "jaw",
    "chin",
    "lips",
    "teeth",
    "forehead",
    "nostril",
    "cheek",
    "blink"
  ];
  var parts = Belt_Array.keep(facialParts, (function (w) {
          return block.toLowerCase().includes(w);
        }));
  if (parts.length < record.cast.length) {
    problem(record.jobId, "the REACTIONS block names moods rather than describing faces. \"Flat and unimpressed\" lost to a reference sheet that smiles; \"her mouth stays a level line and never turns up at the corners\" wins. Say what the mouth, brows, eyes and jaw actually do — at least one piece of anatomy per character.");
  }
  var changes = Belt_Array.keep(changeMarkers, (function (m) {
          return block.includes(m);
        }));
  if (changes.length < 2) {
    return problem(record.jobId, "the REACTIONS block describes states, not changes. A held expression is just a second mask — Фрося wore one grin through Вася's whole line in s5job2. Say what each face STARTS as and what it BECOMES (widens, drops, gives way to, by the end…).");
  }
  
}

var emotions = [
  {
    name: "SHOCK",
    belongs: [
      "mouth falls open",
      "mouth stays open",
      "jaw hangs",
      "jaw falls",
      "eyes go round",
      "eyes snap wide",
      "eyes open wide",
      "eyes go wide",
      "brows shoot up",
      "brows drive up",
      "brows go up"
    ],
    contradicts: [
      "eyes narrow",
      "brows draw in",
      "brows draw together",
      "brows draw down",
      "jaw sets",
      "lips press",
      "corner of the mouth pulls up"
    ]
  },
  {
    name: "DISBELIEF",
    belongs: [
      "mouth falls open",
      "mouth stays open",
      "jaw hangs",
      "eyes go wide",
      "eyes snap wide",
      "eyes open wide",
      "brows shoot up",
      "brows go up",
      "blinks"
    ],
    contradicts: [
      "eyes narrow",
      "brows draw in",
      "brows draw together",
      "brows draw down",
      "jaw sets",
      "lips press"
    ]
  },
  {
    name: "WONDER",
    belongs: [
      "mouth falls open",
      "mouth stays open",
      "eyes go wide",
      "eyes open wide",
      "eyes shine",
      "eyes bright",
      "brows go up",
      "brows climb"
    ],
    contradicts: [
      "eyes narrow",
      "brows draw together",
      "brows draw down",
      "jaw sets",
      "lips press"
    ]
  },
  {
    name: "DELIGHT",
    belongs: [
      "eyes squeeze",
      "eyes crinkle",
      "cheeks bunch",
      "cheeks push up",
      "mouth stretches",
      "mouth stretched",
      "grin"
    ],
    contradicts: [
      "brows draw together",
      "brows draw down",
      "jaw sets",
      "lips press",
      "mouth closes into"
    ]
  },
  {
    name: "GLEE",
    belongs: [
      "eyes squeeze",
      "eyes crinkle",
      "cheeks bunch",
      "mouth stretches",
      "mouth stretched",
      "grin",
      "squeal"
    ],
    contradicts: [
      "brows draw together",
      "brows draw down",
      "jaw sets",
      "lips press"
    ]
  },
  {
    name: "AMUSEMENT",
    belongs: [
      "corner of the mouth",
      "closed-lipped smile",
      "eyes narrow",
      "one eyebrow climbs",
      "one eyebrow rises",
      "dry"
    ],
    contradicts: [
      "jaw drops",
      "jaw hangs",
      "mouth falls open",
      "eyes go round",
      "eyes snap wide",
      "brows shoot up"
    ]
  },
  {
    name: "SATISFACTION",
    belongs: [
      "corner of the mouth",
      "closed-lipped smile",
      "eyes narrow",
      "one eyebrow climbs",
      "one eyebrow rises",
      "settles"
    ],
    contradicts: [
      "jaw drops",
      "jaw hangs",
      "mouth falls open",
      "eyes go round",
      "eyes snap wide",
      "brows shoot up"
    ]
  },
  {
    name: "UNEASE",
    belongs: [
      "mouth stays closed",
      "lips close",
      "mouth closes",
      "brows stay level",
      "eyes stay open",
      "eyes stay steady"
    ],
    contradicts: [
      "eyes narrow",
      "brows draw together",
      "brows draw in",
      "brows draw down",
      "jaw sets",
      "lips press",
      "mouth falls open",
      "jaw hangs",
      "grin"
    ]
  },
  {
    name: "CONFUSION",
    belongs: [
      "brows draw together",
      "brows lift",
      "uncertain",
      "loose O",
      "blank O",
      "mouth falls open into"
    ],
    contradicts: [
      "eyes squeeze",
      "cheeks bunch",
      "grin",
      "jaw sets"
    ]
  },
  {
    name: "WORRY",
    belongs: [
      "brows lift in the middle",
      "brows draw up",
      "mouth closes",
      "mouth tightens",
      "eyes drop"
    ],
    contradicts: [
      "grin",
      "cheeks bunch",
      "closed-lipped smile",
      "jaw hangs"
    ]
  },
  {
    name: "ANGER",
    belongs: [
      "brows draw down",
      "brows draw together",
      "jaw sets",
      "lips press",
      "eyes narrow"
    ],
    contradicts: [
      "mouth falls open",
      "jaw hangs",
      "eyes go round",
      "brows shoot up",
      "grin"
    ]
  },
  {
    name: "EAGERNESS",
    belongs: [
      "eyes widen",
      "brows lift",
      "mouth opens",
      "leans in",
      "grin",
      "bounces"
    ],
    contradicts: [
      "eyes narrow",
      "lips press",
      "jaw sets",
      "eyelids droop"
    ]
  },
  {
    name: "DETERMINATION",
    belongs: [
      "jaw sets",
      "lips press",
      "brows draw down",
      "eyes steady",
      "eyes narrow"
    ],
    contradicts: [
      "mouth falls open",
      "jaw hangs",
      "eyes go round",
      "brows shoot up"
    ]
  },
  {
    name: "DISAPPOINTMENT",
    belongs: [
      "brows tilt up",
      "inner ends",
      "brows come together",
      "corners of her mouth pull down",
      "mouth corners fall",
      "lower lip pushes",
      "shoulders come down",
      "shoulders drop",
      "eyes stay",
      "looks down",
      "settles downward",
      "hand goes still"
    ],
    contradicts: [
      "grin",
      "smiling",
      "cheeks bunch",
      "eyes squeeze",
      "brows shoot up",
      "mouth stretches wide",
      "laughing"
    ]
  },
  {
    name: "SULK",
    belongs: [
      "shoulders slump",
      "shoulders drop",
      "chin tucks",
      "chin drops",
      "lips press",
      "pout",
      "lower lip pushes",
      "brows draw down",
      "looks down",
      "eyes drop"
    ],
    contradicts: [
      "grin",
      "mouth falls open",
      "eyes go wide",
      "eyes snap wide",
      "brows shoot up",
      "cheeks bunch"
    ]
  },
  {
    name: "DISGUST",
    belongs: [
      "nose wrinkles",
      "upper lip lifts",
      "tongue",
      "eyes screw",
      "head pulls back"
    ],
    contradicts: [
      "grin",
      "cheeks bunch",
      "eyes shine"
    ]
  }
];

var emotionNames = Belt_Array.map(emotions, (function (e) {
        return e.name;
      }));

var emotionGateGrandfathered = [
  "s8shot1",
  "s8shot2",
  "s8tochka",
  "s8tochka2",
  "s8vasya",
  "s8offer",
  "s8glass",
  "s8salat",
  "s8bowl",
  "s8fu",
  "s8rusya",
  "s8mak",
  "s8poppy",
  "v01ask",
  "v02answer",
  "v03gather",
  "v04read",
  "v05single",
  "v05vzhukh",
  "v06frosya",
  "v07table"
];

function assertEmotionsDeclared(record, problem) {
  var grandfathered = Belt_Array.some(emotionGateGrandfathered, (function (j) {
          return j === record.jobId;
        }));
  if (grandfathered) {
    return ;
  }
  var c = record.creative;
  var h = Belt_Array.getBy(reactionHeaders, (function (h) {
          return c.includes("\n" + h + "\n");
        }));
  if (h === undefined) {
    return ;
  }
  var after = Belt_Array.getExn(c.split("\n" + h + "\n"), 1);
  var block = Belt_Option.getWithDefault(Belt_Array.getExn(after.split(/\n[A-ZА-Я][A-ZА-Я ,\-]{4,}\n/), 0), after);
  var paragraphs = block.split("\n\n");
  Belt_Array.forEach(Belt_Array.keepMap(record.cast, (function (t) {
              var n = Drakosha_SeedanceBatch.castRuName(t);
              if (n !== undefined) {
                return [
                        n,
                        Drakosha_SeedanceBatch.castEntry(t).tag
                      ];
              }
              
            })), (function (param) {
          var n = param[0];
          var mName = n + " — ";
          var mTag = param[1] + " — ";
          var para = Belt_Array.getBy(paragraphs, (function (p) {
                  if (p.includes(mTag)) {
                    return true;
                  } else {
                    return p.includes(mName);
                  }
                }));
          if (para === undefined) {
            return problem(record.jobId, n + " has no paragraph of their own in the REACTIONS block. Every character needs one that starts with their name, so the emotion they are playing can be named and checked against the anatomy that follows.");
          }
          var marker = para.includes(mTag) ? mTag : mName;
          var i = para.indexOf(marker);
          if (i === -1) {
            return problem(record.jobId, n + " is described without naming the emotion. Write it as \"" + n + " — EMOTION: …\" — one or two words in capitals after an em dash, then the anatomy. Without a named feeling there is nothing for the choreography to be checked against, which is how Мама's UNEASE came back as a scowl in v07table. Known words: " + emotionNames.join(", ") + ".");
          }
          var rest = para.slice(i + marker.length | 0);
          var j = rest.indexOf(":");
          if (j === -1) {
            return problem(record.jobId, n + "'s emotion is not closed with a colon. The syntax is \"" + n + " — EMOTION: …\" so the gate can tell the label from the choreography.");
          }
          var label = rest.slice(0, j).trim();
          var words = Belt_Array.keep(label.split(" "), (function (w) {
                  return w !== "";
                }));
          if (words.length < 1 || words.length > 2) {
            return problem(record.jobId, n + " declares \"" + label + "\", which is " + String(words.length) + " words. An emotion is one or two words. A sentence here is a description, and a description is what this gate exists to stop standing in for a feeling.");
          }
          var spec = Belt_Array.getBy(emotions, (function (e) {
                  return e.name === label;
                }));
          if (spec === undefined) {
            return problem(record.jobId, n + " declares \"" + label + "\", which the gate does not know, so it cannot check the choreography against it. Use one of: " + emotionNames.join(", ") + " — or add the new one to `emotions` in this file with the anatomy that belongs to it and the anatomy that contradicts it.");
          }
          var lower = para.toLowerCase();
          var n$1 = lower.length;
          var from = n$1 > 180 ? n$1 - (n$1 / 3 | 0) | 0 : 0;
          var dest = lower.slice(from);
          var negators = [
            "never",
            "not ",
            "no ",
            "without",
            "nor "
          ];
          var negatedAt = function (hay, at) {
            var from = at > 30 ? at - 30 | 0 : 0;
            var $$window = hay.slice(from, at);
            return Belt_Array.some(negators, (function (g) {
                          return $$window.includes(g);
                        }));
          };
          var has = Belt_Array.some(spec.belongs, (function (w) {
                  return lower.includes(w);
                }));
          if (!has) {
            problem(record.jobId, n + " is marked " + label + " but the choreography never does any of the things " + label + " does with a face. Put at least one of these in: " + spec.belongs.join("; ") + ".");
          }
          Belt_Array.forEach(spec.contradicts, (function (w) {
                  var at = dest.indexOf(w);
                  if (at >= 0 && !negatedAt(dest, at)) {
                    return problem(record.jobId, n + " is marked " + label + " but the choreography ENDS on \"" + w + "\", which is a different feeling on the same face. This is exactly the v07table failure: Мама was meant to be unsettled and her paragraph finished on brows drawing in, eyes narrowing and a jaw setting, so she came back angry. Either change the anatomy or change the label — but they have to agree.");
                  }
                  
                }));
        }));
}

var lineIndexPath = "../stories/drakosha/production/kuku_flow/audio/LINE_INDEX.json";

function lineKey(file) {
  var m = file.match(/^line[0-9]+_/);
  if (m !== null) {
    return Belt_Option.getWithDefault(Belt_Option.flatMap(Belt_Array.get(m, 0), (function (x) {
                      return x;
                    })), file);
  } else {
    return file;
  }
}

function isDecided(file) {
  return Belt_Array.some([
              "_FINAL",
              "_APPROVED",
              "_CONTROL"
            ], (function (mark) {
                return file.includes(mark);
              }));
}

function decidedOnly(index) {
  var settled = {};
  Belt_Array.forEach(index, (function (param) {
          var file = param[0];
          if (isDecided(file)) {
            settled[lineKey(file)] = true;
            return ;
          }
          
        }));
  return Belt_Array.keep(index, (function (param) {
                var file = param[0];
                var match = Js_dict.get(settled, lineKey(file));
                if (match !== undefined) {
                  return isDecided(file);
                } else {
                  return true;
                }
              }));
}

function loadLineIndex() {
  if (!Fs.existsSync(lineIndexPath)) {
    return [];
  }
  var raw = Fs.readFileSync(lineIndexPath, "utf8");
  var obj = Js_json.decodeObject(JSON.parse(raw));
  if (obj !== undefined) {
    return decidedOnly(Belt_Array.keepMap(Js_dict.entries(obj), (function (param) {
                      var e = Js_json.decodeObject(param[1]);
                      if (e === undefined) {
                        return ;
                      }
                      var match = Belt_Option.flatMap(Js_dict.get(e, "dur"), Js_json.decodeNumber);
                      var match$1 = Belt_Option.flatMap(Js_dict.get(e, "text"), Js_json.decodeString);
                      if (match !== undefined && match$1 !== undefined) {
                        return [
                                param[0],
                                match,
                                match$1
                              ];
                      }
                      
                    })));
  } else {
    return [];
  }
}

function findRecording(index, scriptLine) {
  var want = bare(scriptLine);
  if (want.length < 3) {
    return ;
  }
  if (want.length < 8) {
    return Belt_Option.map(Belt_Array.getBy(index, (function (param) {
                      return bare(param[2]) === want;
                    })), (function (param) {
                  return [
                          param[0],
                          param[1]
                        ];
                }));
  }
  var probe = want.length > 20 ? want.slice(0, 20) : want;
  return Belt_Option.map(Belt_Array.getBy(index, (function (param) {
                    return bare(param[2]).includes(probe);
                  })), (function (param) {
                return [
                        param[0],
                        param[1]
                      ];
              }));
}

function assertDurationHoldsAudio(record, script, problem) {
  var index = loadLineIndex();
  if (index.length === 0) {
    return ;
  }
  var declared = Belt_Array.keepMap(record.carriesLines, (function (f) {
          return Belt_Option.map(Belt_Array.getBy(index, (function (param) {
                            return param[0] === f;
                          })), (function (param) {
                        return [
                                param[0],
                                param[1]
                              ];
                      }));
        }));
  if (record.carriesLines.length !== 0 && declared.length < record.carriesLines.length) {
    problem(record.jobId, "names a recording in carriesLines that is not in LINE_INDEX.json. A job may only be sized against takes the index knows the length of.");
  }
  var lines = Belt_Array.concatMany(Belt_Array.map(shRange(record.shots), (function (sh) {
              return linesForShot(script, sh);
            })));
  var seen = {};
  var found = Belt_Array.keep(Belt_Array.keepMap(lines, (function (l) {
              return findRecording(index, l);
            })), (function (param) {
          var file = param[0];
          var match = Js_dict.get(seen, file);
          if (match !== undefined) {
            return false;
          } else {
            seen[file] = true;
            return true;
          }
        }));
  var found$1 = record.carriesLines.length !== 0 ? declared : found;
  var total = Belt_Array.reduce(found$1, 0.0, (function (acc, param) {
          return acc + param[1];
        }));
  var needed = total + 0.25 * (found$1.length - 1 | 0) + 2.0;
  var have = record.durationSec;
  if (!(found$1.length !== 0 && needed > have)) {
    return ;
  }
  var names = Belt_Array.map(found$1, (function (param) {
          return param[0] + " " + param[1].toFixed(2) + "s";
        }));
  problem(record.jobId, "duration is " + String(record.durationSec) + "s but the APPROVED AUDIO for these shots needs " + needed.toFixed(1) + "s — " + names.join(", ") + ". Set the duration from the recorded reads, never from the script's estimates; otherwise the dub has to be sped up.");
}

function assertModelFits(spec, refCount, problem) {
  var m = spec.model;
  var name = Drakosha_SeedanceJobs.modelName(m);
  var maxSec = Drakosha_SeedanceJobs.modelMaxSec(m);
  var maxRefs = Drakosha_SeedanceJobs.modelMaxRefs(m);
  if (spec.record.durationSec > maxSec) {
    problem(spec.record.jobId, "asks for " + String(spec.record.durationSec) + "s on " + name + ", which generates at most " + String(maxSec) + "s. Either move the job to seedance_2_5 or split the shots — never let it truncate.");
  }
  var match = spec.model;
  switch (match) {
    case "Kling26" :
    case "Kling30" :
    case "Veo31Lite" :
        break;
    default:
      if (refCount > maxRefs) {
        return problem(spec.record.jobId, "binds " + String(refCount) + " image references but " + name + " accepts " + String(maxRefs) + ". The extras are dropped without an error and the shot comes back off-model.");
      } else {
        return ;
      }
  }
  var match$1 = spec.record.startImage;
  if (match$1 !== undefined) {
    
  } else {
    problem(spec.record.jobId, "runs on " + name + ", which takes no image references. With no start frame either, nothing in the call says who she is. Give it a start frame.");
  }
  var match$2 = spec.model;
  var match$3 = spec.endImage;
  if (match$2 === "Kling26" && match$3 !== undefined) {
    return problem(spec.record.jobId, "declares an end frame, but only kling3_0 accepts one. On kling2_6 it is silently ignored and the clip will not loop.");
  }
  
}

var creditTotal = {
  contents: 0.0
};

function assertTagLinesAreIdentityOnly(record, problem) {
  Belt_Array.forEach(record.cast, (function (t) {
          var entry = Drakosha_SeedanceBatch.castEntry(t);
          var held = [
            " in hand",
            "in her hand",
            "in his hand",
            "holding a",
            "holding her",
            "no pencil",
            "empty-handed"
          ];
          Belt_Array.forEach(held, (function (phrase) {
                  if (entry.tagLine.toLowerCase().includes(phrase)) {
                    return problem(record.jobId, "the reference line for " + entry.tag + " says \"" + phrase.trim() + "\" — that is what is in their hands, which changes shot to shot and belongs in the choreography. A reference line fixes identity only, or every job in the episode inherits one pose.");
                  }
                  
                }));
        }));
}

var handsHeaders = [
  "\nHANDS — ",
  "\nHANDS - ",
  "\nHANDS: "
];

var handsVerbs = [
  "holding",
  "holds",
  "grips",
  "gripping",
  "resting",
  "rests",
  "closed around",
  "open at",
  "open and",
  "tucked",
  "folded",
  "pressed",
  "planted",
  "hooked",
  "clutch",
  "cupped",
  "hangs",
  "hanging",
  "raises",
  "raised",
  "crooks",
  "reaching",
  "carries",
  "wrapped",
  "spread",
  "flat against",
  "hang ",
  "come up",
  "comes up"
];

function assertHandsWritten(record, problem) {
  var c = record.creative;
  var h = Belt_Array.getBy(handsHeaders, (function (h) {
          return c.includes(h);
        }));
  if (h === undefined) {
    return problem(record.jobId, "the choreography has no HANDS block. Every character's hands must be stated positively in every job, or the reference sheet puts back whatever it shows them holding — which is how Бабушка-Яга carried her broom through a scene in which she was giving away two gifts.");
  }
  var after = Belt_Array.getExn(c.split(h), 1);
  var block = Belt_Option.getWithDefault(Belt_Array.getExn(after.split(/\n[A-ZА-Я][A-ZА-Я ,\-]{4,}\n/), 0), after);
  var missing = Belt_Array.keepMap(Belt_Array.keep(record.cast, (function (t) {
              var n = Drakosha_SeedanceBatch.castRuName(t);
              if (n !== undefined && !block.includes(n)) {
                return !block.includes(Drakosha_SeedanceBatch.castEntry(t).tag);
              } else {
                return false;
              }
            })), Drakosha_SeedanceBatch.castRuName);
  if (missing.length !== 0) {
    problem(record.jobId, "the HANDS block never says what " + missing.join(", ") + " is doing with their hands. An unwritten pair of hands is filled from the reference sheet.");
  }
  var lower = block.toLowerCase();
  var verbs = Belt_Array.keep(handsVerbs, (function (v) {
          return lower.includes(v);
        }));
  if (verbs.length < record.cast.length) {
    return problem(record.jobId, "the HANDS block leans on prohibitions rather than saying what the hands ARE doing. \"No broom\" lost to a reference sheet that shows one; \"her hands hang open and empty at her sides\" wins, because it occupies the same cell. Give every character a positive hand action.");
  }
  
}

var namedWalls = [
  "hatch wall",
  "hatch-wall",
  "ramp",
  "railing",
  "back wall",
  "kitchen end",
  "niche",
  "table end",
  "boulder-block wall",
  "no wall",
  "shows no wall"
];

var wallFeatures = [
  "hatch",
  "niche",
  "ramp",
  "railing",
  "stove",
  "iron door"
];

var bareWords = [
  "bare run",
  "plain run",
  "bare wall",
  "plain wall",
  "blank wall",
  "nothing is set into",
  "nothing stands against"
];

function assertNamedFeaturesAreBacked(record, refPaths, problem) {
  var c = record.creative;
  if (!c.includes("\nBACKGROUNDS")) {
    return ;
  }
  var after = Belt_Array.getExn(c.split("\nBACKGROUNDS"), 1);
  var block = Belt_Option.getWithDefault(Belt_Array.getExn(after.split(/\n[A-ZА-Я][A-ZА-Я ,\-]{4,}\n/), 0), after);
  var lower = block.toLowerCase();
  var backing = Belt_Array.map(refPaths, (function (prim) {
          return prim.toLowerCase();
        }));
  var match = record.startImage;
  var hasStartImage = match !== undefined;
  var callsItBare = Belt_Array.some(bareWords, (function (w) {
          return lower.includes(w);
        }));
  Belt_Array.forEach(wallFeatures, (function (f) {
          var named = lower.includes(f);
          var inRefs = Belt_Array.some(backing, (function (b) {
                  return b.includes(f);
                }));
          if (named && !inRefs) {
            if (hasStartImage) {
              if (callsItBare) {
                return problem(record.jobId, "the BACKGROUNDS block names \"" + f + "\" and in the same breath calls that wall bare or plain. Both cannot be true of the frame in front of you: either the plate shows the feature, in which case describe it, or it does not, in which case do not name it. This is the sentence that put a hatch on a blank run of stone.");
              } else {
                return ;
              }
            } else {
              return problem(record.jobId, "the BACKGROUNDS block names \"" + f + "\" and there is no start frame and no bound reference that shows one. With nothing to look at, a named feature is simply an instruction to invent one.");
            }
          }
          
        }));
}

function assertGlyphsPlanned(record, problem) {
  var c = record.creative;
  var lower = c.toLowerCase();
  var hasLetters = lower.includes("фишк") || lower.includes("tile") || lower.includes("букв") || lower.includes("слово") || lower.includes("letter");
  if (!hasLetters) {
    return ;
  }
  if (!c.includes("\nGLYPHS")) {
    return problem(record.jobId, "this shot has letters in it and no GLYPHS block. Every glyph the model draws is assumed wrong — scene 7 lost every single letter shot. State how this shot survives that: either NOT READABLE (the letters are texture and nobody reads them), or REPAINT with the camera hold and the moment the letters are at rest, or PLATE if the letters are our art over a generated plate.");
  }
  var after = Belt_Array.getExn(c.split("\nGLYPHS"), 1);
  var block = Belt_Array.getExn(after.split("\n\n"), 0);
  var up = block.toUpperCase();
  var planned = up.includes("NOT READABLE") || up.includes("REPAINT") || up.includes("PLATE");
  if (!planned) {
    problem(record.jobId, "the GLYPHS block names no strategy. It must say NOT READABLE, REPAINT or PLATE.");
  }
  if (up.includes("REPAINT") && !up.includes("AT REST")) {
    return problem(record.jobId, "a REPAINT shot must say when the letters are AT REST — glyphs can only be replaced cleanly on tiles or paper that are not moving. If they never come to rest, the shot cannot be repainted and needs a different plan.");
  }
  
}

function assertBackgroundsAssigned(record, problem) {
  var c = record.creative;
  if (!c.includes("\nBACKGROUNDS")) {
    return problem(record.jobId, "the choreography has no BACKGROUNDS block. Every character in frame must be placed against a named wall of the hall — the hatch wall, the ramp side, the back wall, or the table end — or the shot must say it shows no wall at all.");
  }
  var after = Belt_Array.getExn(c.split("\nBACKGROUNDS"), 1);
  var block = Belt_Option.getWithDefault(Belt_Array.getExn(after.split(/\n[A-ZА-Я][A-ZА-Я ,\-]{4,}\n/), 0), after);
  var blockLower = block.toLowerCase();
  var missing = Belt_Array.keepMap(Belt_Array.keep(record.cast, (function (t) {
              var n = Drakosha_SeedanceBatch.castRuName(t);
              if (n !== undefined && !blockLower.includes(n.toLowerCase())) {
                return !block.includes(Drakosha_SeedanceBatch.castEntry(t).tag);
              } else {
                return false;
              }
            })), Drakosha_SeedanceBatch.castRuName);
  if (missing.length !== 0) {
    problem(record.jobId, "the BACKGROUNDS block never says what is behind " + missing.join(", ") + ". A character with no wall behind them is a character the audience cannot place, and the model puts a different room back there in every shot.");
  }
  var lower = block.toLowerCase();
  var walls = Belt_Array.keep(namedWalls, (function (w) {
          return lower.includes(w);
        }));
  var deferredToPlate = lower.includes("start image") || lower.includes("start frame") || lower.includes("the plate");
  var match = record.startImage;
  var hasStartImage = match !== undefined;
  if (walls.length === 0 && !(hasStartImage && deferredToPlate)) {
    return problem(record.jobId, "the BACKGROUNDS block names no wall of the hall. \"Soft and out of focus\" describes the lens, not the room. Name the hatch wall, the ramp and its railing, the back wall with the niche, or the table end — or say the framing shows no wall. This job has a start frame, so \"as the start image has it\" is also a valid answer: the plate already settles the wall and outranks anything written here.");
  }
  
}

function assertShotCodeResolves(record, problem) {
  var codes = shRange(record.shots);
  if (codes.length !== 0) {
    return ;
  }
  var c = record.creative;
  var declared = c.includes("NON-SCRIPT ELEMENT") && c.includes("WHY:");
  if (!declared) {
    return problem(record.jobId, "the shot code \"" + record.shots + "\" contains no SH number, so every script-derived check silently skipped: the line check, the recording check and the duration check all passed because they had nothing to look at. Either give this job its real SH numbers, or put a NON-SCRIPT ELEMENT block in the creative with a WHY: line saying what it is and why the script does not cover it.");
  }
  
}

function assertQuotedLinesRecorded(record, problem) {
  var c = record.creative;
  var out = [];
  var re = /«([^»]{2,140})»/g;
  var loop = function () {
    while(true) {
      var m = re.exec(c);
      if (m === null) {
        return ;
      }
      var t = Belt_Option.flatMap(Belt_Array.get(m, 1), (function (x) {
              if (x == null) {
                return ;
              } else {
                return Caml_option.some(x);
              }
            }));
      if (t !== undefined) {
        var tt = t.trim();
        if (tt.length > 2 && /[\u0400-\u04FF]/.test(tt)) {
          out.push(tt);
        }
        
      }
      continue ;
    };
  };
  loop();
  if (out.length === 0) {
    return ;
  }
  var index = loadLineIndex();
  if (index.length === 0) {
    return ;
  }
  var missing = Belt_Array.keep(out, (function (l) {
          return Belt_Option.isNone(findRecording(index, l));
        }));
  if (missing.length !== 0) {
    return problem(record.jobId, "the choreography quotes " + Belt_Array.map(missing, (function (m) {
                        return "«" + m.trim() + "»";
                      })).join(", ") + " and there is no recording of it in the line index. Record it first. A shot built around a line nobody has said yet is a shot built on a guess about its length and its reading.");
  }
  
}

function assertFaceWorkHasReferences(spec, refCount, problem) {
  var c = spec.record.creative;
  var wantsFace = c.includes("\nFACES") || c.includes("\nREACTIONS");
  var maxRefs = Drakosha_SeedanceJobs.modelMaxRefs(spec.model);
  if (wantsFace && maxRefs === 0 && refCount === 0) {
    return problem(spec.record.jobId, "asks for a performance (it has a FACES block) on " + Drakosha_SeedanceJobs.modelName(spec.model) + ", which takes no reference images at all. On 2026-08-20 this produced a blank-faced child twice. Expression on this show comes from the bound character sheets; move the job to a Seedance model, which takes a start frame, an end frame AND references together.");
  }
  
}

function assertStartFrameNative(record, problem) {
  var k = record.startImage;
  if (k === undefined) {
    return ;
  }
  var prov = "../stories/drakosha/rnd/keyframes/" + k + ".provenance.json";
  if (!Fs.existsSync(prov)) {
    return ;
  }
  var txt = Fs.readFileSync(prov, "utf8");
  if (txt.includes("\"native\": false") || txt.includes("\"upscaled\": true")) {
    return problem(record.jobId, "start frame " + k + " is recorded as an upscaled crop. Feeding the model a frame with fewer real pixels than it claims is how the pencil grew a metal band and the child stopped looking like herself. Re-cut the frame at native resolution, or shoot the wider framing and crop the OUTPUT instead.");
  }
  
}

var fail = {
  contents: false
};

function problem(jobId, msg) {
  fail.contents = true;
  console.log("  FAIL  " + jobId + ": " + msg);
}

Fs.mkdirSync(outDir, {
      recursive: true
    });

var manifestLines = [];

Belt_Array.forEach(Drakosha_SeedanceJobs.all, (function (spec) {
        var jobId = spec.record.jobId;
        var creative = Fs.existsSync(spec.creativeFile) ? Fs.readFileSync(spec.creativeFile, "utf8") : (problem(jobId, "missing creative file " + spec.creativeFile), "");
        var init = spec.record;
        var record_jobId = init.jobId;
        var record_shots = init.shots;
        var record_cast = init.cast;
        var record_props = init.props;
        var record_startImage = init.startImage;
        var record_durationSec = init.durationSec;
        var record_carriesLines = init.carriesLines;
        var record = {
          jobId: record_jobId,
          shots: record_shots,
          cast: record_cast,
          props: record_props,
          startImage: record_startImage,
          durationSec: record_durationSec,
          creative: creative,
          carriesLines: record_carriesLines
        };
        var match = spec.model;
        var floorSec;
        switch (match) {
          case "Kling26" :
          case "Kling30" :
              floorSec = 3;
              break;
          default:
            floorSec = 4;
        }
        if (record_durationSec < floorSec || record_durationSec > 30) {
          problem(jobId, "invalid duration — " + Drakosha_SeedanceJobs.modelName(spec.model) + " takes " + String(floorSec) + " to 30 seconds");
        }
        var prompt;
        try {
          prompt = Drakosha_SeedanceBatch.emitPrompt(record);
        }
        catch (raw_m){
          var m = Caml_js_exceptions.internalToOCamlException(raw_m);
          if (m.RE_EXN_ID === Drakosha_SeedanceBatch.BatchError) {
            problem(jobId, m._1);
            prompt = undefined;
          } else {
            throw m;
          }
        }
        if (prompt === undefined) {
          return ;
        }
        if (Fs.existsSync(shootingScript)) {
          var sc = Fs.readFileSync(shootingScript, "utf8");
          assertScriptLinesPresent(record, sc, problem);
          assertDurationHoldsAudio(record, sc, problem);
          assertStartFrameSameLocation(record, sc, Belt_Array.concat(Belt_Array.map(Drakosha_SeedanceJobs.all, (function (s) {
                          return s.record;
                        })), Belt_Array.concat(Drakosha_SeedanceJobs.retired, Drakosha_SeedanceJobs.retiredBatch)), problem);
        }
        assertStartFrameBacked(record, problem);
        assertReactionsWritten(record, problem);
        assertEmotionsDeclared(record, problem);
        assertHandsWritten(record, problem);
        assertBackgroundsAssigned(record, problem);
        assertGlyphsPlanned(record, problem);
        assertShotCodeResolves(record, problem);
        assertQuotedLinesRecorded(record, problem);
        assertStartFrameNative(record, problem);
        var refPaths = Belt_Array.map(Drakosha_SeedanceBatch.emitRefPaths(record), resolveRef);
        assertNamedFeaturesAreBacked(record, refPaths, problem);
        Belt_Array.forEach(refPaths, (function (p) {
                if (!Fs.existsSync(p)) {
                  return problem(jobId, "missing reference " + p);
                }
                
              }));
        assertSetImageBacked(record, refPaths, problem);
        var k = record_startImage;
        var start;
        if (k !== undefined) {
          var p = resolveRef(k.includes(":") ? k : "KF:" + k);
          if (!Fs.existsSync(p)) {
            problem(jobId, "missing start image " + p);
          }
          start = p;
        } else {
          start = "";
        }
        Fs.writeFileSync(outDir + "/" + jobId + ".prompt.txt", prompt);
        var d = {};
        d["model"] = Drakosha_SeedanceJobs.modelName(spec.model);
        d["duration"] = record_durationSec;
        d["startImage"] = start;
        var e = spec.endImage;
        if (e !== undefined) {
          d["endImage"] = kfDir + "/" + e;
        }
        d["imageReferences"] = Belt_Array.map(refPaths, (function (prim) {
                return prim;
              }));
        d["promptSha256"] = sha256(prompt);
        Fs.writeFileSync(outDir + "/" + jobId + ".args.json", JSON.stringify(d, null, 2));
        var castCount = record_cast.length;
        var refCount = refPaths.length;
        assertModelFits(spec, refCount, problem);
        assertFaceWorkHasReferences(spec, refCount, problem);
        assertTagLinesAreIdentityOnly(record, problem);
        var credits = Drakosha_SeedanceJobs.modelCreditsPerSec(spec.model) * record_durationSec;
        creditTotal.contents = creditTotal.contents + credits;
        manifestLines.push(jobId + "  " + record_shots + "  cast=" + String(castCount) + "  refs=" + String(refCount) + "  start=" + (
              start === "" ? "none" : "yes"
            ) + "  model=" + Drakosha_SeedanceJobs.modelName(spec.model) + "  cr=" + credits.toFixed(1) + "  sha=" + sha256(prompt).slice(0, 12));
        console.log("  OK    " + jobId + "  " + record_shots + "  cast " + String(castCount) + ", refs " + String(refCount) + (
              start === "" ? ", text+refs only" : ", start-image"
            ));
      }));

var ledger = "TOTAL " + creditTotal.contents.toFixed(1) + " credits (~$" + (creditTotal.contents * 0.043).toFixed(2) + " at the Ultra rate) for this batch.";

Fs.writeFileSync(outDir + "/BATCH_MANIFEST.txt", manifestLines.join("\n") + "\n" + ledger + "\n");

console.log("  " + ledger);

if (fail.contents) {
  console.log("DRY RUN: FAIL — fix the rows above; nothing may be submitted.");
  process.exit(1);
} else {
  console.log("DRY RUN: PASS — emitted artifacts in " + outDir + " for review.");
}

var gapSec = 0.25;

var nonDialogueHeadSec = 2.0;

export {
  refsDir ,
  kfDir ,
  outDir ,
  sha256 ,
  framesDir ,
  resolveRef ,
  shootingScript ,
  pad3 ,
  shRange ,
  linesForShot ,
  bare ,
  assertScriptLinesPresent ,
  assertStartFrameBacked ,
  assertSetImageBacked ,
  sceneHeadingFor ,
  assertStartFrameSameLocation ,
  changeMarkers ,
  reactionHeaders ,
  assertReactionsWritten ,
  emotions ,
  emotionNames ,
  emotionGateGrandfathered ,
  assertEmotionsDeclared ,
  lineIndexPath ,
  lineKey ,
  isDecided ,
  decidedOnly ,
  loadLineIndex ,
  findRecording ,
  gapSec ,
  nonDialogueHeadSec ,
  assertDurationHoldsAudio ,
  assertModelFits ,
  creditTotal ,
  assertTagLinesAreIdentityOnly ,
  handsHeaders ,
  handsVerbs ,
  assertHandsWritten ,
  namedWalls ,
  wallFeatures ,
  bareWords ,
  assertNamedFeaturesAreBacked ,
  assertGlyphsPlanned ,
  assertBackgroundsAssigned ,
  assertShotCodeResolves ,
  assertQuotedLinesRecorded ,
  assertFaceWorkHasReferences ,
  assertStartFrameNative ,
  fail ,
  problem ,
}
/* emotionNames Not a pure module */
