/* Kuku_Engine.res — the ONE generation engine.

   Author's law (2026-08-28): every prompt is formatted and generated by the
   same engine; character references are always attached; the backplate exists
   before the shot; a new character's sheet exists before the character appears.
   This module is that law made structural. A driver supplies a typed spec and
   nothing else — the engine renders the prompt (through the PromptGate),
   assembles every reference, REFUSES on any missing premise, guards the budget
   before the provider call, books spend only on success, and writes a receipt
   beside every asset it produces.

   The receipt (<asset>.gen.json) is the point. It records the engine version,
   the prompt, the model and params, and the sha256 of every reference the
   asset was generated from. "Was this generated by the engine, from current
   premises?" stops being a claim and becomes a file: an asset whose receipt
   is missing, or whose reference hashes have drifted from what is on disk
   today, is mechanically stale — which is how a regeneration campaign knows
   exactly what it owes. The h13 incident (a clip generated against a frame
   the bible had left behind, caught only by looking) is the class this kills.

   Premise refusals name what to make first, in dependency order:
     PREMISE MISSING: plate — a shot's backplate is generated before the shot
     PREMISE MISSING: sheet — a character's board exists before the character
     PREMISE STALE:   receipt hash drift — regenerate the premise, then this */

module P = Kuku_PromptSpec

type execOpts = {"encoding": string, "timeout": int}
@module("child_process")
external execFileSync: (string, array<string>, execOpts) => string = "execFileSync"
@module("fs") external existsSync: string => bool = "existsSync"
@module("fs") external writeFileSync: (string, string) => unit = "writeFileSync"
@module("fs") external readFileSync: (string, string) => string = "readFileSync"
type buffer
@module("fs") external readFileBuf: string => buffer = "readFileSync"
type hash
@module("crypto") external createHash: string => hash = "createHash"
@send external hashUpdateBuffer: (hash, buffer) => hash = "update"
@send external hashUpdateText: (hash, string, string) => hash = "update"
@send external hashDigest: (hash, string) => string = "digest"
@scope("Date") @val external now: unit => float = "now"
@new external mkDate: float => Js.Date.t = "Date"

let version = "kuku-engine/1"
let opts = {"encoding": "utf8", "timeout": 1800000}

let sha256File = p => createHash("sha256")->hashUpdateBuffer(readFileBuf(p))->hashDigest("hex")

/* A reference may be a provider-side asset id (the style key) rather than a
   local file. Those are exempt from existence checks and hash as themselves. */
let isProviderAsset = r =>
  Js.Re.test_(Js.Re.fromString("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"), r)
let refHash = r => isProviderAsset(r) ? "PROVIDER_ASSET:" ++ r : existsSync(r) ? sha256File(r) : "ABSENT"
let sha256Text = t => createHash("sha256")->hashUpdateText(t, "utf8")->hashDigest("hex")

/* ---- refusals -------------------------------------------------------------- */
let refuse = (kind, what, remedy) =>
  Js.Exn.raiseError("PREMISE " ++ kind ++ ": " ++ what ++ " — " ++ remedy)

let requireFile = (label, p) =>
  isProviderAsset(p) || existsSync(p) ? p : refuse("MISSING", label ++ " " ++ p, "generate it first")

/* Every character in a spec must carry a sheet. This is where गौरी (no sheet)
   and small वैस्पर (no small sheet) stop being silent omissions and become
   named work items. Props are exempt: a prop is described, a character is
   referenced. */
let requireBoards = (subjects: array<P.subject>) =>
  Js.Array2.forEach(subjects, sub =>
    switch sub {
    | P.Prop(_) => ()
    | _ =>
      switch P.boardOf(sub) {
      | Some(b) => ignore(requireFile("character sheet", b))
      | None =>
        refuse(
          "MISSING",
          "character sheet for " ++
          switch sub {
          | P.Dragon({name}) => P.nameOf(name)
          | P.Gauri(_) => "GAURI"
          | P.RishiMuni(_) => "RISHI"
          | P.Dadi(_) => "DADI"
          | P.Cheel(_) => "CHEEL"
          | P.Papa(_) => "PAPA"
          | P.Kalu(_) => "KALU"
          | P.Prop(_) => "?"
          },
          "generate the sheet first, register it in boardOf, then rerun",
        )
      }
    }
  )

/* ---- receipts -------------------------------------------------------------- */
let receiptPath = asset => asset ++ ".gen.json"

/* THE LAW IS PART OF THE PREMISE. A receipt records the hash of the compiled
   renderer, gate and engine that produced its prompt; when any of them changes,
   every asset made before is stale — no more eyeballing which frames predate
   which rule. */
let lawFiles = ["src/Kuku_PromptSpec.res.mjs", "src/PromptGate.res.mjs", "src/Kuku_Engine.res.mjs"]
let rulesSha = () =>
  sha256Text(Js.Array2.joinWith(Js.Array2.map(lawFiles, f => existsSync(f) ? sha256File(f) : "ABSENT"), "|"))

/* ============================================================================
   NO BARE BUILT-INS ACROSS THIS BOUNDARY, AND ONE LIST FOR THE CALL.

   Two defects in this file were the same defect. On 2026-09-02 `clip` built a
   reference list for the RECEIPT and an argument list for the CALL, and a change
   added the set anchors to the first only — ten clip receipts then claimed a
   style key and a plate the provider never received, which is the one thing a
   receipt must never be able to do. And every path here was `string`, so a start
   frame and an end frame were the same type to the compiler.

   Both are now impossible to express. A `reference` carries its own role and
   renders BOTH the CLI flag and the receipt row, so the two cannot disagree;
   `run` assembles the command itself, so no caller can hand it a mismatched
   pair. Start and end frames are distinct unboxed types: passing one where the
   other belongs is a build error, not a bad render found after the charge.
   ============================================================================ */
@unboxed type shotId = ShotId(string)
@unboxed type startFrame = StartFrame(string)
@unboxed type endFrame = EndFrame(string)
@unboxed type seconds = Seconds(int)

let shotIdText = (ShotId(s)) => s
let startPath = (StartFrame(s)) => s
let endPath = (EndFrame(s)) => s
let secondsInt = (Seconds(n)) => n

type reference =
  | Style(string)
  | Plate(string)
  | Object(string)
  | Board(string)
  | Start(startFrame)
  | End(endFrame)
  | Video(string)

let pathOf = r =>
  switch r {
  | Style(p) | Plate(p) | Object(p) | Board(p) | Video(p) => p
  | Start(f) => startPath(f)
  | End(f) => endPath(f)
  }

let roleOf = r =>
  switch r {
  | Style(_) => "style"
  | Plate(_) => "plate"
  | Object(_) => "object"
  | Board(_) => "board"
  | Start(_) => "start"
  | End(_) => "end"
  | Video(_) => "video"
  }

/* a still takes --image; a clip takes --image-references plus the frame flags */
let flagOf = (~forClip, r) =>
  switch r {
  | Start(_) => "--start-image"
  | End(_) => "--end-image"
  | Video(_) => "--video-references"
  | Style(_) | Plate(_) | Object(_) | Board(_) => forClip ? "--image-references" : "--image"
  }

/* ============================================================================
   REFERENCE ORDER IS A PROPERTY OF THE MODEL, NOT A HABIT.

   Measured 2026-09-04 on one shot, same prompt, same seven references:

     nano_banana_pro   style first  plate 0.393  cast 5/5   <- current
     nano_banana_pro   plate first  plate 0.402  cast 3/5   <- set better, cast lost
     seedream_v5_pro   style first  plate 0.083  cast 3/5   <- reinvented the set
     seedream_v5_pro   plate first  plate 0.318  cast 5/5   <- rescued

   Whichever reference sits first dominates, and the models disagree about the
   cost of that. So the order is chosen per model here, once, and every driver
   inherits it — rather than each caller assembling an array and hoping.
   ============================================================================ */
type refOrder = StyleFirst | PlateFirst

let orderFor = model =>
  switch model {
  | "seedream_v5_pro" | "seedream_v5_lite" | "seedream_v4_5" => PlateFirst
  | _ => StyleFirst
  }

let rank = (o, r) =>
  switch (o, r) {
  | (StyleFirst, Style(_)) => 0
  | (StyleFirst, Plate(_)) => 1
  | (PlateFirst, Plate(_)) => 0
  | (PlateFirst, Style(_)) => 1
  | (_, Start(_)) => 0
  | (_, End(_)) => 2
  | (_, Object(_)) => 3
  | (_, Board(_)) => 4
  | (_, Video(_)) => 5
  }

/* stable sort: equal ranks keep the order the renderer chose */
let ordered = (~model, refs: array<reference>) => {
  let o = orderFor(model)
  let withIdx = Js.Array2.mapi(refs, (r, i) => (r, i))
  let sorted = Js.Array2.copy(withIdx)
  Js.Array2.sortInPlaceWith(sorted, ((a, ai), (b, bi)) => {
    let d = rank(o, a) - rank(o, b)
    d != 0 ? d : ai - bi
  })->ignore
  Js.Array2.map(sorted, ((r, _)) => r)
}

let argsOfRefs = (~forClip, refs: array<reference>) =>
  Js.Array2.reduce(refs, (acc, r) => Js.Array2.concat(acc, [flagOf(~forClip, r), pathOf(r)]), [])

let writeReceipt = (~asset, ~kind, ~id, ~prompt, ~refs: array<reference>, ~model, ~params: array<string>, ~credits) => {
  let refRows = Js.Array2.map(refs, r =>
    Js.Json.object_(
      Js.Dict.fromArray([
        ("path", Js.Json.string(pathOf(r))),
        ("role", Js.Json.string(roleOf(r))),
        ("sha256", Js.Json.string(refHash(pathOf(r)))),
      ]),
    )
  )
  let o = Js.Dict.fromArray([
    ("engine", Js.Json.string(version)),
    ("kind", Js.Json.string(kind)),
    ("id", Js.Json.string(id)),
    ("at", Js.Json.string(Js.Date.toISOString(mkDate(now())))),
    ("model", Js.Json.string(model)),
    ("credits", Js.Json.number(credits)),
    ("assetSha256", Js.Json.string(existsSync(asset) ? sha256File(asset) : "ABSENT")),
    ("promptSha256", Js.Json.string(sha256Text(prompt))),
    ("rulesSha256", Js.Json.string(rulesSha())),
    ("prompt", Js.Json.string(prompt)),
    ("params", Js.Json.stringArray(params)),
    ("refs", Js.Json.array(refRows)),
  ])
  writeFileSync(receiptPath(asset), Js.Json.stringifyWithSpace(Js.Json.object_(o), 1) ++ "\n")
}

/* An asset is CURRENT when its receipt exists, was written by this engine, and
   every reference it names still hashes to what is on disk. Anything else is
   stale — including everything generated before receipts existed, which is the
   honest verdict: nothing predating the engine can prove its premises. */
type freshness = Current | NoReceipt | RefDrift(string) | PromptDrift | AssetDrift | RulesDrift

let freshness = (~asset, ~prompt) =>
  if !existsSync(receiptPath(asset)) {
    NoReceipt
  } else {
    switch Js.Json.decodeObject(Js.Json.parseExn(readFileSync(receiptPath(asset), "utf8"))) {
    | None => NoReceipt
    | Some(o) => {
        let str = k => o->Js.Dict.get(k)->Belt.Option.flatMap(Js.Json.decodeString)
        let drift = ref(None)
        switch o->Js.Dict.get("refs")->Belt.Option.flatMap(Js.Json.decodeArray) {
        | Some(rows) =>
          Js.Array2.forEach(rows, row =>
            switch Js.Json.decodeObject(row) {
            | Some(r) => {
                let p = r->Js.Dict.get("path")->Belt.Option.flatMap(Js.Json.decodeString)
                let h = r->Js.Dict.get("sha256")->Belt.Option.flatMap(Js.Json.decodeString)
                switch (p, h, drift.contents) {
                | (Some(p), Some(h), None) =>
                  if refHash(p) != h {
                    drift := Some(p)
                  }
                | _ => ()
                }
              }
            | None => ()
            }
          )
        | None => ()
        }
        switch drift.contents {
        | Some(p) => RefDrift(p)
        | None =>
          switch str("assetSha256") {
          | Some(h) if existsSync(asset) && sha256File(asset) != h => AssetDrift
          | _ =>
            str("rulesSha256") != Some(rulesSha())
              ? RulesDrift
              : str("promptSha256") == Some(sha256Text(prompt)) ? Current : PromptDrift
          }
        }
      }
    }
  }

/* A premise asset is INTACT when its receipt exists, every reference it was
   generated from still hashes the same, and its own pixels are the ones the
   receipt recorded. This is the recursive staleness check: regenerate a plate
   and every frame generated from it goes non-intact, and every clip resting on
   those frames refuses until they are remade. */
let receiptIntact = asset =>
  if !existsSync(receiptPath(asset)) {
    false
  } else {
    switch Js.Json.decodeObject(Js.Json.parseExn(readFileSync(receiptPath(asset), "utf8"))) {
    | None => false
    | Some(o) => {
        let ok = ref(true)
        switch o->Js.Dict.get("refs")->Belt.Option.flatMap(Js.Json.decodeArray) {
        | Some(rows) =>
          Js.Array2.forEach(rows, row =>
            switch Js.Json.decodeObject(row) {
            | Some(r) =>
              switch (
                r->Js.Dict.get("path")->Belt.Option.flatMap(Js.Json.decodeString),
                r->Js.Dict.get("sha256")->Belt.Option.flatMap(Js.Json.decodeString),
              ) {
              | (Some(p), Some(h)) => if refHash(p) != h { ok := false }
              | _ => ()
              }
            | None => ()
            }
          )
        | None => ()
        }
        switch o->Js.Dict.get("assetSha256")->Belt.Option.flatMap(Js.Json.decodeString) {
        | Some(h) => if !existsSync(asset) || sha256File(asset) != h { ok := false }
        | None => ()
        }
        ok.contents
      }
    }
  }

/* ---- the one provider call ------------------------------------------------- */
/* THE RESULT URL IS A NAMED FIELD, NOT THE FIRST LINK IN THE BLOB. The response
   echoes every input media before the output, so a first-match regex handed back
   the video reference we had just uploaded — 54 credits spent and the previz
   downloaded over itself. Read result_url; fall back to a delivery-host match. */
let resultUrl = (raw, ext) =>
  switch Js.String2.match_(raw, Js.Re.fromStringWithFlags("\"result_url\"\\s*:\\s*\"(https://[^\"]+)\"", ~flags="")) {
  | Some(m) =>
    switch m[1] {
    | Some(u) => Some(u)
    | None => None
    }
  | None =>
    /* delivery host only: inputs live on the upload host, results on d8j0… */
    switch Js.String2.match_(raw, Js.Re.fromString("https://d8j0[^\"\\s]*\\." ++ ext)) {
    | Some(m) => m[0]
    | None => None
    }
  }

let firstUrl = resultUrl

/* A RECEIPT LISTS WHAT THE PROVIDER WAS SENT — computed from argv, never from a
   parallel list that can drift from it. Every value that follows a reference
   flag is a reference; nothing else is. */
let refFlags = ["--image", "--image-references", "--start-image", "--end-image", "--video-references"]
let refsOfArgs = (args: array<string>): array<string> =>
  Js.Array2.reducei(args, (acc, a, i) =>
    i > 0 && Js.Array2.includes(refFlags, Js.Array2.unsafe_get(args, i - 1)) ? Js.Array2.concat(acc, [a]) : acc
  , [])

/* THE ONLY PLACE A PROVIDER COMMAND IS ASSEMBLED. Callers give the references
   and the surrounding flags; the args and the receipt are both derived here from
   the same list, so they cannot describe different calls. */
let run = (~episode, ~id, ~kind, ~model, ~credits, ~prompt, ~refs: array<reference>, ~head, ~tail, ~forClip, ~dst, ~ext) => {
  Js.Array2.forEach(refs, r => ignore(requireFile(roleOf(r) ++ " reference", pathOf(r))))
  /* the model decides which reference leads */
  let refs = ordered(~model, refs)
  let args = Js.Array2.concatMany(head, [argsOfRefs(~forClip, refs), tail])
  Kuku_Spend.guard(~episode, ~shot=id, ~credits)
  let raw = execFileSync("higgsfield", args, opts)
  switch firstUrl(raw, ext) {
  | Some(url) =>
    switch try {
      let _ = execFileSync("curl", ["-fsSL", "--retry", "3", "--create-dirs", "-o", dst, url], opts)
      true
    } catch {
    | _ => false
    } {
    | true => {
        Kuku_Spend.record(~episode, ~shot=id, ~kind, ~model, ~credits, ())
        writeReceipt(~asset=dst, ~kind, ~id, ~prompt, ~refs, ~model, ~params=args, ~credits)
        Js.log("OK " ++ id)
        true
      }
    | false => {
        /* the provider charged for this result; the download is what failed */
        Kuku_Spend.record(~episode, ~shot=id, ~kind, ~model, ~credits, ~note="charged; download failed — asset unreceipted", ())
        Js.log("FAIL " ++ id ++ " — charged but download failed: " ++ url)
        false
      }
    }
  | None => {
      Js.log("FAIL " ++ id ++ " — " ++ Js.String2.slice(raw, ~from=0, ~to_=160))
      false
    }
  }
}

/* ---- stills ---------------------------------------------------------------- */
let still = (~episode="EP10", ~id, ~spec: P.imageSpec, ~dst, ()) => {
  let prompt = P.imagePrompt(spec) /* PromptGate inside */
  requireBoards(spec.subjects)
  switch spec.plate {
  | Some(p) => ignore(requireFile("backplate", p))
  | None => ()
  }
  /* the renderer decides the ORDER; the roles are recovered here so the receipt
     records what each attachment was for */
  let plateSet = switch spec.plate {
  | Some(p) => [p]
  | None => []
  }
  let refs = Js.Array2.map(P.imageRefs(spec), r =>
    r == P.styleKey()
      ? Style(r)
      : Js.Array2.includes(plateSet, r)
      ? Plate(r)
      : Js.Array2.includes(spec.objects, r)
      ? Object(r)
      : Board(r)
  )
  run(~episode, ~id, ~kind="still", ~model="nano_banana_pro",
    ~credits=Kuku_Spend.priceOf("nano_banana_pro"), ~prompt, ~refs, ~forClip=false,
    ~head=["generate", "create", "nano_banana_pro", "--prompt", prompt],
    ~tail=["--aspect_ratio", "16:9", "--resolution", "2k", "--wait", "--json"],
    ~dst, ~ext="(png|webp|jpg)")
}

/* ---- clips ----------------------------------------------------------------- */
/* The start frame is a premise like any other: it must exist AND be engine-
   receipted, so a clip can never again be built on a frame the bible has left
   behind. Character boards ride along as image references — the author's law
   that identity never depends on the start frame alone. Seedance takes at
   most 9 reference images counting start and end; cast boards fill the rest. */
/* `workflow` swaps the bare model for one of the platform's own pipelines —
   Cinema Studio exposes palette, light, lens and pacing as PARAMETERS rather
   than as sentences a model may ignore, which is the whole reason to try it. */
/* HOW MANY IMAGES THIS ENGINE ACCEPTS. The old 9 was Cinema Studio's ceiling
   promoted to a law; Seedance 2.5 states its own: at most 50 reference media,
   at most 30 images counting start and end. Read the model, do not assume. */
let imageSlots = engine =>
  switch engine {
  | "seedance_2_5" | "seedance_2_0" | "seedance_2_0_mini" => 30
  | _ => 9
  }

let clip = (~episode="EP10", ~id, ~spec: P.videoSpec, ~model, ~secs, ~start: startFrame, ~endFrame: option<endFrame>=?, ~videoRefs=[], ~setRefs=[], ~workflow="", ~generateAudio=false, ~dst, ()) => {
  let prompt = P.videoPrompt(spec) /* PromptGate inside */
  requireBoards(spec.cast)
  let startP = startPath(start)
  ignore(requireFile("start frame", startP))
  if !receiptIntact(startP) {
    refuse("STALE", "start frame " ++ startP,
      "its receipt is absent or its premises drifted — regenerate the frame through the engine first")
  }
  switch endFrame {
  | Some(e) => {
      let ep = endPath(e)
      ignore(requireFile("end frame", ep))
      if !receiptIntact(ep) {
        refuse("STALE", "end frame " ++ ep,
          "its receipt is absent or its premises drifted — regenerate the frame through the engine first")
      }
    }
  | None => ()
  }
  let boards = Js.Array2.reduce(spec.cast, (acc, sub) =>
    switch P.boardOf(sub) {
    | Some(b) => Js.Array2.includes(acc, b) ? acc : Js.Array2.concat(acc, [b])
    | None => acc
    }
  , [])
  let hasEnd = switch endFrame {
  | Some(_) => 1
  | None => 0
  }
  let slots = imageSlots(workflow == "" ? model : workflow) - 1 - Js.Array2.length(setRefs) - hasEnd
  if Js.Array2.length(boards) > slots {
    refuse("OVERFLOW",
      Belt.Int.toString(Js.Array2.length(boards)) ++ " cast sheets for " ++ Belt.Int.toString(slots) ++ " reference slots in " ++ id,
      "split the shot or reduce the cast — the law is every sheet attached, so dropping some silently is refused")
  }
  Js.Array2.forEach(videoRefs, v => ignore(requireFile("video reference", v)))
  let refs = Js.Array2.concatMany(
    [Start(start)],
    [
      switch endFrame {
      | Some(e) => [End(e)]
      | None => []
      },
      Js.Array2.map(setRefs, r => Plate(r)),
      Js.Array2.map(boards, b => Board(b)),
      Js.Array2.map(videoRefs, v => Video(v)),
    ],
  )
  let credits = Kuku_Spend.priceOf(workflow == "" ? model : workflow) *. Belt.Int.toFloat(secs) /. 5.0
  let engineName = workflow == "" ? model : workflow
  run(~episode, ~id, ~kind="clip", ~model=engineName, ~credits, ~prompt, ~refs, ~forClip=true,
    /* every clip carries a start frame, so the mode is always omni_reference:
       t2v refuses reference media outright, and omni_reference refuses to run
       without any — the two constraints leave exactly one lawful mode. */
    ~head=Js.Array2.concat(
      ["generate", "create", engineName, "--prompt", prompt],
      /* Seedance 2.0 Mini states no mode parameter and takes reference media
         directly; passing one to an engine that does not declare it is a 422. */
      engineName == "seedance_2_0_mini" ? [] : ["--mode", "omni_reference"],
    ),
    /* GENERATED SPEECH IS THE DUB MARKER. The runbook paid three wrong passes
       for guessing where a model animated a mouth; its own generated voice is
       the only record of that, so a shot that will be dubbed asks for audio. */
    ~tail=Js.Array2.concat(
      ["--generate_audio", generateAudio ? "true" : "false", "--duration", Belt.Int.toString(secs)],
      ["--resolution", "720p", "--bitrate_mode", "high", "--aspect_ratio", "16:9", "--wait", "--json"],
    ),
    ~dst, ~ext="(mp4|webm|mov)")
}

/* ---- edits ----------------------------------------------------------------- */
/* An edit inherits its source's authority, so the source must itself be
   engine-receipted. */
let edit = (~episode="EP10", ~id, ~spec: P.editSpec, ~src, ~dst, ()) => {
  let prompt = P.editPrompt(spec)
  ignore(requireFile("source image", src))
  if !receiptIntact(src) {
    refuse("STALE", "edit source " ++ src,
      "an edit inherits its source's authority — regenerate the source through the engine first")
  }
  run(~episode, ~id, ~kind="edit", ~model="nano_banana_pro",
    ~credits=Kuku_Spend.priceOf("nano_banana_pro"), ~prompt, ~refs=[Object(src)], ~forClip=false,
    ~head=["generate", "create", "nano_banana_pro", "--prompt", prompt],
    ~tail=["--aspect_ratio", "16:9", "--resolution", "2k", "--wait", "--json"],
    ~dst, ~ext="(png|webp|jpg)")
}

/* ---- plates ---------------------------------------------------------------- */
let plate = (~episode="EP10", ~id, ~prompt, ~refs: array<string>, ~dst, ~aspect="16:9", ()) => {
  let gated = PromptGate.passStrict(~which="plate " ++ id, prompt)
  let typed = Js.Array2.mapi(refs, (r, i) => i == 0 ? Style(r) : Plate(r))
  run(~episode, ~id, ~kind="plate", ~model="nano_banana_pro",
    ~credits=Kuku_Spend.priceOf("nano_banana_pro"), ~prompt=gated, ~refs=typed, ~forClip=false,
    ~head=["generate", "create", "nano_banana_pro", "--prompt", gated],
    ~tail=["--aspect_ratio", aspect, "--resolution", "2k", "--wait", "--json"],
    ~dst, ~ext="(png|webp|jpg)")
}

/* A LOCAL DETERMINISTIC TRANSFORM (the ga composite) may change an asset's
   pixels lawfully. It calls stamp() to update the recorded asset hash and
   append what it did, keeping the receipt intact without a provider call. */
let stamp = (~asset, ~note) =>
  if existsSync(receiptPath(asset)) {
    switch Js.Json.decodeObject(Js.Json.parseExn(readFileSync(receiptPath(asset), "utf8"))) {
    | Some(o) => {
        Js.Dict.set(o, "assetSha256", Js.Json.string(sha256File(asset)))
        /* a self-edit records the asset's pre-edit hash as its own reference;
           a later lawful transform must refresh that self-reference row too */
        switch o->Js.Dict.get("refs")->Belt.Option.flatMap(Js.Json.decodeArray) {
        | Some(rows) => {
            let healed = Js.Array2.map(rows, row =>
              switch Js.Json.decodeObject(row) {
              | Some(r) =>
                switch r->Js.Dict.get("path")->Belt.Option.flatMap(Js.Json.decodeString) {
                | Some(pth) if pth == asset => {
                    Js.Dict.set(r, "sha256", Js.Json.string(sha256File(asset)))
                    Js.Json.object_(r)
                  }
                | _ => row
                }
              | None => row
              }
            )
            Js.Dict.set(o, "refs", Js.Json.array(healed))
          }
        | None => ()
        }
        let prior = switch o->Js.Dict.get("localTransforms")->Belt.Option.flatMap(Js.Json.decodeArray) {
        | Some(a) => a
        | None => []
        }
        Js.Dict.set(o, "localTransforms", Js.Json.array(Js.Array2.concat(prior, [Js.Json.string(note)])))
        writeFileSync(receiptPath(asset), Js.Json.stringifyWithSpace(Js.Json.object_(o), 1) ++ "\n")
      }
    | None => ()
    }
  }
