// Generated by ReScript, PLEASE EDIT WITH CARE


function lighting(b) {
  switch (b) {
    case "RingDrill" :
    case "Briefing" :
    case "RopeSlips" :
        return "warm golden dusk — the last golden evening; the low sun gilds the paper flagstones";
    case "Runaway" :
    case "Braking" :
        return "deepening golden dusk, long warm shadows running down the lane";
    case "Forging" :
        return "deep dusk — the golden breath-light is the light source of the frame";
    case "AfterStop" :
        return "soft warm afterglow just after sundown";
    case "DoorwayNight" :
        return "cool blue evening; the doorway's golden glow is the only warmth in frame";
    case "TowerMischief" :
    case "TowerEnd" :
        return "cool fading dusk at the tower, blue-grey light on the stone";
    default:
      return "the very last of the gold — the sun nearly down, warm light low and grazing";
  }
}

function dragonForm(b) {
  switch (b) {
    case "AfterStop" :
    case "DoorwayNight" :
    case "TowerEnd" :
        return "Small";
    default:
      return "Great";
  }
}

function gauriAboard(b) {
  switch (b) {
    case "RingDrill" :
    case "AfterStop" :
    case "DoorwayNight" :
    case "TowerEnd" :
        return false;
    default:
      return true;
  }
}

function gaExists(b) {
  switch (b) {
    case "Forging" :
    case "LastApproach" :
    case "TheStop" :
    case "AfterStop" :
    case "DoorwayNight" :
    case "TowerEnd" :
        return true;
    default:
      return false;
  }
}

function bellWithCheel(b) {
  switch (b) {
    case "RingDrill" :
    case "Briefing" :
    case "TowerMischief" :
        return false;
    default:
      return true;
  }
}

export {
  lighting ,
  dragonForm ,
  gauriAboard ,
  gaExists ,
  bellWithCheel ,
}
/* No side effect */
