// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

var laneLandmarks = [
  {
    name: "STONE POST",
    x: -4.6,
    y: 0.0,
    z: 9.0,
    note: "the rope tie-point at the top of the slope, on the LEFT kerb"
  },
  {
    name: "CART START",
    x: 0.0,
    y: 2.0,
    z: 9.0 * 0.97,
    note: "where the tethered cart stands"
  },
  {
    name: "MARKER 1",
    x: 0.0,
    y: 12.0,
    z: 9.0 * 0.75,
    note: "first distance mark: a broad red band PAINTED flat across the lane's paving — colour on the road surface itself, part of the flagstones, smooth under any wheel"
  },
  {
    name: "MARKER 2",
    x: 0.0,
    y: 24.0,
    z: 9.0 * 0.5,
    note: "second distance mark: a broad red band PAINTED flat across the lane's paving — colour on the road surface itself, part of the flagstones, smooth under any wheel"
  },
  {
    name: "MARKER 3",
    x: 0.0,
    y: 36.0,
    z: 9.0 * 0.25,
    note: "third and last distance mark: a broad red band PAINTED flat across the lane's paving — colour on the road surface itself, part of the flagstones, smooth under any wheel"
  },
  {
    name: "FLAT BEGINS",
    x: 0.0,
    y: 48.0,
    z: 0.0,
    note: "the slope ends; the last 12 m is level"
  },
  {
    name: "GA-STONE",
    x: 0.0,
    y: 55.0,
    z: 0.0,
    note: "the flat stone where the golden ga-shape is forged"
  },
  {
    name: "END WALL",
    x: 0.0,
    y: 60.0,
    z: 0.0,
    note: "closed paper stone wall across the full width, its face plain bare stone from kerb to kerb — the lane is a dead end"
  }
];

var courtyardLandmarks = [
  {
    name: "FLIGHT RING",
    x: 0.0,
    y: -18.0,
    z: 9.0,
    note: "a COMPLETE CIRCLE of stone standing upright on its edge, built of layered paper arcs and UNBROKEN ALL THE WAY ROUND, its lowest point meeting the courtyard flagstones — FOURTEEN METRES across, wide enough for an enormous dragon to fly through with wings spread, a full closed circle. A SHORT BRONZE HOOK is fixed to the inside of its crown, reaching down into the ring's opening"
  },
  {
    name: "LAUNCH CIRCLE",
    x: 0.0,
    y: -12.0,
    z: 9.0,
    note: "where a dragon stands to begin her flight: a circle of plain flagstones laid in rings, every stone BLANK and uncarved, plain smooth paper faces"
  },
  {
    name: "TEMPLE GATEWAY",
    x: 0.0,
    y: -30.0,
    z: 9.0,
    note: "far behind the ring, the paper temple gateway"
  },
  {
    name: "TOWER",
    x: 16.0,
    y: -26.0,
    z: 9.0 + 14.0,
    note: "चील's closed stone tower, off to the RIGHT and high"
  },
  {
    name: "LANE HEAD",
    x: 0.0,
    y: 0.0,
    z: 9.0,
    note: "the courtyard's edge, where the lane begins"
  }
];

function landmarksOf(s) {
  switch (s) {
    case "Courtyard" :
        return courtyardLandmarks;
    case "Lane" :
        return laneLandmarks;
    case "FlatStone" :
        return laneLandmarks.filter(function (l) {
                    return l.y >= 44.0;
                  });
    case "Tower" :
        return [
                {
                  name: "PARAPET",
                  x: 16.0,
                  y: -26.0,
                  z: 9.0 + 14.0,
                  note: "where चील perches, looking DOWN-LEFT at the courtyard"
                },
                {
                  name: "TOWER DOOR",
                  x: 16.0,
                  y: -24.0,
                  z: 9.0 + 10.0,
                  note: "tall closed stone door in the tower face"
                }
              ];
    case "Doorway" :
        return [
                {
                  name: "THE DOORWAY",
                  x: 0.0,
                  y: 0.0,
                  z: 0.0,
                  note: "the golden arch standing free between the worlds"
                },
                {
                  name: "VILLAGE BEYOND",
                  x: 0.0,
                  y: 4.0,
                  z: 0.0,
                  note: "seen THROUGH the arch: दादी's village courtyard"
                }
              ];
    case "GrassVerge" :
        return [
                {
                  name: "GRASS PATCH",
                  x: -9.0,
                  y: 6.0,
                  z: 9.0 * 0.9,
                  note: "गौरी's grazing patch, LEFT of the lane head"
                },
                {
                  name: "LANE (BEYOND)",
                  x: 0.0,
                  y: 6.0,
                  z: 9.0 * 0.9,
                  note: "the lane visible past her"
                }
              ];
    
  }
}

function setName(s) {
  switch (s) {
    case "Courtyard" :
        return "courtyard";
    case "Lane" :
        return "lane";
    case "FlatStone" :
        return "flat_stone";
    case "Tower" :
        return "tower";
    case "Doorway" :
        return "doorway";
    case "GrassVerge" :
        return "grass_verge";
    
  }
}

function vantageName(v) {
  switch (v) {
    case "TopLookingDown" :
        return "top_looking_down";
    case "BottomLookingUp" :
        return "bottom_looking_up";
    case "Overhead" :
        return "overhead";
    case "GroundLevel" :
        return "ground_level";
    case "AtTheRing" :
        return "at_the_ring";
    
  }
}

function vantageProse(s, v) {
  switch (s) {
    case "Courtyard" :
        switch (v) {
          case "Overhead" :
              return "we look from high above the courtyard, down: the ring, the launch circle, and the head of the lane running away";
          case "AtTheRing" :
              return "we look from the courtyard flagstones, facing the great stone flight ring, the bronze bell hanging from the inside of the ring's crown, the temple gateway far behind the ring";
          default:
            return "we look from the courtyard flagstones at head height, the flight ring in view";
        }
    case "Lane" :
        switch (v) {
          case "TopLookingDown" :
              return "we look from the stone post at the TOP of the lane, at head height, looking straight DOWN the slope: the three red markers recede away from us along the centreline, the flat stretch and the closed stone wall are visible far below";
          case "BottomLookingUp" :
              return "we look from the flat stretch at the BOTTOM of the lane, at head height, looking back UP the slope: the markers climb away from us, the stone post and the courtyard edge at the top of frame";
          case "Overhead" :
              return "we look from high above the lane, straight DOWN: the lane runs top-to-bottom through the frame, the three red markers evenly spaced on its centreline, the closed wall across the bottom";
          case "GroundLevel" :
          case "AtTheRing" :
              return "we look from beside the lane at head height, the slope running left to right across frame, the markers on its centreline";
          
        }
    case "FlatStone" :
        if (v === "BottomLookingUp") {
          return "we look from low on the flat stretch, back up the lane, the closed stone wall behind us";
        } else {
          return "we look from low and close on the flat stone at the end of the lane, the closed stone wall behind it";
        }
    case "Tower" :
        return "we look up at the tower parapet from below and to the left, the courtyard far beneath";
    case "Doorway" :
        return "we face the standing golden arch square-on, the village courtyard visible through it";
    case "GrassVerge" :
        return "we look from the grass verge at head height, the lane beyond";
    
  }
}

function setProseFor(s, names) {
  var chosen = landmarksOf(s).filter(function (l) {
        return names.includes(l.name);
      });
  var lm = chosen.map(function (l) {
          return l.name + " (" + l.note + ")";
        }).join("; ");
  switch (s) {
    case "Courtyard" :
        return "THE FLIGHT COURTYARD — an open paper-flagstone courtyard at the top of the lane. In this shot: " + lm;
    case "Lane" :
        return "THE LANE — the gurukul's straight downhill flight-courtyard slope of paper flagstones with low paper kerbs both sides. In this shot: " + lm;
    case "FlatStone" :
        return "THE FLAT STONE — the level last stretch at the bottom of the lane. In this shot: " + lm;
    case "Tower" :
        return "THE TOWER — चील's closed paper stone tower. In this shot: " + lm;
    case "Doorway" :
        return "THE THRESHOLD — the golden paper doorway between the worlds. In this shot: " + lm;
    case "GrassVerge" :
        return "THE GRASS VERGE — the paper-grass patch beside the head of the lane. In this shot: " + lm;
    
  }
}

function setProse(s) {
  var lm = landmarksOf(s).map(function (l) {
          return l.name + " (" + l.note + ")";
        }).join("; ");
  switch (s) {
    case "Courtyard" :
        return "THE FLIGHT COURTYARD — an open paper-flagstone courtyard at the top of the lane. Fixed landmarks, always in these places: " + lm;
    case "Lane" :
        return "THE LANE — the gurukul's straight downhill flight-courtyard slope of paper flagstones, " + String(60.0) + " m long and " + String(8.0) + " m wide, falling " + String(9.0) + " m from top to bottom, with low paper kerbs on both sides. Fixed landmarks, always in these places: " + lm;
    case "FlatStone" :
        return "THE FLAT STONE — the level last stretch at the bottom of the lane. Fixed landmarks: " + lm;
    case "Tower" :
        return "THE TOWER — चील's closed paper stone tower above and right of the courtyard. Fixed landmarks: " + lm;
    case "Doorway" :
        return "THE THRESHOLD — the golden paper doorway standing between the dragon world and the village. Fixed landmarks: " + lm;
    case "GrassVerge" :
        return "THE GRASS VERGE — the paper-grass patch beside the head of the lane. Fixed landmarks: " + lm;
    
  }
}

function f(prim) {
  return String(prim);
}

function blueprint(s) {
  var lms = landmarksOf(s);
  var hasLane = s === "Lane" || s === "Courtyard" || s === "FlatStone";
  var ys = lms.map(function (l) {
        return l.y;
      });
  var minY = Caml_splice_call.spliceApply(Math.min, [ys.concat(hasLane ? [0.0] : [])]);
  var maxY = Caml_splice_call.spliceApply(Math.max, [ys.concat(hasLane ? [60.0] : [])]);
  var zs = lms.map(function (l) {
        return l.z;
      });
  var maxZ = Caml_splice_call.spliceApply(Math.max, [zs.concat([1.0])]);
  var span = maxY - minY;
  var scale = Math.min(17.0, 980.0 / Math.max(span, 1.0));
  var h = 132.0 + span * scale + 90.0;
  var py = function (y) {
    return 132.0 + (y - minY) * scale;
  };
  var px = function (x) {
    return 250.0 + x * scale;
  };
  var ez = function (z) {
    return 900.0 + z * 9.0;
  };
  var laneBody = hasLane ? "<rect x='" + String(px(- 8.0 / 2.0)) + "' y='" + String(132.0 + (0.0 - minY) * scale) + "' width='" + String(8.0 * scale) + "' height='" + String(60.0 * scale) + "' fill='#e9e1d0' stroke='#8a7f68' stroke-width='2'/><line x1='" + String(250.0 + 0.0 * scale) + "' y1='" + String(132.0 + (0.0 - minY) * scale) + "' x2='" + String(250.0 + 0.0 * scale) + "' y2='" + String(py(60.0)) + "' stroke='#b9ad93' stroke-width='1' stroke-dasharray='7 7'/><rect x='" + String(px(- 8.0 / 2.0) - 6.0) + "' y='" + String(py(60.0)) + "' width='" + String(8.0 * scale + 12.0) + "' height='10' fill='#6d6151'/>" : "";
  var elevPath;
  if (hasLane) {
    var pts = lms.slice().sort(function (a, b) {
              if (a.y < b.y) {
                return -1;
              } else {
                return 1;
              }
            }).map(function (l) {
            return String(ez(l.z)) + "," + String(py(l.y));
          }).join(" ");
    elevPath = "<polyline points='" + pts + "' fill='none' stroke='#8a7f68' stroke-width='2.5'/>";
  } else {
    elevPath = "";
  }
  var rows = lms.map(function (l, i) {
          var cy = py(l.y);
          var cx = px(l.x);
          var isMarker = l.name.startsWith("MARKER");
          var colour = isMarker ? "#c0392b" : "#b9ad93";
          var labelY = cy + (
            i % 2 === 0 ? -1.0 : 13.0
          );
          return "<circle cx='" + String(cx) + "' cy='" + String(cy) + "' r='" + (
                  isMarker ? "8" : "6"
                ) + "' fill='" + colour + "'/>" + (
                  hasLane ? "<circle cx='" + String(ez(l.z)) + "' cy='" + String(cy) + "' r='4' fill='" + colour + "'/>" : ""
                ) + "<line x1='" + String(cx + 10.0) + "' y1='" + String(cy) + "' x2='" + String(470.0 - 8.0) + "' y2='" + String(labelY - 4.0) + "' stroke='#cfc6b2' stroke-width='1'/><text x='" + String(470.0) + "' y='" + String(labelY) + "' font-family='Helvetica' font-size='15' font-weight='bold' fill='#2c3e50'>" + l.name + "</text><text x='" + String(470.0) + "' y='" + String(labelY + 15.0) + "' font-family='Helvetica' font-size='11.5' fill='#7f8c8d'>" + String(l.y) + " m along · " + String(l.z) + " m up · " + l.note + "</text>";
        }).join("");
  return "<svg xmlns='http://www.w3.org/2000/svg' width='" + String(1240.0) + "' height='" + String(h) + "' viewBox='0 0 " + String(1240.0) + " " + String(h) + "'><rect width='100%' height='100%' fill='#fbf8f1'/><text x='40' y='54' font-family='Helvetica' font-size='25' font-weight='bold' fill='#2c3e50'>EP10 SET BLUEPRINT — " + setName(s).toUpperCase() + "</text><text x='40' y='80' font-family='Helvetica' font-size='13.5' fill='#7f8c8d'>metres. LEFT: plan, looking straight down; the lane runs down the page away from the courtyard." + (
          hasLane ? "  RIGHT: elevation, looking from the side; the line is the ground falling " + String(maxZ) + " m." : ""
        ) + "</text><text x='" + String(250.0 - 46.0) + "' y='" + String(132.0 - 16.0) + "' font-family='Helvetica' font-size='12' font-weight='bold' fill='#8a7f68'>PLAN</text>" + (
          hasLane ? "<text x='" + String(900.0 - 20.0) + "' y='" + String(132.0 - 16.0) + "' font-family='Helvetica' font-size='12' font-weight='bold' fill='#8a7f68'>ELEVATION</text><line x1='" + String(900.0) + "' y1='" + String(132.0 - 8.0) + "' x2='" + String(900.0) + "' y2='" + String(h - 70.0) + "' stroke='#e0d8c6' stroke-width='1'/>" : ""
        ) + laneBody + elevPath + rows + "</svg>";
}

var plateDir = "../stories/kuku/ep10prod/sets/";

function platePath(s, tag) {
  return plateDir + setName(s) + "_" + tag + "_plate.png";
}

function masterPlate(s) {
  return plateDir + setName(s) + "_plate.png";
}

function lanePlateAt(y) {
  if (y < 30.0) {
    return platePath("Lane", "top_looking_down");
  } else {
    return platePath("Lane", "flat_approach");
  }
}

var markerPositions = [
  12.0,
  24.0,
  36.0
];

var greatFormStaging = "ORIENTATION IN THE LANE: this dragon is far longer than she is wide, and the lane is " + String(8.0) + " metres between its kerbs. She lies ALONG the lane: her long axis runs parallel to it, nose forward in the direction of travel, body and tail trailing back up the slope behind her, her whole length inside the lane. Her wings are swept back along her body or held HIGH above the kerb line. Every part of her — body, tail, wings and limbs — stays between the kerbs, in open air, clear of kerb and wall.";

function lanePosition(at, cartAt) {
  var behind = markerPositions.filter(function (m) {
        return m < at;
      }).length;
  var ahead = markerPositions.length - behind | 0;
  var toWall = 60.0 - at;
  var base = "POSITION ON THE LANE: this shot happens " + String(at) + " metres down the " + String(60.0) + " metre lane. Of the three red markers, " + String(behind) + " are already BEHIND this point and " + String(ahead) + " still lie AHEAD down the slope. The closed end wall is " + String(toWall) + " metres further on and reads exactly that far away.";
  if (cartAt !== undefined) {
    return base + " THE CART is " + String(cartAt) + " metres down the lane at this moment — " + String(60.0 - cartAt) + " metres from the wall — and is still running.";
  } else {
    return base;
  }
}

var laneLength = 60.0;

var laneWidth = 8.0;

var laneDrop = 9.0;

var greatFormFraming = "FRAMING FOR AN ENORMOUS DRAGON: play this WIDE. The viewpoint stands far enough back that the whole width of the lane, both kerbs and a good band of sky sit in frame, with clear space above and behind the dragon, his whole body inside the picture with open air around it. When he shares the shot with the cart, the two sit SEPARATED across the frame — dragon to one side, cart to the other, each whole and distinct.";

var bellOnRing = "THE BRONZE BELL hangs inside the ring's crown, fastened by its bronze binding to the short hook there, down into the opening — SMALL, about ONE METRE tall, a hand-bell against the fourteen-metre ring, light enough for an eagle to lift away in her talons";

var hookBare = "THE HOOK INSIDE THE RING'S CROWN HANGS BARE — a short bronze hook over empty air, swinging gently, the space beneath it open sky. The ring carries only itself";

export {
  laneLength ,
  laneWidth ,
  laneDrop ,
  laneLandmarks ,
  courtyardLandmarks ,
  landmarksOf ,
  setName ,
  vantageName ,
  vantageProse ,
  setProseFor ,
  setProse ,
  f ,
  blueprint ,
  plateDir ,
  platePath ,
  masterPlate ,
  lanePlateAt ,
  markerPositions ,
  greatFormFraming ,
  bellOnRing ,
  hookBare ,
  greatFormStaging ,
  lanePosition ,
}
/* greatFormStaging Not a pure module */
