// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Kuku_Spend from "./Kuku_Spend.res.mjs";
import * as PromptGate from "./PromptGate.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Kuku_Ep10Sets from "./Kuku_Ep10Sets.res.mjs";
import * as Child_process from "child_process";
import * as Kuku_PromptSpec from "./Kuku_PromptSpec.res.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var opts = {
  encoding: "utf8",
  timeout: 900000
};

var dir = Kuku_PromptSpec.kukuRoot + "ep10prod/sets/";

Fs.mkdirSync(dir, {
      recursive: true
    });

var sets = [
  "Lane",
  "Courtyard",
  "FlatStone",
  "Tower",
  "Doorway",
  "GrassVerge"
];

function setOfName(n) {
  return Caml_option.undefined_to_opt(sets.find(function (s) {
                  return Kuku_Ep10Sets.setName(s) === n;
                }));
}

function platePrompt(s) {
  return PromptGate.pass("platePrompt", [
                "SHOT: WIDE ESTABLISHING PLATE, LANDSCAPE 16:9, full-bleed, the camera is INSIDE the world.",
                "STYLE: " + Kuku_PromptSpec.styleLaw + ". The FIRST attached image is the art style; match it EXACTLY.",
                "PALETTE: " + Kuku_PromptSpec.paletteLaw + ".",
                "BLUEPRINT: the SECOND attached image is a PLAN-VIEW MAP of this set — read the landmark positions from it, then draw the PLACE ITSELF seen from inside the world. Every landmark stands blank and plain: the markers are flat red paving stones, the post is a bare stone post, every face of stone smooth and empty.",
                "TIME: this is the set BEFORE the story happens — every flagstone bare, the flat stone bare, the lane open and empty from top to wall.",
                "SET: " + Kuku_Ep10Sets.setProse(s),
                "VIEWPOINT: " + Kuku_Ep10Sets.vantageProse(s, "TopLookingDown"),
                "LIGHTING: warm golden dusk — the last golden evening; the low sun gilds the paper flagstones. THE SUN STANDS OFF TO ONE SIDE, well clear of the viewing axis, so every landmark is LIT full-face and every colour in the place stays full — green hills, blue water, snow on the far peaks.",
                "PURPOSE: this is a SET PLATE — the empty location itself, to be reused as the reference for every shot staged here. Every landmark must be clearly visible and correctly placed.",
                "HARD RULES:\n" + Kuku_PromptSpec.bullets([
                        "the set stands EMPTY and still: bare flagstones, open sky, architecture and landscape alone — the whole cast of this picture is the place itself",
                        "the picture is the finished place seen from inside the world, rendered edge to edge, with open air between the viewer and every landmark"
                      ].concat(Kuku_PromptSpec.worldFacts))
              ].join("\n"));
}

function plateFile(s) {
  return dir + Kuku_Ep10Sets.setName(s) + "_plate.png";
}

function blueprintSvg(s) {
  return dir + Kuku_Ep10Sets.setName(s) + "_blueprint.svg";
}

function blueprintPng(s) {
  return dir + Kuku_Ep10Sets.setName(s) + "_blueprint.png";
}

function surveyFile(s) {
  return dir + Kuku_Ep10Sets.setName(s) + "_survey.mp4";
}

function firstUrl(raw, ext) {
  var m = raw.match(new RegExp("https://[^\"\\s]*\\." + ext));
  if (m !== null) {
    return Caml_array.get(m, 0);
  }
  
}

function fetchTo(url, dst) {
  Child_process.execFileSync("curl", [
        "-sL",
        "--retry",
        "3",
        "--create-dirs",
        "-o",
        dst,
        url
      ], opts);
  console.log("saved " + dst);
}

function doBlueprints() {
  sets.forEach(function (s) {
        Fs.writeFileSync(blueprintSvg(s), Kuku_Ep10Sets.blueprint(s));
        console.log("blueprint " + Kuku_Ep10Sets.setName(s));
      });
}

function doPlate(s) {
  var bp = blueprintPng(s);
  var refs = Fs.existsSync(bp) ? [
      Kuku_PromptSpec.styleKey,
      bp
    ] : [Kuku_PromptSpec.styleKey];
  if (!Fs.existsSync(bp)) {
    console.log("NOTE: no blueprint PNG for " + Kuku_Ep10Sets.setName(s) + " — generating from prose alone");
  }
  var args = [
        "generate",
        "create",
        "nano_banana_pro",
        "--prompt",
        platePrompt(s)
      ].concat(refs.reduce((function (acc, r) {
                return acc.concat([
                            "--image",
                            r
                          ]);
              }), [])).concat([
        "--aspect_ratio",
        "16:9",
        "--resolution",
        "2k",
        "--wait",
        "--json"
      ]);
  Kuku_Spend.guard("EP10", Kuku_Ep10Sets.setName(s) + "_plate", Kuku_Spend.priceOf("nano_banana_pro"));
  var raw = Child_process.execFileSync("higgsfield", args, opts);
  var url = firstUrl(raw, "(png|webp|jpg)");
  if (url !== undefined) {
    fetchTo(url, plateFile(s));
    return Kuku_Spend.record("EP10", Kuku_Ep10Sets.setName(s) + "_plate", "plate", "nano_banana_pro", Kuku_Spend.priceOf("nano_banana_pro"), "set plate", undefined);
  } else {
    console.log("FAIL plate " + Kuku_Ep10Sets.setName(s) + " — " + raw.slice(0, 160));
    return ;
  }
}

function surveySpec(s) {
  return {
          scene: "A slow survey of an EMPTY papercraft set, the place itself the whole subject. " + Kuku_Ep10Sets.setProse(s),
          cameraTravels: true,
          cast: [],
          blocking: [
            "the start image IS this set; every landmark stays exactly where the start image puts it",
            "the set holds perfectly still — a still world, the camera the only thing that travels"
          ],
          beats: [
            "0.0-1.0s: the camera is still, at the stone post at the top of the lane",
            "1.0-4.0s: it travels slowly forward down the centreline, its whole travel about EIGHTEEN METRES — coming to rest roughly level with the second red marker",
            "4.0-5.0s: it comes to rest. The closed stone wall is still far away in the distance at the end of the clip, exactly as far as eighteen metres of travel would leave it"
          ],
          camera: "one single short forward dolly of about eighteen metres down the lane centreline at head height, then a full stop, the end wall still far away at the finish",
          physics: [
            "the place itself is the complete cast — bare ground and standing architecture from first frame to last",
            "the set is RIGID: the end wall, the stone post, the kerbs and every red marker keep their exact positions in the world for the whole clip",
            "the end wall grows slowly and steadily nearer as the camera advances, and the lane keeps its exact length from first frame to last",
            "each red marker passes out of frame behind the camera exactly once, and exactly three markers exist in the whole lane"
          ],
          lighting: "constant warm golden dusk, identical to the start image throughout, the light holding steady for the whole clip",
          audio: "",
          extraRules: ["the set stays EMPTY for the whole clip: bare flagstones, open sky, the place itself the only subject"]
        };
}

function doSurvey(s) {
  var plate = plateFile(s);
  if (Fs.existsSync(plate)) {
    var args = [
      "generate",
      "create",
      "seedance_2_0_mini",
      "--prompt",
      Kuku_PromptSpec.videoPrompt(surveySpec(s)),
      "--start-image",
      plate,
      "--duration",
      "5",
      "--wait",
      "--json"
    ];
    var raw = Child_process.execFileSync("higgsfield", args, opts);
    var url = firstUrl(raw, "(mp4|webm|mov)");
    if (url !== undefined) {
      return fetchTo(url, surveyFile(s));
    } else {
      console.log("FAIL survey " + Kuku_Ep10Sets.setName(s) + " — " + raw.slice(0, 160));
      return ;
    }
  }
  console.log("no approved plate for " + Kuku_Ep10Sets.setName(s) + " — run `plate` first");
}

function doRetouch(s, change) {
  var plate = plateFile(s);
  if (Fs.existsSync(plate)) {
    var bak = dir + Kuku_Ep10Sets.setName(s) + "_plate_PRE_RETOUCH.png";
    if (!Fs.existsSync(bak)) {
      Child_process.execFileSync("cp", [
            plate,
            bak
          ], opts);
    }
    var spec_keep = [
      "the exact geography: the post at the top LEFT, the three red markers evenly spaced on the centreline, the flat stretch, the closed stone wall across the far end",
      "the same camera, the same perspective, the same golden dusk light"
    ];
    var spec_extraRules = ["the set stays EMPTY: no dragons, birds, animals, cow, cart or figures"];
    var spec = {
      change: change,
      keep: spec_keep,
      extraRules: spec_extraRules
    };
    var raw = Child_process.execFileSync("higgsfield", [
          "generate",
          "create",
          "nano_banana_pro",
          "--prompt",
          Kuku_PromptSpec.editPrompt(spec),
          "--image",
          plate,
          "--aspect_ratio",
          "16:9",
          "--resolution",
          "2k",
          "--wait",
          "--json"
        ], opts);
    var url = firstUrl(raw, "(png|webp|jpg)");
    if (url !== undefined) {
      return fetchTo(url, plate);
    } else {
      console.log("FAIL retouch — " + raw.slice(0, 160));
      return ;
    }
  }
  console.log("no plate for " + Kuku_Ep10Sets.setName(s));
}

function stylePassPrompt(s) {
  return PromptGate.pass("stylePassPrompt", [
                "TASK: the SECOND attached image is an untextured grey 3D BLOCKOUT of this set — the geometry and camera are already correct. Render that exact view as the finished illustration.",
                "STYLE: " + Kuku_PromptSpec.styleLaw + ". The FIRST attached image is the art style; match it EXACTLY.",
                "PALETTE: " + Kuku_PromptSpec.paletteLaw + ".",
                "KEEP FROM THE BLOCKOUT, EXACTLY: the viewpoint, the perspective, the horizon line, the shape and fall of the ground, and the position and size of every object in frame, all held exactly where the blockout puts them.",
                "THE BLOCKOUT IS THE AUTHORITY ON WHAT IS IN FRAME: render exactly the forms it shows, the full list of them and only that list. The set description below covers the whole location; the blockout chooses which part of it this picture holds.",
                "SET: " + Kuku_Ep10Sets.setProse(s),
                "MATERIALS: flagstones become layered cut-paper slabs; kerbs become folded paper edges; the markers become blank red paper wedges; the wall becomes stacked paper stones; the ground becomes soft paper grass and hills.",
                "LIGHTING: warm golden dusk — the last golden evening, low grazing light and long soft shadows.",
                "HARD RULES:\n" + Kuku_PromptSpec.bullets([
                        "the set stands EMPTY and still: bare ground, open sky, architecture and landscape alone",
                        "every surface is finished paper, textured corner to corner"
                      ].concat(Kuku_PromptSpec.worldFacts))
              ].join("\n"));
}

function doStylePass(s, blockout, dst) {
  var args = [
    "generate",
    "create",
    "nano_banana_pro",
    "--prompt",
    stylePassPrompt(s),
    "--image",
    Kuku_PromptSpec.styleKey,
    "--image",
    blockout,
    "--aspect_ratio",
    "16:9",
    "--resolution",
    "2k",
    "--wait",
    "--json"
  ];
  var raw = Child_process.execFileSync("higgsfield", args, opts);
  var url = firstUrl(raw, "(png|webp|jpg)");
  if (url !== undefined) {
    return fetchTo(url, dst);
  } else {
    console.log("FAIL stylepass — " + raw.slice(0, 160));
    return ;
  }
}

var mode = process.argv.length > 2 ? Caml_array.get(process.argv, 2) : "blueprint";

var target = process.argv.length > 3 ? setOfName(Caml_array.get(process.argv, 3)) : undefined;

var exit = 0;

switch (mode) {
  case "blueprint" :
      doBlueprints();
      break;
  case "gate" :
      var bad = {
        contents: 0
      };
      var try_ = function (label, f) {
        try {
          f();
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            bad.contents = bad.contents + 1 | 0;
            console.log("== " + label + " ==");
            var m = err._1.message;
            console.log(m !== undefined ? m : "?");
            return ;
          }
          throw err;
        }
      };
      sets.forEach(function (s) {
            try_(Kuku_Ep10Sets.setName(s) + " plate", (function () {
                    return platePrompt(s);
                  }));
            try_(Kuku_Ep10Sets.setName(s) + " style", (function () {
                    return stylePassPrompt(s);
                  }));
            try_(Kuku_Ep10Sets.setName(s) + " survey", (function () {
                    return Kuku_PromptSpec.videoPrompt(surveySpec(s));
                  }));
          });
      if (bad.contents > 0) {
        Js_exn.raiseError(String(bad.contents) + " set prompts forbid");
      }
      console.log("PROMPT GATE CLEAN: plates, style passes and surveys for " + String(sets.length) + " sets");
      break;
  case "plate" :
      if (target !== undefined) {
        doPlate(target);
      } else {
        exit = 1;
      }
      break;
  case "prompt" :
      if (target !== undefined) {
        console.log(platePrompt(target));
      } else {
        exit = 1;
      }
      break;
  case "retouch" :
      if (target !== undefined) {
        doRetouch(target, process.argv.length > 4 ? Caml_array.get(process.argv, 4) : "Remove every letter, word and number from the picture: no carved or painted text on the stone post, none on any stone, and no numerals on the red markers — the markers become blank plain red paper wedges and the post a blank plain stone post. Also remove the pale upright stone slab standing on the flat stretch near the wall entirely, leaving clean empty flagstones there.");
      } else {
        exit = 1;
      }
      break;
  case "stylepass" :
      if (target !== undefined) {
        var tag = process.argv.length > 4 ? Caml_array.get(process.argv, 4) : "bottom_looking_up";
        doStylePass(target, dir + "blender/" + Kuku_Ep10Sets.setName(target) + "_" + tag + "_blockout.png", dir + Kuku_Ep10Sets.setName(target) + "_" + tag + "_plate.png");
      } else {
        exit = 1;
      }
      break;
  case "survey" :
      if (target !== undefined) {
        doSurvey(target);
      } else {
        exit = 1;
      }
      break;
  default:
    exit = 1;
}

if (exit === 1) {
  console.log("usage: node src/KukuEp10_SetBible.res.mjs <blueprint|plate|survey|prompt> <lane|courtyard|flat_stone|tower|doorway|grass_verge>  (got: " + mode + ")");
}

var S;

var P;

export {
  S ,
  P ,
  opts ,
  dir ,
  sets ,
  setOfName ,
  platePrompt ,
  plateFile ,
  blueprintSvg ,
  blueprintPng ,
  surveyFile ,
  firstUrl ,
  fetchTo ,
  doBlueprints ,
  doPlate ,
  surveySpec ,
  doSurvey ,
  doRetouch ,
  stylePassPrompt ,
  doStylePass ,
  mode ,
  target ,
}
/*  Not a pure module */
