/* Kuku_Engine.res — the ONE generation engine.

   Author's law (2026-08-28): every prompt is formatted and generated by the
   same engine; character references are always attached; the backplate exists
   before the shot; a new character's sheet exists before the character appears.
   This module is that law made structural. A driver supplies a typed spec and
   nothing else — the engine renders the prompt (through the PromptGate),
   assembles every reference, REFUSES on any missing premise, guards the budget
   before the provider call, books spend only on success, and writes a receipt
   beside every asset it produces.

   The receipt (<asset>.gen.json) is the point. It records the engine version,
   the prompt, the model and params, and the sha256 of every reference the
   asset was generated from. "Was this generated by the engine, from current
   premises?" stops being a claim and becomes a file: an asset whose receipt
   is missing, or whose reference hashes have drifted from what is on disk
   today, is mechanically stale — which is how a regeneration campaign knows
   exactly what it owes. The h13 incident (a clip generated against a frame
   the bible had left behind, caught only by looking) is the class this kills.

   Premise refusals name what to make first, in dependency order:
     PREMISE MISSING: plate — a shot's backplate is generated before the shot
     PREMISE MISSING: sheet — a character's board exists before the character
     PREMISE STALE:   receipt hash drift — regenerate the premise, then this */

module P = Kuku_PromptSpec

type execOpts = {"encoding": string, "timeout": int}
@module("child_process")
external execFileSync: (string, array<string>, execOpts) => string = "execFileSync"
@module("fs") external existsSync: string => bool = "existsSync"
@module("fs") external writeFileSync: (string, string) => unit = "writeFileSync"
@module("fs") external readFileSync: (string, string) => string = "readFileSync"
type buffer
@module("fs") external readFileBuf: string => buffer = "readFileSync"
type hash
@module("crypto") external createHash: string => hash = "createHash"
@send external hashUpdateBuffer: (hash, buffer) => hash = "update"
@send external hashUpdateText: (hash, string, string) => hash = "update"
@send external hashDigest: (hash, string) => string = "digest"
@scope("Date") @val external now: unit => float = "now"
@new external mkDate: float => Js.Date.t = "Date"

let version = "kuku-engine/1"
let opts = {"encoding": "utf8", "timeout": 1800000}

let sha256File = p => createHash("sha256")->hashUpdateBuffer(readFileBuf(p))->hashDigest("hex")

/* A reference may be a provider-side asset id (the style key) rather than a
   local file. Those are exempt from existence checks and hash as themselves. */
let isProviderAsset = r =>
  Js.Re.test_(Js.Re.fromString("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"), r)
let refHash = r => isProviderAsset(r) ? "PROVIDER_ASSET:" ++ r : existsSync(r) ? sha256File(r) : "ABSENT"
let sha256Text = t => createHash("sha256")->hashUpdateText(t, "utf8")->hashDigest("hex")

/* ---- refusals -------------------------------------------------------------- */
let refuse = (kind, what, remedy) =>
  Js.Exn.raiseError("PREMISE " ++ kind ++ ": " ++ what ++ " — " ++ remedy)

let requireFile = (label, p) =>
  isProviderAsset(p) || existsSync(p) ? p : refuse("MISSING", label ++ " " ++ p, "generate it first")

/* Every character in a spec must carry a sheet. This is where गौरी (no sheet)
   and small वैस्पर (no small sheet) stop being silent omissions and become
   named work items. Props are exempt: a prop is described, a character is
   referenced. */
let requireBoards = (subjects: array<P.subject>) =>
  Js.Array2.forEach(subjects, sub =>
    switch sub {
    | P.Prop(_) => ()
    | _ =>
      switch P.boardOf(sub) {
      | Some(b) => ignore(requireFile("character sheet", b))
      | None =>
        refuse(
          "MISSING",
          "character sheet for " ++
          switch sub {
          | P.Dragon({name}) => P.nameOf(name)
          | P.Gauri(_) => "GAURI"
          | P.RishiMuni(_) => "RISHI"
          | P.Dadi(_) => "DADI"
          | P.Cheel(_) => "CHEEL"
          | P.Prop(_) => "?"
          },
          "generate the sheet first, register it in boardOf, then rerun",
        )
      }
    }
  )

/* ---- receipts -------------------------------------------------------------- */
let receiptPath = asset => asset ++ ".gen.json"

let writeReceipt = (~asset, ~kind, ~id, ~prompt, ~refs: array<string>, ~model, ~params: array<string>, ~credits) => {
  let refRows = Js.Array2.map(refs, r =>
    Js.Json.object_(
      Js.Dict.fromArray([
        ("path", Js.Json.string(r)),
        ("sha256", Js.Json.string(refHash(r))),
      ]),
    )
  )
  let o = Js.Dict.fromArray([
    ("engine", Js.Json.string(version)),
    ("kind", Js.Json.string(kind)),
    ("id", Js.Json.string(id)),
    ("at", Js.Json.string(Js.Date.toISOString(mkDate(now())))),
    ("model", Js.Json.string(model)),
    ("credits", Js.Json.number(credits)),
    ("assetSha256", Js.Json.string(existsSync(asset) ? sha256File(asset) : "ABSENT")),
    ("promptSha256", Js.Json.string(sha256Text(prompt))),
    ("prompt", Js.Json.string(prompt)),
    ("params", Js.Json.stringArray(params)),
    ("refs", Js.Json.array(refRows)),
  ])
  writeFileSync(receiptPath(asset), Js.Json.stringifyWithSpace(Js.Json.object_(o), 1) ++ "\n")
}

/* An asset is CURRENT when its receipt exists, was written by this engine, and
   every reference it names still hashes to what is on disk. Anything else is
   stale — including everything generated before receipts existed, which is the
   honest verdict: nothing predating the engine can prove its premises. */
type freshness = Current | NoReceipt | RefDrift(string) | PromptDrift | AssetDrift

let freshness = (~asset, ~prompt) =>
  if !existsSync(receiptPath(asset)) {
    NoReceipt
  } else {
    switch Js.Json.decodeObject(Js.Json.parseExn(readFileSync(receiptPath(asset), "utf8"))) {
    | None => NoReceipt
    | Some(o) => {
        let str = k => o->Js.Dict.get(k)->Belt.Option.flatMap(Js.Json.decodeString)
        let drift = ref(None)
        switch o->Js.Dict.get("refs")->Belt.Option.flatMap(Js.Json.decodeArray) {
        | Some(rows) =>
          Js.Array2.forEach(rows, row =>
            switch Js.Json.decodeObject(row) {
            | Some(r) => {
                let p = r->Js.Dict.get("path")->Belt.Option.flatMap(Js.Json.decodeString)
                let h = r->Js.Dict.get("sha256")->Belt.Option.flatMap(Js.Json.decodeString)
                switch (p, h, drift.contents) {
                | (Some(p), Some(h), None) =>
                  if refHash(p) != h {
                    drift := Some(p)
                  }
                | _ => ()
                }
              }
            | None => ()
            }
          )
        | None => ()
        }
        switch drift.contents {
        | Some(p) => RefDrift(p)
        | None =>
          switch str("assetSha256") {
          | Some(h) if existsSync(asset) && sha256File(asset) != h => AssetDrift
          | _ => str("promptSha256") == Some(sha256Text(prompt)) ? Current : PromptDrift
          }
        }
      }
    }
  }

/* A premise asset is INTACT when its receipt exists, every reference it was
   generated from still hashes the same, and its own pixels are the ones the
   receipt recorded. This is the recursive staleness check: regenerate a plate
   and every frame generated from it goes non-intact, and every clip resting on
   those frames refuses until they are remade. */
let receiptIntact = asset =>
  if !existsSync(receiptPath(asset)) {
    false
  } else {
    switch Js.Json.decodeObject(Js.Json.parseExn(readFileSync(receiptPath(asset), "utf8"))) {
    | None => false
    | Some(o) => {
        let ok = ref(true)
        switch o->Js.Dict.get("refs")->Belt.Option.flatMap(Js.Json.decodeArray) {
        | Some(rows) =>
          Js.Array2.forEach(rows, row =>
            switch Js.Json.decodeObject(row) {
            | Some(r) =>
              switch (
                r->Js.Dict.get("path")->Belt.Option.flatMap(Js.Json.decodeString),
                r->Js.Dict.get("sha256")->Belt.Option.flatMap(Js.Json.decodeString),
              ) {
              | (Some(p), Some(h)) => if refHash(p) != h { ok := false }
              | _ => ()
              }
            | None => ()
            }
          )
        | None => ()
        }
        switch o->Js.Dict.get("assetSha256")->Belt.Option.flatMap(Js.Json.decodeString) {
        | Some(h) => if !existsSync(asset) || sha256File(asset) != h { ok := false }
        | None => ()
        }
        ok.contents
      }
    }
  }

/* ---- the one provider call ------------------------------------------------- */
let firstUrl = (raw, ext) =>
  switch Js.String2.match_(raw, Js.Re.fromString("https://[^\"\\s]*\\." ++ ext)) {
  | Some(m) => m[0]
  | None => None
  }

let run = (~episode, ~id, ~kind, ~model, ~credits, ~prompt, ~refs, ~args, ~dst, ~ext) => {
  Kuku_Spend.guard(~episode, ~shot=id, ~credits)
  let raw = execFileSync("higgsfield", args, opts)
  switch firstUrl(raw, ext) {
  | Some(url) =>
    switch try {
      let _ = execFileSync("curl", ["-fsSL", "--retry", "3", "--create-dirs", "-o", dst, url], opts)
      true
    } catch {
    | _ => false
    } {
    | true => {
        Kuku_Spend.record(~episode, ~shot=id, ~kind, ~model, ~credits, ())
        writeReceipt(~asset=dst, ~kind, ~id, ~prompt, ~refs, ~model, ~params=args, ~credits)
        Js.log("OK " ++ id)
        true
      }
    | false => {
        /* the provider charged for this result; the download is what failed */
        Kuku_Spend.record(~episode, ~shot=id, ~kind, ~model, ~credits, ~note="charged; download failed — asset unreceipted", ())
        Js.log("FAIL " ++ id ++ " — charged but download failed: " ++ url)
        false
      }
    }
  | None => {
      Js.log("FAIL " ++ id ++ " — " ++ Js.String2.slice(raw, ~from=0, ~to_=160))
      false
    }
  }
}

/* ---- stills ---------------------------------------------------------------- */
let still = (~episode="EP10", ~id, ~spec: P.imageSpec, ~dst, ()) => {
  let prompt = P.imagePrompt(spec) /* PromptGate inside */
  requireBoards(spec.subjects)
  switch spec.plate {
  | Some(p) => ignore(requireFile("backplate", p))
  | None => ()
  }
  let refs = P.imageRefs(spec)
  Js.Array2.forEach(refs, r => ignore(requireFile("reference", r)))
  let args = Js.Array2.concat(
    Js.Array2.concat(
      ["generate", "create", "nano_banana_pro", "--prompt", prompt],
      Js.Array2.reduce(refs, (acc, r) => Js.Array2.concat(acc, ["--image", r]), []),
    ),
    ["--aspect_ratio", "16:9", "--resolution", "2k", "--wait", "--json"],
  )
  run(~episode, ~id, ~kind="still", ~model="nano_banana_pro",
    ~credits=Kuku_Spend.priceOf("nano_banana_pro"), ~prompt, ~refs, ~args, ~dst, ~ext="(png|webp|jpg)")
}

/* ---- clips ----------------------------------------------------------------- */
/* The start frame is a premise like any other: it must exist AND be engine-
   receipted, so a clip can never again be built on a frame the bible has left
   behind. Character boards ride along as image references — the author's law
   that identity never depends on the start frame alone. Seedance takes at
   most 9 reference images counting start and end; cast boards fill the rest. */
let clip = (~episode="EP10", ~id, ~spec: P.videoSpec, ~model, ~secs, ~start, ~endFrame="", ~dst, ()) => {
  let prompt = P.videoPrompt(spec) /* PromptGate inside */
  requireBoards(spec.cast)
  ignore(requireFile("start frame", start))
  if !receiptIntact(start) {
    refuse("STALE", "start frame " ++ start,
      "its receipt is absent or its premises drifted — regenerate the frame through the engine first")
  }
  if endFrame != "" {
    ignore(requireFile("end frame", endFrame))
    if !receiptIntact(endFrame) {
      refuse("STALE", "end frame " ++ endFrame,
        "its receipt is absent or its premises drifted — regenerate the frame through the engine first")
    }
  }
  let boards = Js.Array2.reduce(spec.cast, (acc, sub) =>
    switch P.boardOf(sub) {
    | Some(b) => Js.Array2.includes(acc, b) ? acc : Js.Array2.concat(acc, [b])
    | None => acc
    }
  , [])
  let slots = 9 - 1 - (endFrame == "" ? 0 : 1)
  if Js.Array2.length(boards) > slots {
    refuse("OVERFLOW",
      Belt.Int.toString(Js.Array2.length(boards)) ++ " cast sheets for " ++ Belt.Int.toString(slots) ++ " reference slots in " ++ id,
      "split the shot or reduce the cast — the law is every sheet attached, so dropping some silently is refused")
  }
  let boardRefs = boards
  let refs = Js.Array2.concatMany([start], [endFrame == "" ? [] : [endFrame], boardRefs])
  let credits = Kuku_Spend.priceOf(model) *. Belt.Int.toFloat(secs) /. 5.0
  let args = Js.Array2.concatMany(
    ["generate", "create", model, "--prompt", prompt, "--start-image", start],
    [
      endFrame == "" ? [] : ["--end-image", endFrame],
      Js.Array2.reduce(boardRefs, (acc, b) => Js.Array2.concat(acc, ["--image-references", b]), []),
      ["--generate_audio", "false", "--duration", Belt.Int.toString(secs)],
      ["--resolution", "720p", "--bitrate_mode", "high", "--aspect_ratio", "16:9", "--wait", "--json"],
    ],
  )
  run(~episode, ~id, ~kind="clip", ~model, ~credits, ~prompt, ~refs, ~args, ~dst, ~ext="(mp4|webm|mov)")
}

/* ---- edits ----------------------------------------------------------------- */
let edit = (~episode="EP10", ~id, ~spec: P.editSpec, ~src, ~dst, ()) => {
  let prompt = P.editPrompt(spec)
  ignore(requireFile("source image", src))
  if !receiptIntact(src) {
    refuse("STALE", "edit source " ++ src,
      "an edit inherits its source's authority — regenerate the source through the engine first")
  }
  let args = [
    "generate", "create", "nano_banana_pro", "--prompt", prompt, "--image", src,
    "--aspect_ratio", "16:9", "--resolution", "2k", "--wait", "--json",
  ]
  run(~episode, ~id, ~kind="edit", ~model="nano_banana_pro",
    ~credits=Kuku_Spend.priceOf("nano_banana_pro"), ~prompt, ~refs=[src], ~args, ~dst, ~ext="(png|webp|jpg)")
}

/* ---- plates ---------------------------------------------------------------- */
/* A plate's receipt carries the hash of the set prose it was rendered from, so
   a bible edit mechanically stales every plate derived from the old text —
   the failure this morning's bell-arch hunt found by hand. */
let plate = (~episode="EP10", ~id, ~prompt, ~refs: array<string>, ~dst, ~aspect="16:9", ()) => {
  let gated = PromptGate.pass(~which="plate " ++ id, prompt)
  Js.Array2.forEach(refs, r => ignore(requireFile("reference", r)))
  let args = Js.Array2.concat(
    Js.Array2.concat(
      ["generate", "create", "nano_banana_pro", "--prompt", gated],
      Js.Array2.reduce(refs, (acc, r) => Js.Array2.concat(acc, ["--image", r]), []),
    ),
    ["--aspect_ratio", aspect, "--resolution", "2k", "--wait", "--json"],
  )
  run(~episode, ~id, ~kind="plate", ~model="nano_banana_pro",
    ~credits=Kuku_Spend.priceOf("nano_banana_pro"), ~prompt=gated, ~refs, ~args, ~dst, ~ext="(png|webp|jpg)")
}

/* A LOCAL DETERMINISTIC TRANSFORM (the ga composite) may change an asset's
   pixels lawfully. It calls stamp() to update the recorded asset hash and
   append what it did, keeping the receipt intact without a provider call. */
let stamp = (~asset, ~note) =>
  if existsSync(receiptPath(asset)) {
    switch Js.Json.decodeObject(Js.Json.parseExn(readFileSync(receiptPath(asset), "utf8"))) {
    | Some(o) => {
        Js.Dict.set(o, "assetSha256", Js.Json.string(sha256File(asset)))
        let prior = switch o->Js.Dict.get("localTransforms")->Belt.Option.flatMap(Js.Json.decodeArray) {
        | Some(a) => a
        | None => []
        }
        Js.Dict.set(o, "localTransforms", Js.Json.array(Js.Array2.concat(prior, [Js.Json.string(note)])))
        writeFileSync(receiptPath(asset), Js.Json.stringifyWithSpace(Js.Json.object_(o), 1) ++ "\n")
      }
    | None => ()
    }
  }
