// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PromptGate from "./PromptGate.res.mjs";

function nameOf(n) {
  switch (n) {
    case "Kuku" :
        return "KUKU";
    case "Fyuria" :
        return "FYURIA";
    case "Leda" :
        return "LEDA";
    case "Castor" :
        return "CASTOR";
    case "Vesper" :
        return "VESPER";
    
  }
}

function colorOf(n) {
  switch (n) {
    case "Kuku" :
        return "green";
    case "Fyuria" :
        return "bright pink-red";
    case "Leda" :
        return "lilac-purple";
    case "Castor" :
        return "golden-yellow";
    case "Vesper" :
        return "pale blue";
    
  }
}

function shotName(s) {
  switch (s) {
    case "Wide" :
        return "WIDE";
    case "WideLow" :
        return "WIDE LOW ANGLE";
    case "HighWide" :
        return "HIGH WIDE";
    case "MediumWide" :
        return "MEDIUM-WIDE";
    case "Medium" :
        return "MEDIUM";
    case "CloseMedium" :
        return "CLOSE-MEDIUM";
    case "Close" :
        return "CLOSE";
    case "Insert" :
        return "INSERT CLOSE";
    case "WideAction" :
        return "WIDE ACTION";
    case "CloseAbstract" :
        return "CLOSE ABSTRACT";
    case "WideAbstract" :
        return "WIDE ABSTRACT";
    case "Sheet" :
        return "PUPPET SHEET";
    
  }
}

var styleKeyDefault = "a34b16f4-11fa-4153-9c43-ed2e2a30d033";

var styleKeyRef = {
  contents: styleKeyDefault
};

function useStyleKey(k) {
  styleKeyRef.contents = k;
}

function styleKey() {
  return styleKeyRef.contents;
}

var styleLaw = "3D papercraft, layered cut-paper illustration, soft matte construction-paper textures, visible paper edges and folds, an illustrated handcrafted paper world";

var paletteLaw = "bright, vibrant, warm storybook palette, every colour full and saturated";

var worldFacts = [
  "the only creatures anywhere in this picture are the ones this prompt names — a world of paper dragons, paper birds and paper animals",
  "every surface — stone, wood, cloth, banner and sky — is plain blank paper"
];

function bullets(xs) {
  return xs.map(function (x) {
                return "- " + x;
              }).join("\n");
}

function subjectText(s) {
  switch (s.TAG) {
    case "Dragon" :
        var name = s.name;
        return "- " + nameOf(name) + " — " + colorOf(name) + " paper dragon, " + (
                s.form === "Great" ? "GREAT form: ENORMOUS IN THE WORLD — a grown man would reach only to this dragon's knee, and this dragon towers over anything man-made beside it. That is the dragon's size in the world; the size in the picture is decided by how far away the viewpoint stands, so in a wide shot this dragon may be a small figure and still be enormous" : "small everyday form: a small paper dragon child, the height of a human child"
              ) + ", wearing a golden कड़ा on one forearm. " + s.doing;
    case "Gauri" :
        return "- GAURI — gentle brown-and-white paper cow, dark paper eyes; a plain rope halter is the ONLY thing she wears, her neck and legs otherwise bare. " + s.doing;
    case "RishiMuni" :
        return "- RISHI — the elder paper dragon guru from the attached character sheet: white-maned and white-bearded, pale horns, an ochre robe, a wooden staff. " + s.doing;
    case "Dadi" :
        return "- DADI — the paper grandmother bird from the attached character sheet. " + s.doing;
    case "Cheel" :
        return "- CHEEL — a great paper eagle, sharp-eyed, imposing. " + s.doing;
    case "Prop" :
        return "- " + s.what + " — " + s.doing;
    
  }
}

function castLine(s) {
  switch (s.TAG) {
    case "Dragon" :
        return "- " + nameOf(s.name) + " — " + s.doing;
    case "Gauri" :
        return "- GAURI the cow — " + s.doing;
    case "RishiMuni" :
        return "- RISHI — " + s.doing;
    case "Dadi" :
        return "- DADI — " + s.doing;
    case "Cheel" :
        return "- CHEEL the eagle — " + s.doing;
    case "Prop" :
        return "- " + s.what + " — " + s.doing;
    
  }
}

function isCharacter(s) {
  if (s.TAG === "Prop") {
    return false;
  } else {
    return true;
  }
}

function subjectFields(i, s) {
  var k = "subject[" + String(i) + "]";
  var rows;
  switch (s.TAG) {
    case "Dragon" :
        var name = s.name;
        rows = [
          [
            k + ".name",
            nameOf(name)
          ],
          [
            k + ".species",
            "paper dragon child"
          ],
          [
            k + ".colour",
            colorOf(name)
          ],
          [
            k + ".scale",
            s.form === "Great" ? "about seven metres tall — a grown man would reach only to this dragon's knee; the size in the picture depends on how far the viewpoint stands, so in a wide shot this dragon may be a small figure and still be enormous" : "knee high to a grown-up, the height of a human child"
          ],
          [
            k + ".pose",
            s.doing
          ]
        ];
        break;
    case "Gauri" :
        rows = [
          [
            k + ".name",
            "GAURI"
          ],
          [
            k + ".species",
            "paper cow"
          ],
          [
            k + ".colour",
            "brown and white, dark paper eyes"
          ],
          [
            k + ".pose",
            s.doing
          ]
        ];
        break;
    case "RishiMuni" :
        rows = [
          [
            k + ".name",
            "RISHI"
          ],
          [
            k + ".species",
            "elder paper dragon guru from the attached sheet"
          ],
          [
            k + ".pose",
            s.doing
          ]
        ];
        break;
    case "Dadi" :
        rows = [
          [
            k + ".name",
            "DADI"
          ],
          [
            k + ".species",
            "paper grandmother from the attached sheet"
          ],
          [
            k + ".pose",
            s.doing
          ]
        ];
        break;
    case "Cheel" :
        rows = [
          [
            k + ".name",
            "CHEEL"
          ],
          [
            k + ".species",
            "great paper eagle, sharp-eyed, imposing"
          ],
          [
            k + ".pose",
            s.doing
          ]
        ];
        break;
    case "Prop" :
        rows = [
          [
            k + ".name",
            s.what
          ],
          [
            k + ".state",
            s.doing
          ]
        ];
        break;
    
  }
  return rows.map(function (param) {
                return param[0] + ": " + param[1];
              }).join("\n");
}

function fieldBlock(subjects) {
  return subjects.map(function (s, i) {
                return subjectFields(i, s);
              }).join("\n\n");
}

function imagePrompt(s) {
  var match = s.shot;
  var tmp;
  tmp = match === "Sheet" ? "SHOT: PUPPET SHEET, LANDSCAPE 16:9: one character shown whole and large, straight on, standing on one flat sheet of paper — the same three-dimensional papercraft figure as on its character sheet, every piece with real thickness and a soft shadow on the sheet." : "SHOT: " + shotName(s.shot) + ", LANDSCAPE 16:9, full-bleed scene, the camera is INSIDE the world.";
  var match$1 = s.plate;
  var tmp$1;
  if (match$1 !== undefined) {
    var match$2 = s.shot;
    var tmp$2;
    switch (match$2) {
      case "Medium" :
      case "CloseMedium" :
      case "Close" :
      case "Insert" :
      case "CloseAbstract" :
      case "Sheet" :
          tmp$2 = "set.rule: image[1] is this same location seen closer — identical ground material and paving, identical walls, kerbs, stone and paper textures, identical palette and light; every landmark inside this tighter frame sits where image[1] puts it";
          break;
      default:
        tmp$2 = "set.rule: image[1] IS this location, already built — same ground, same landmarks in the same places, same walls, kerbs and horizon, same camera vantage, same architecture";
    }
    tmp$1 = "set.ref: image[1]\n" + tmp$2 + (
      s.objects.length > 0 ? "\nobject.ref: the image after the plate is a locked story object — identical form, proportion, colour and material every time it appears" : ""
    ) + "\ncast.ref: every remaining attached image is a locked character design — the sheet is the authority on that character's build, colour and everything worn; reproduce each design exactly as the sheet shows it";
  } else {
    var match$3 = s.shot;
    tmp$1 = match$3 === "Sheet" ? "cast.ref: image[2] is the locked character design — the authority on build, colour, markings and everything worn; the pose in this picture is the one written in SCENE and drawn in the silhouette" : "cast.ref: every attached image after the first is a locked character design — the sheet is the authority on that character's build, colour and everything worn; reproduce each design exactly as the sheet shows it";
  }
  var match$4 = s.blockout;
  var match$5 = s.shot;
  var tmp$3;
  tmp$3 = match$4 !== undefined ? (
      match$5 === "Sheet" ? "POSE: image[1] is a flat silhouette in the character's own colour on the same sheet, showing the pose for this picture — the authority on where every limb goes: head, wings, arms, legs and tail; paint the finished papercraft character exactly over it, limb for limb, with the plain sheet all around." : "STAGING: the attached grey BLOCKOUT is a 3D render of this exact moment — it is the authority on WHERE EVERY BODY STANDS and where the camera looks. Each coloured proxy marks one character by their own colour (green कुकु, pink-red फ्यूरिया, lilac लेडा, golden-yellow कैस्टर, pale blue वैस्पर, cream ऋषि, brown cart, cream cow): put that character exactly there, at that size, facing that way, on that ground. Paint the finished papercraft world over this arrangement — the blockout owns the positions, the style reference owns the look."
    ) : "";
  return PromptGate.passStrict("imagePrompt", [
                tmp,
                "style.ref: image[0] — match its look EXACTLY",
                "style.medium: " + styleLaw,
                "style.palette: " + paletteLaw,
                tmp$1,
                tmp$3,
                "SCENE: " + s.scene,
                fieldBlock(s.subjects),
                "setting.place: " + s.setting,
                "light.state: " + s.lighting,
                "world.rules:\n" + bullets((
                        s.subjects.some(isCharacter) ? worldFacts : ["this is an object/insert shot: the frame holds the place and the named objects alone"].concat(worldFacts)
                      ).concat(s.extraRules))
              ].join("\n"));
}

var editKeepLaw = [
  "same 3D papercraft medium and layered cut-paper texture",
  "same bright vibrant palette and same lighting",
  "same character designs, poses and expressions unless the change says otherwise",
  "same composition and camera"
];

function editPrompt(e) {
  return PromptGate.passStrict("editPrompt", [
                "TASK: edit the attached image — apply ONLY the change below.",
                "CHANGE: " + e.change,
                "KEEP:\n" + bullets(editKeepLaw.concat(e.keep)),
                "world.rules:\n" + bullets(worldFacts.concat(e.extraRules))
              ].join("\n"));
}

var directionLaw = ["TRAVEL KEEPS ONE DIRECTION: whatever moves may start from rest, speed up or slow down, and its path always continues the same way."];

var travellingCameraLaw = ["the camera keeps one direction of travel too, and the ground streams past in one consistent direction the entire time"];

var paperPhysics = ["motion has real weight"];

var dragonContinuity = ["the golden कड़ा stays on the same forearm as in the start image"];

function hasDragon(cast) {
  return cast.some(function (s) {
              if (s.TAG === "Dragon") {
                return true;
              } else {
                return false;
              }
            });
}

function videoPrompt(v) {
  return PromptGate.passStrict("videoPrompt", [
                  "SCENE: " + v.scene,
                  v.cast.length > 0 ? "THE COMPLETE CAST OF THIS SHOT — exactly these:\n" + v.cast.map(castLine).join("\n") : "IN THIS SHOT: the place itself, empty and still.",
                  "FIRST FRAME: the provided start image IS frame one — the action begins from exactly this position.",
                  "FORMAT: one single unbroken take.",
                  "BLOCKING:\n" + bullets(v.blocking),
                  "ACTION TIMING:\n" + bullets(v.beats),
                  "CAMERA: " + v.camera,
                  "PHYSICS:\n" + bullets(directionLaw.concat(v.cameraTravels ? travellingCameraLaw : [], paperPhysics, hasDragon(v.cast) ? dragonContinuity : [], v.physics)),
                  "LIGHTING: " + v.lighting,
                  v.audio === "" ? "" : "AUDIO: " + v.audio,
                  "STYLE: every frame keeps exactly the cut-paper papercraft look of the start image.",
                  v.extraRules.length > 0 ? "HARD RULES:\n" + bullets(v.extraRules) : ""
                ].filter(function (l) {
                    return l !== "";
                  }).join("\n"));
}

var kukuRoot = "../stories/kuku/";

function boardOf(s) {
  switch (s.TAG) {
    case "Dragon" :
        var name = s.name;
        if (s.form !== "Small") {
          return kukuRoot + "ep10prod/elements/future_" + nameOf(name).toLowerCase() + "_board_bracelet.png";
        }
        switch (name) {
          case "Kuku" :
              return kukuRoot + "charsheets/kuku.png";
          case "Fyuria" :
              return kukuRoot + "charsheets/furia.png";
          case "Leda" :
              return kukuRoot + "charsheets/leda_small.png";
          case "Castor" :
              return kukuRoot + "charsheets/castor.png";
          case "Vesper" :
              return kukuRoot + "charsheets/vesper_small.png";
          
        }
    case "Gauri" :
        return kukuRoot + "charsheets/gauri.png";
    case "RishiMuni" :
        return kukuRoot + "charsheets/rishi.png";
    case "Dadi" :
        return kukuRoot + "charsheets/dadi.png";
    case "Cheel" :
        return kukuRoot + "charsheets/cheel.png";
    case "Prop" :
        return ;
    
  }
}

function imageRefs(s) {
  var b = s.blockout;
  var staging = b !== undefined ? [b] : [];
  var p = s.plate;
  var head = p !== undefined ? [styleKeyRef.contents].concat(staging, [p], s.objects) : [styleKeyRef.contents].concat(staging, s.objects);
  var boards = s.subjects.reduce((function (acc, sub) {
          var b = boardOf(sub);
          if (b !== undefined && !acc.includes(b)) {
            return acc.concat([b]);
          } else {
            return acc;
          }
        }), []);
  return head.concat(boards);
}

export {
  nameOf ,
  colorOf ,
  shotName ,
  styleKeyDefault ,
  styleKeyRef ,
  useStyleKey ,
  styleKey ,
  styleLaw ,
  paletteLaw ,
  worldFacts ,
  bullets ,
  subjectText ,
  castLine ,
  isCharacter ,
  subjectFields ,
  fieldBlock ,
  imagePrompt ,
  editKeepLaw ,
  editPrompt ,
  directionLaw ,
  travellingCameraLaw ,
  paperPhysics ,
  dragonContinuity ,
  hasDragon ,
  videoPrompt ,
  kukuRoot ,
  boardOf ,
  imageRefs ,
}
/* PromptGate Not a pure module */
