// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Kuku_Engine from "./Kuku_Engine.res.mjs";
import * as Kuku_Ep10Sets from "./Kuku_Ep10Sets.res.mjs";
import * as Child_process from "child_process";
import * as Kuku_PromptSpec from "./Kuku_PromptSpec.res.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var opts = {
  encoding: "utf8",
  timeout: 1800000
};

var ep10 = Kuku_PromptSpec.kukuRoot + "ep10prod/";

var stills = ep10 + "stills/";

var clips = ep10 + "clips/";

var laneSet = Kuku_Ep10Sets.setProse("Lane");

function d(name, doing) {
  return {
          TAG: "Dragon",
          name: name,
          form: "Great",
          doing: doing
        };
}

function dSmall(name, doing) {
  return {
          TAG: "Dragon",
          name: name,
          form: "Small",
          doing: doing
        };
}

function cow(doing) {
  return {
          TAG: "Gauri",
          doing: doing
        };
}

var commonBlocking = [
  "the start image IS this lane — the same flagstones, low kerbs, rubble wall along the right, stone post behind, and the same horizon and sun",
  "the cart runs along the CENTRELINE, wheels on the flagstones the whole way, the kerbs sliding past on either side",
  "गौरी the brown-and-white paper cow stays aboard the cart in EVERY frame, braced in the hay",
  "three red bands painted flat across the lane's paving cross it at 12, 24 and 36 metres; the closed stone end wall stays a distant line at the bottom of the slope for the whole clip"
];

var commonPhysics = [
  Kuku_Ep10Sets.greatFormStaging,
  Kuku_Ep10Sets.greatFormFraming,
  "the lane is RIGID: kerbs, markers, post and wall keep their positions, the lane keeps its exact length, and each marker slides past exactly once",
  "wheels turn at a speed that matches the ground moving past them"
];

var commonRules = ["गौरी is in the cart in EVERY frame — a cart running empty is wrong"];

var talkPhysics = [
  Kuku_Ep10Sets.greatFormStaging,
  Kuku_Ep10Sets.greatFormFraming,
  "the character stays planted on the same spot for the whole clip — a held shot, the body anchored, the head, mouth and wings carrying the performance",
  "the mouth moves in natural speech throughout, jaw and lips working, with small head movements and blinks between phrases"
];

var all = [
  {
    tag: "c1_breaks_away",
    start: stills + "h15_cart_runs.png",
    endFrame: "",
    secs: 10,
    spec: {
      scene: "The tethered hay cart breaks away and begins to run down the gurukul's flight-lane at golden dusk, गौरी braced inside it, the loosed red rope trailing behind, its knot slid open. The cart and गौरी are the complete cast of this clip. " + laneSet,
      cameraTravels: true,
      cast: [{
          TAG: "Gauri",
          doing: "braced in the running cart"
        }],
      blocking: commonBlocking.concat(["the cart and गौरी are the complete cast from first frame to last — the lane belongs to them alone"]),
      beats: [
        "0.0-3.0s: the cart is already moving and gathering speed, hay lifting, the loose red rope snaking behind it",
        "3.0-7.0s: it runs on down the slope, gathering speed, the FIRST red marker still ahead of it",
        "7.0-10.0s: still accelerating — and in the last second the FIRST red marker slides under its wheels and away behind"
      ],
      camera: "one single continuous tracking shot alongside the cart at cart height, travelling at its speed, holding one framing and facing DOWN the lane from first frame to last",
      physics: commonPhysics.concat(["the cart's whole travel this clip is about twelve metres — from the top of the slope to the first marker"]),
      lighting: "constant warm golden dusk exactly as the start image, low sun, long soft shadows, the light holding steady for the whole clip",
      audio: "",
      extraRules: commonRules
    },
    talking: false,
    cheap: false
  },
  {
    tag: "c2_five_flank",
    start: stills + "h16_five_flank.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "All five sweep in and take up formation around the running cart. " + laneSet,
      cameraTravels: true,
      cast: [
        {
          TAG: "Dragon",
          name: "Fyuria",
          form: "Great",
          doing: "lowest and furthest forward"
        },
        {
          TAG: "Dragon",
          name: "Kuku",
          form: "Great",
          doing: "on the cart's left"
        },
        {
          TAG: "Dragon",
          name: "Leda",
          form: "Great",
          doing: "on the cart's right, head turned down to the lane"
        },
        {
          TAG: "Dragon",
          name: "Castor",
          form: "Great",
          doing: "tight beside the cart"
        },
        {
          TAG: "Dragon",
          name: "Vesper",
          form: "Great",
          doing: "highest of all"
        },
        {
          TAG: "Gauri",
          doing: "braced in the running cart"
        }
      ],
      blocking: commonBlocking.concat([
            "FYURIA flies lowest and furthest forward, KUKU on the cart's left, LEDA on its right with her head turned down to the lane, CASTOR tight beside it, VESPER highest of all",
            "each dragon towers over the cart — the cart is small beneath them"
          ]),
      beats: [
        "0.0-2.0s: the five drop into place around the running cart, wings spread wide",
        "2.0-5.0s: they hold formation and travel with it as it passes the FIRST marker"
      ],
      camera: "a continuous tracking shot alongside the cart and its escort at cart height, matching their speed. The camera looks DOWN the lane in the direction of travel for the entire clip, holding that facing to the last frame, and the flagstones stream TOWARD the camera and out of the bottom of frame the whole time. One continuous take.",
      physics: commonPhysics.concat(["the cart's whole travel this clip is about eight metres"]),
      lighting: "constant warm golden dusk exactly as the start image, the light holding steady for the whole clip",
      audio: "",
      extraRules: commonRules
    },
    talking: false,
    cheap: false
  },
  {
    tag: "c3_failed_lift",
    start: stills + "h17_group_lift.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "The five grip the cart's wheels and heave all four up together — a hand's height, a sway — and the weight wins. " + laneSet,
      cameraTravels: true,
      cast: [
        {
          TAG: "Dragon",
          name: "Kuku",
          form: "Great",
          doing: "front-left wheel"
        },
        {
          TAG: "Dragon",
          name: "Fyuria",
          form: "Great",
          doing: "front-right wheel"
        },
        {
          TAG: "Dragon",
          name: "Castor",
          form: "Great",
          doing: "rear-left wheel"
        },
        {
          TAG: "Dragon",
          name: "Leda",
          form: "Great",
          doing: "rear-right wheel"
        },
        {
          TAG: "Dragon",
          name: "Vesper",
          form: "Great",
          doing: "the centre rail from above"
        },
        {
          TAG: "Gauri",
          doing: "sliding in the hay as the cart twists"
        }
      ],
      blocking: commonBlocking.concat([
            "KUKU has the front-left wheel, FYURIA the front-right, CASTOR the rear-left, LEDA the rear-right, VESPER the centre rail from above",
            "all four wheels come off the track TOGETHER, only a hand's height, the cart level and swaying under its own weight"
          ]),
      beats: [
        "0.0-2.0s: all five take hold and heave, wings beating hard, all four wheels rising a little together",
        "2.0-4.0s: the cart sways level in the air, a hand above the track, and गौरी braces in the hay",
        "4.0-5.0s: the weight wins — all four wheels settle back toward the track, the cart still moving forward"
      ],
      camera: "one single continuous low tracking shot alongside, at wheel height, matching the cart's speed",
      physics: commonPhysics.concat([
            "all four wheels rise together by less than a wheel's height and settle back together",
            "the cart covers about four metres in this clip"
          ]),
      lighting: "constant warm golden dusk exactly as the start image, the light holding steady for the whole clip",
      audio: "",
      extraRules: commonRules
    },
    talking: false,
    cheap: false
  },
  {
    tag: "c4_wheels_return",
    start: stills + "h19_wheels_return.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "The lift is abandoned: the cart's wheels come back down onto the flagstones, dust puffs out, and it runs on with गौरी still aboard. Every dragon has let go of it. " + laneSet,
      cameraTravels: true,
      cast: [{
          TAG: "Gauri",
          doing: "braced in the cart as it settles and runs on"
        }],
      blocking: commonBlocking.concat(["the dragons have let go and pulled up out of frame; the cart is alone on the lane again"]),
      beats: [
        "0.0-2.0s: all four wheels settle back onto the flagstones together and dust puffs out around them",
        "2.0-5.0s: the cart rights itself and runs on down the slope, गौरी braced, hay still lifting"
      ],
      camera: "one single continuous low tracking shot at wheel height alongside the cart",
      physics: commonPhysics.concat(["the cart covers about four metres in this clip"]),
      lighting: "constant warm golden dusk exactly as the start image, the light holding steady for the whole clip",
      audio: "",
      extraRules: commonRules
    },
    talking: false,
    cheap: false
  },
  {
    tag: "s0b_rope_slips",
    start: stills + "h12_rope_slip.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "चील's talon, reaching down from the top of frame, draws the knot's last loop open at the stone post — the rope end pulls free and whips away after the cart.",
      cameraTravels: false,
      cast: [
        {
          TAG: "Cheel",
          doing: "only her one dark talon in frame at the top, hooking the knot's last loop and drawing it open"
        },
        {
          TAG: "Prop",
          what: "THE ROPE",
          doing: "thick red paper twine, pulled taut around the weathered stone post"
        }
      ],
      blocking: [
        "the start image IS this post and this knot — the same stone, the same rope, the same light",
        "the stone post holds perfectly still, exactly as the start image has it"
      ],
      beats: [
        "0.0-1.5s: the rope is stretched tight under load — and चील's dark talon, reaching down from the top of frame, hooks the knot's last loop and draws it open",
        "1.5-3.0s: the loops slide, turn by turn, the knot opening as the load pulls it apart",
        "3.0-5.0s: the last loop lets go and the freed rope end whips away out of frame, leaving the post bare"
      ],
      camera: "one locked-off CLOSE camera on the post and knot, held perfectly still for the whole clip",
      physics: [
        "the rope moves like stiff paper twine — it bends at creases and holds its shape, stiff from end to end",
        "once the knot begins to give it keeps giving; the loops only ever loosen",
        "the post stays exactly where it is and keeps its shape throughout"
      ],
      lighting: "constant warm golden dusk exactly as the start image",
      audio: "",
      extraRules: []
    },
    talking: false,
    cheap: false
  },
  {
    tag: "s0c_bell_taken",
    start: stills + "h13_bell_taken.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "चील takes the bell: perched on the crown of the great stone flight ring, she works the bronze binding open, the bell drops free into her talons, and she lifts away with it.",
      cameraTravels: false,
      cast: [
        {
          TAG: "Cheel",
          doing: "perched on the ring's crown above the hanging bell, working its binding loose, then lifting away with the bell in her talons"
        },
        {
          TAG: "Prop",
          what: "THE BELL",
          doing: "bronze, hanging from its short bronze hook inside the crown of the flight ring, warm and gleaming"
        }
      ],
      blocking: [
        "the start image IS this ring and this bell — the same stone, the same hook, the same sky and light",
        "the great stone ring holds perfectly still throughout, exactly as the start image has it",
        "she is the only creature in frame"
      ],
      beats: [
        "0.0-1.5s: she leans down and works the bronze binding at the ring's crown with her beak and talons, the bell swinging a little as it loosens",
        "1.5-2.5s: the binding gives and the bell drops free, caught in her talons, swinging under her once",
        "2.5-5.0s: her great wings open and beat down, and she lifts away from the ring with the bell held beneath her, rising out of the top of frame"
      ],
      camera: "one locked-off MEDIUM camera on the ring's crown, held perfectly still for the whole clip, with sky above so she has room to rise into it",
      physics: [
        "the bell hangs and swings from the single point of its bronze binding, and once caught it hangs from her talons the same way",
        "her wings move like stiff cut paper, and the downbeat is what lifts her — she rises only when they beat",
        "the ring, its stones and the hook keep their shapes; only the bell and the eagle move"
      ],
      lighting: "constant warm golden dusk exactly as the start image",
      audio: "",
      extraRules: []
    },
    talking: false,
    cheap: false
  },
  {
    tag: "s0a_furia_ring",
    start: stills + "h53_ring_drill_wide.png",
    endFrame: stills + "h53_ring_drill_wide.png",
    secs: 5,
    spec: {
      scene: "फ्यूरिया flies out: up from the launch circle, through the opening of the great stone ring, and she banks round behind it to come back toward the courtyard.",
      cameraTravels: false,
      cast: [{
          TAG: "Dragon",
          name: "Fyuria",
          form: "Great",
          doing: "flying one circuit: mark, through the ring, round and back to the mark"
        }],
      blocking: [
        "the start image IS this courtyard — the same flagstones, the same ring, the same sky and light",
        "the RING holds perfectly still, exactly as the start image has it; it is fourteen metres across, and she passes through its opening with her wings spread"
      ],
      beats: [
        "0.0-1.2s: she crouches on the launch circle and launches toward the ring, paper dust curling from the stones beneath her",
        "1.2-2.4s: she flies INTO the ring's opening and through it, crossing from the near side of the ring to the far side",
        "2.4-3.6s: beyond the ring she banks round in a wide arc and comes back toward the courtyard",
        "3.6-5.0s: she comes back round toward the courtyard, wings wide, lining up on the launch circle"
      ],
      camera: "one locked-off WIDE camera on the courtyard floor, held perfectly still for the whole clip, the ring centred and whole in frame with sky above it",
      physics: [
        "PROOF OF PASSAGE: as she goes through, the ring's near rim briefly passes in front of her body, hiding part of her for a moment, and on the far side the ring's stone is nearer to camera than she is",
        "SEAMLESS LOOP: the final frame matches the first exactly — same place on the mark, same pose, same wing position — so the clip can play again straight after itself",
        "she passes cleanly through the empty middle of the opening, well clear of the stone"
      ],
      lighting: "constant warm golden dusk exactly as the start image — low sun, long soft shadows",
      audio: "",
      extraRules: []
    },
    talking: false,
    cheap: false
  },
  {
    tag: "s0d_bell_touch",
    start: stills + "h53_ring_drill_wide.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "फ्यूरिया flies the drill: up from the launch circle, through the opening of the great stone ring, and as she passes she brushes the bronze bell hanging inside it with one claw so that it rings. She banks round, comes in fast, and lands — one claw scuffing a hand's width past the circle's edge as she stops.",
      cameraTravels: false,
      cast: [{
          TAG: "Dragon",
          name: "Fyuria",
          form: "Great",
          doing: "flying through the ring and brushing the bell with one claw as she passes"
        }],
      blocking: [
        "the start image IS this courtyard — the same flagstones, the same ring, the same bell, the same sky and light",
        "the RING holds perfectly still, exactly as the start image has it; it is fourteen metres across, and she passes through its opening with her wings spread",
        "THE BELL HANGS INSIDE THE RING and stays hanging on its hook from first frame to last — her claw meets it for one instant and travels on, and the bell swings in place behind her",
        "SHE IS AIRBORNE FROM LAUNCH TO LANDING: her wings carry her the whole way, and the only contacts in the whole clip are her claw on the bell (one instant, in passing) and her feet on the launch circle at the first and last moments",
        "ONE TOUCH ONLY: the claw meets the bell exactly once, mid-flight, on her way through"
      ],
      beats: [
        "0.0-1.2s: she crouches on the launch circle and launches toward the ring, paper dust curling from the stones beneath her",
        "1.2-2.6s: she flies INTO the ring's opening, and as she passes the hanging bell she reaches out ONE FORELIMB and brushes it lightly with a claw",
        "2.6-3.0s: the bell swings on its hook from the touch and rings",
        "3.0-5.0s: beyond the ring she banks round in a wide arc, comes in fast, and lands on the launch circle — one hind claw scuffing a hand's width past its edge as she stops, dust puffing"
      ],
      camera: "one locked-off WIDE camera on the courtyard floor, held perfectly still for the whole clip, the ring centred and whole in frame with sky above it",
      physics: [
        "PROOF OF PASSAGE: as she goes through, the ring's near rim briefly passes in front of her body, hiding part of her for a moment, and on the far side the ring's stone is nearer to camera than she is",
        "A PASSING BRUSH: the claw makes contact for one moment and travels on; the bell is left swinging on its hook, still hanging in the ring",
        "the bell swings from its single hook like a real bell, pivoting at that one point",
        "she passes cleanly through the empty middle of the opening, well clear of the stone"
      ],
      lighting: "constant warm golden dusk exactly as the start image — low sun, long soft shadows",
      audio: "",
      extraRules: []
    },
    talking: false,
    cheap: false
  },
  {
    tag: "b1_breath_fail",
    start: stills + "h24_kuku_breath_fail.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "कुकु tries to forge and his breath fails: a thin stream of golden paper light leaves his mouth, wavers, scatters into shapeless drifting wisps and fades to a few falling paper flecks. The stone below stays bare.",
      cameraTravels: false,
      cast: [{
          TAG: "Dragon",
          name: "Kuku",
          form: "Great",
          doing: "hovering in place, exhaling a thin golden breath that scatters and dies"
        }],
      blocking: [
        "the start image IS this place — the same stone, kerbs and light",
        "कुकु holds his position in the air through the whole clip, wings beating steadily"
      ],
      beats: [
        "0.0-1.5s: he draws a breath and exhales a thin stream of golden paper light",
        "1.5-3.5s: the stream wavers, breaks into curling wisps and scatters in the air",
        "3.5-5.0s: the last flecks drift down and fade; his eyes go wide — startled, deflated"
      ],
      camera: "one locked static camera, holding one framing from first frame to last",
      physics: [
        "the golden light behaves like cut paper — flat curls and flecks, drifting with weight",
        "the stone below stays bare from first frame to last"
      ],
      lighting: "constant light exactly as the start image, holding steady for the whole clip",
      audio: "",
      extraRules: []
    },
    talking: false,
    cheap: false
  },
  {
    tag: "b2_forging",
    start: stills + "h28_forging.png",
    endFrame: stills + "h29_ga_stands.png",
    secs: 5,
    spec: {
      scene: "The forging: कुकु exhales a broad steady stream of golden paper light onto the flat stone, and the golden shape builds itself whole out of the light — finishing exactly as the end image shows, seated on the stone with a heavy settling weight.",
      cameraTravels: false,
      cast: [
        {
          TAG: "Dragon",
          name: "Kuku",
          form: "Great",
          doing: "exhaling a broad golden stream onto the flat stone, steady and sure"
        },
        {
          TAG: "Dragon",
          name: "Leda",
          form: "Great",
          doing: "at the stone's far edge, wings half-raised, eyes on the forming shape"
        }
      ],
      blocking: [
        "the start image IS this place and the END image is this same place a breath later — the shape grows from the first into the second",
        "the golden shape that forms is EXACTLY the shape in the end image — the same form, proportion and position, built up from flowing golden light",
        "कुकु and लेडा keep their positions; only his breath and the growing shape move"
      ],
      beats: [
        "0.0-1.5s: the golden stream pours onto the stone and pools into flowing light",
        "1.5-4.0s: the light rises and takes form, edges firming from liquid gold to solid golden paper",
        "4.0-5.0s: the finished shape settles onto the stone with visible weight — one heavy seat — and the light stills"
      ],
      camera: "one locked static camera, holding the exact framing shared by the start and end images",
      physics: [
        "the shape seats DOWN into place at the end — a heavy, final settling, dust puffing at its base",
        "the stream flows in one direction, mouth to stone, for the whole clip"
      ],
      lighting: "constant deepening dusk exactly as the start image, the golden light of the forging the only new light",
      audio: "",
      extraRules: []
    },
    talking: false,
    cheap: false
  },
  {
    tag: "b3_three_beats",
    start: stills + "h36_three_beats.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "फ्यूरिया holds ahead of the slowing cart and beats her wings against its motion — three deep deliberate beats, each one slowing the cart further, paper dust rolling beneath each stroke.",
      cameraTravels: true,
      cast: [
        {
          TAG: "Dragon",
          name: "Fyuria",
          form: "Great",
          doing: "flying backwards ahead of the cart, forepaws braced on its front wall, wings in deep deliberate beats"
        },
        {
          TAG: "Gauri",
          doing: "braced in the cart, steadying as it slows"
        }
      ],
      blocking: [
        "the start image IS this lane — the same flagstones, kerbs and light",
        "फ्यूरिया stays ahead of the cart with her forepaws on its front wall the whole clip",
        "the cart continues DOWN the lane, slowing the whole time"
      ],
      beats: [
        "0.0-1.6s: FIRST deep wingbeat — dust rolls out from under her wings, the cart slows a little",
        "1.6-3.2s: SECOND deep beat, stronger — hay shifts forward in the cart bed",
        "3.2-5.0s: THIRD beat — the cart is visibly slower by the last frame, wheels turning gently"
      ],
      camera: "one single continuous tracking shot alongside, matching the cart's slowing speed, facing along the lane the whole clip",
      physics: commonPhysics.concat(["each wingbeat visibly costs her effort and visibly slows the cart — action and result linked"]),
      lighting: "constant deepening golden dusk exactly as the start image, the light holding steady for the whole clip",
      audio: "",
      extraRules: commonRules
    },
    talking: false,
    cheap: false
  },
  {
    tag: "b4_curve_stop",
    start: stills + "h37_cart_into_curve.png",
    endFrame: stills + "h38_stopped.png",
    secs: 5,
    spec: {
      scene: "The stop the golden shape was forged for: the cart rolls its last stretch and its nose rides up into the open curve of the golden shape, which receives it and holds it — wheels turning slower until they stand still, exactly as the end image shows, गौरी steady in the bed.",
      cameraTravels: false,
      cast: [
        {
          TAG: "Dragon",
          name: "Fyuria",
          form: "Great",
          doing: "flying backwards ahead of the cart, forepaws on its front wall, her slow heavy wingbeats matching its last metres"
        },
        {
          TAG: "Gauri",
          doing: "standing braced in the cart bed as the golden curve receives the cart and it comes to rest"
        }
      ],
      blocking: [
        "the start image IS this place and the END image is this same place moments later — the clip travels from one to the other",
        "the cart moves only forward, slower every second, and is perfectly still by the last frame"
      ],
      beats: [
        "0.0-2.0s: the cart rolls in, wheels turning slowly, its nose entering the golden curve and beginning to CLIMB its shallow slope",
        "2.0-4.0s: the climb drains the cart's speed — the drag rises, hay settles, गौरी's footing steadies, फ्यूरिया's wingbeats slow with it",
        "4.0-5.0s: the wheels stand still; dust settles; everything at rest exactly as the end image"
      ],
      camera: "one locked static camera, holding the exact framing shared by the start and end images",
      physics: [
        "wheels turn at a speed matching the ground passing beneath them, down to a full stop",
        "the stop is gentle and final — the cart stays at rest once stopped",
        "THE GOLDEN SHAPE IS RIGID AND ROOTED: it keeps its exact form and position while the cart settles against its curve"
      ],
      lighting: "constant dusk exactly as the start image, the light holding steady for the whole clip",
      audio: "",
      extraRules: ["गौरी stays in the cart bed the whole clip, upright and calm by the end"]
    },
    talking: false,
    cheap: false
  },
  {
    tag: "b5_shrink",
    start: stills + "h39_shrink_glow.png",
    endFrame: stills + "h54_small_five_stand.png",
    secs: 5,
    spec: {
      scene: "Five columns of soft golden paper light stand where the five dragons were; the light settles and sinks, and inside each column a small everyday dragon child appears — finishing exactly as the end image shows, five small dragons standing together on the flagstones.",
      cameraTravels: false,
      cast: [
        {
          TAG: "Dragon",
          name: "Kuku",
          form: "Small",
          doing: "appearing within the far-left column as the light settles"
        },
        {
          TAG: "Dragon",
          name: "Fyuria",
          form: "Small",
          doing: "appearing within the second column"
        },
        {
          TAG: "Dragon",
          name: "Leda",
          form: "Small",
          doing: "appearing within the centre column"
        },
        {
          TAG: "Dragon",
          name: "Castor",
          form: "Small",
          doing: "appearing within the fourth column"
        },
        {
          TAG: "Dragon",
          name: "Vesper",
          form: "Small",
          doing: "appearing within the far-right column"
        }
      ],
      blocking: [
        "the start image IS this place and the END image is this same place after the light settles — the clip travels from one to the other",
        "each column of light shrinks DOWN in place, and the small dragon in the end image appears exactly where that column stood"
      ],
      beats: [
        "0.0-2.0s: the five golden columns glow and slowly sink, paper-light motes drifting",
        "2.0-4.0s: within each column a small silhouette resolves as the light thins",
        "4.0-5.0s: the last light dissolves into drifting golden flecks — five small dragons stand exactly as the end image"
      ],
      camera: "one locked static camera, holding the exact framing shared by the start and end images",
      physics: ["the light behaves like cut paper — flat golden motes and curls, sinking with weight"],
      lighting: "constant dusk exactly as the start image, the golden columns the only extra light, fading as they settle",
      audio: "",
      extraRules: []
    },
    talking: false,
    cheap: false
  },
  {
    tag: "b6_tower_door",
    start: stills + "h44_tower_door.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "चील stands before the tall stone door — shut, open only a hair's width, a thin dark seam at its edge — with the stolen bronze bell. She takes the bell up, studies the door, raises her claw — and STRIKES the bell once, full and clean. The clip ends on the bell still shivering from the strike.",
      cameraTravels: false,
      cast: [{
          TAG: "Cheel",
          doing: "before the closed door, lifting the bell, raising a claw to strike it"
        }],
      blocking: [
        "the start image IS this place — the same door, stone and light",
        "the door stays SHUT to a hair's-width seam from first frame to last, exactly as the start image has it",
        "the bell begins on the stones at her feet, and from the moment she lifts it it stays in her talon to the last frame"
      ],
      beats: [
        "0.0-2.0s: she takes the bronze bell up from the stones in one talon, lifts it level with her eyes and tilts her head at the door",
        "2.0-4.0s: she looks from the bell to the door, slow and deliberate",
        "4.0-5.0s: she strikes the bell once — one full clean swing — and the last frames hold on the bell shivering, the door unmoved"
      ],
      camera: "one locked static camera, holding one framing from first frame to last",
      physics: ["the bell swings slightly from her movements, hanging from its one point in her talon"],
      lighting: "constant cool fading dusk exactly as the start image, blue-grey on the stone, holding steady",
      audio: "",
      extraRules: []
    },
    talking: false,
    cheap: false
  },
  {
    tag: "s2a_furia_brakes",
    start: stills + "h20_furia_brake.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "FYURIA flies BACKWARDS ahead of the running cart, wings beating against it, trying to slow it. " + laneSet,
      cameraTravels: true,
      cast: [
        {
          TAG: "Dragon",
          name: "Fyuria",
          form: "Great",
          doing: "flying backwards ahead of the cart, wings beating against it"
        },
        {
          TAG: "Gauri",
          doing: "braced in the running cart"
        }
      ],
      blocking: commonBlocking.concat([
            "फ्यूरिया is ahead of the cart, facing back toward it, flying in reverse down the lane while the cart bears down on her",
            "she towers over the cart — the cart is small beneath her"
          ]),
      beats: [
        "0.0-2.0s: her wings sweep forward hard against the oncoming cart, paper dust rolling up between them",
        "2.0-5.0s: the cart slows a little but keeps coming; she is driven backwards down the lane by it"
      ],
      camera: "one single continuous tracking shot alongside both of them at cart height, looking down the lane in the direction of travel, the flagstones streaming toward the camera and out of the bottom of frame",
      physics: commonPhysics.concat([
            "cart and dragon both continue to travel DOWN the lane throughout — the cart still winning against her push",
            "the cart covers about five metres in this clip"
          ]),
      lighting: "constant deepening golden dusk exactly as the start image, the light holding steady for the whole clip",
      audio: "",
      extraRules: commonRules
    },
    talking: false,
    cheap: false
  },
  {
    tag: "s2b_marker_passes",
    start: stills + "h23_marker_pass.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "Close on the lane surface: the second flat red distance mark passes beneath the cart's rushing wheels. " + laneSet,
      cameraTravels: false,
      cast: [{
          TAG: "Gauri",
          doing: "braced in the cart as it rushes through frame"
        }],
      blocking: [
        "the start image IS this lane — same flagstones, same kerbs, same light",
        "the red mark is FLUSH with the paving, an inlaid stone the wheels roll straight over, the cart staying level as it passes",
        "the cart and गौरी are the complete cast of this clip"
      ],
      beats: [
        "0.0-2.5s: wooden wheels rush across frame, dust lifting from the flagstones",
        "2.5-5.0s: the flat red mark slides beneath them and away behind, out of the bottom of frame"
      ],
      camera: "a low LOCKED camera fixed in place close to the lane surface, holding one framing as the cart passes through frame",
      physics: commonPhysics.concat(["the wheels and the ground move in ONE direction across frame from first frame to last"]),
      lighting: "constant deepening golden dusk exactly as the start image",
      audio: "",
      extraRules: ["the cart and गौरी are the complete cast of this clip"]
    },
    talking: false,
    cheap: false
  },
  {
    tag: "s2c_castor_talks",
    start: stills + "h22_castor_calm.png",
    endFrame: "",
    secs: 5,
    spec: {
      scene: "A DIALOGUE beat: कैस्टर keeps गौरी calm as the cart runs, talking to her the whole time. " + laneSet,
      cameraTravels: true,
      cast: [
        {
          TAG: "Dragon",
          name: "Castor",
          form: "Great",
          doing: "speaking gently down to her"
        },
        {
          TAG: "Gauri",
          doing: "looking up at him from the hay"
        }
      ],
      blocking: commonBlocking.concat([
            "कैस्टर flies ALONG the lane directly above and behind the cart — nose forward over it, his long body and tail stretching back up the slope behind him, wings swept back. He lowers only his HEAD and neck down toward गौरी in the cart beneath him. He stays nose-forward in line with the lane the whole clip",
            "गौरी looks up at him from the hay"
          ]),
      beats: ["0.0-5.0s: he speaks to her continuously and gently, mouth working, head dipping a little with the words; she watches him and her ears move"],
      camera: "a WIDE tracking shot, the camera well back and leading them down the lane so the full width of the lane, both kerbs and a band of sky are in frame. कैस्टर occupies the LEFT of frame and the cart the RIGHT, clearly separated, with open space above and behind him. One continuous take, facing down the lane throughout",
      physics: talkPhysics.concat([
            "SOLID BODIES: kerb, wall, cart and ground are solid stone and wood — every tail, wing and limb travels through open air, clear of them at all times",
            "the wall runs alongside the lane and stays a solid wall the whole clip"
          ]),
      lighting: "constant deepening golden dusk exactly as the start image, the light holding steady for the whole clip",
      audio: "SILENT — the picture alone carries this shot; the voice is dubbed in later",
      extraRules: commonRules
    },
    talking: true,
    cheap: false
  }
];

function argsFor(c) {
  var model = c.cheap ? "seedance_2_0_mini" : "seedance_2_0";
  var head = [
    "generate",
    "create",
    model,
    "--prompt",
    Kuku_PromptSpec.videoPrompt(c.spec)
  ];
  var mode = [];
  var audio = c.cheap ? [
      "--generate_audio",
      "false"
    ] : [
      "--generate_audio",
      "false"
    ];
  return head.concat(mode, [
              "--start-image",
              c.start
            ], c.endFrame === "" ? [] : [
                "--end-image",
                c.endFrame
              ], audio, [
              "--duration",
              String(c.secs)
            ], [
              "--resolution",
              "720p"
            ], [
              "--bitrate_mode",
              "high"
            ], [
              "--aspect_ratio",
              "16:9",
              "--wait",
              "--json"
            ]);
}

function run(c) {
  var dst = clips + "SCENE1_" + c.tag + ".mp4";
  if (Fs.existsSync(dst)) {
    console.log("skip (exists) " + c.tag);
    return ;
  }
  var model = c.cheap ? "seedance_2_0_mini" : "seedance_2_0";
  Kuku_Engine.clip(undefined, c.tag, c.spec, model, c.secs, c.start, c.endFrame, dst, undefined);
}

var only = process.argv.filter(function (a) {
      if (a.startsWith("-")) {
        return false;
      } else {
        return all.some(function (c) {
                    return c.tag.startsWith(a);
                  });
      }
    });

var chosen = only.length > 0 ? all.filter(function (c) {
        return only.some(function (o) {
                    return c.tag.startsWith(o);
                  });
      }) : all;

if (process.argv.some(function (a) {
        return a === "--audit";
      })) {
  all.forEach(function (c) {
        var dst = clips + "SCENE1_" + c.tag + ".mp4";
        var premises = [];
        if (Fs.existsSync(c.start)) {
          if (!Fs.existsSync(Kuku_Engine.receiptPath(c.start))) {
            premises.push("start frame unreceipted");
          }
          
        } else {
          premises.push("start frame absent");
        }
        if (c.endFrame !== "") {
          if (Fs.existsSync(c.endFrame)) {
            if (!Fs.existsSync(Kuku_Engine.receiptPath(c.endFrame))) {
              premises.push("end frame unreceipted");
            }
            
          } else {
            premises.push("end frame absent");
          }
        }
        var p = Kuku_Engine.freshness(dst, Kuku_PromptSpec.videoPrompt(c.spec));
        var verdict;
        if (typeof p !== "object") {
          switch (p) {
            case "Current" :
                verdict = "current";
                break;
            case "NoReceipt" :
                verdict = "STALE: no engine receipt";
                break;
            case "PromptDrift" :
                verdict = "STALE: prompt changed";
                break;
            case "AssetDrift" :
                verdict = "STALE: asset pixels changed after generation";
                break;
            
          }
        } else {
          verdict = "STALE: ref drifted " + p._0;
        }
        console.log(c.tag + " — " + verdict + (
              premises.length > 0 ? "  [premises: " + premises.join("; ") + "]" : ""
            ));
      });
} else if (process.argv.some(function (a) {
        return a === "--gate";
      })) {
  var bad = {
    contents: 0
  };
  all.forEach(function (c) {
        try {
          Kuku_PromptSpec.videoPrompt(c.spec);
          return ;
        }
        catch (raw_err){
          var err = Caml_js_exceptions.internalToOCamlException(raw_err);
          if (err.RE_EXN_ID === Js_exn.$$Error) {
            bad.contents = bad.contents + 1 | 0;
            console.log("== " + c.tag + " ==");
            var m = err._1.message;
            console.log(m !== undefined ? m : "?");
            return ;
          }
          throw err;
        }
      });
  if (bad.contents > 0) {
    Js_exn.raiseError(String(bad.contents) + " clip prompts forbid");
  }
  console.log("PROMPT GATE CLEAN: " + String(all.length) + " clip prompts describe, and every line names what is on screen");
} else if (process.argv.some(function (a) {
        return a === "--go";
      })) {
  chosen.forEach(run);
} else {
  chosen.forEach(function (c) {
        var costArgs = argsFor(c).slice();
        Caml_array.set(costArgs, 1, "cost");
        costArgs.splice(costArgs.length - 2 | 0, 2);
        console.log(c.tag + "  " + String(c.secs) + "s  start=" + (
              Fs.existsSync(c.start) ? "ok" : "MISSING"
            ) + "  " + Child_process.execFileSync("higgsfield", costArgs, opts).trim());
      });
}

var P;

var S;

export {
  P ,
  S ,
  opts ,
  ep10 ,
  stills ,
  clips ,
  laneSet ,
  d ,
  dSmall ,
  cow ,
  commonBlocking ,
  commonPhysics ,
  commonRules ,
  talkPhysics ,
  all ,
  argsFor ,
  run ,
  only ,
  chosen ,
}
/* laneSet Not a pure module */
