// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PromptGate from "./PromptGate.res.mjs";

function nameOf(n) {
  switch (n) {
    case "Kuku" :
        return "KUKU";
    case "Fyuria" :
        return "FYURIA";
    case "Leda" :
        return "LEDA";
    case "Castor" :
        return "CASTOR";
    case "Vesper" :
        return "VESPER";
    
  }
}

function colorOf(n) {
  switch (n) {
    case "Kuku" :
        return "green";
    case "Fyuria" :
        return "orange-red";
    case "Leda" :
        return "lilac-purple";
    case "Castor" :
        return "golden-yellow";
    case "Vesper" :
        return "pale blue";
    
  }
}

function shotName(s) {
  switch (s) {
    case "Wide" :
        return "WIDE";
    case "WideLow" :
        return "WIDE LOW ANGLE";
    case "HighWide" :
        return "HIGH WIDE";
    case "MediumWide" :
        return "MEDIUM-WIDE";
    case "Medium" :
        return "MEDIUM";
    case "CloseMedium" :
        return "CLOSE-MEDIUM";
    case "Close" :
        return "CLOSE";
    case "Insert" :
        return "INSERT CLOSE";
    case "WideAction" :
        return "WIDE ACTION";
    case "CloseAbstract" :
        return "CLOSE ABSTRACT";
    case "WideAbstract" :
        return "WIDE ABSTRACT";
    
  }
}

var styleKey = "0c47270d-70f7-4dd0-887f-c06c88ef5fd9";

var styleLaw = "3D papercraft, layered cut-paper illustration, soft matte construction-paper textures, visible paper edges and folds, an illustrated handcrafted paper world";

var paletteLaw = "bright, vibrant, warm storybook palette, every colour full and saturated";

var worldFacts = [
  "this world is inhabited by paper dragons, paper birds and paper animals only",
  "every surface — stone, wood, cloth, banner and sky — is plain blank paper"
];

function bullets(xs) {
  return xs.map(function (x) {
                return "- " + x;
              }).join("\n");
}

function subjectText(s) {
  switch (s.TAG) {
    case "Dragon" :
        var name = s.name;
        return "- " + nameOf(name) + " — " + colorOf(name) + " paper dragon, " + (
                s.form === "Great" ? "GREAT form: ENORMOUS IN THE WORLD — a grown man would reach only to her knee, and she towers over anything man-made beside her. That is her size in the world; her size in the picture is decided by how far away the viewpoint stands, so in a wide shot she may be a small figure and still be enormous" : "small everyday form: a small paper dragon child, the height of a human child"
              ) + ", wearing a golden कड़ा on one forearm. " + s.doing;
    case "Gauri" :
        return "- GAURI — gentle brown-and-white paper cow, dark paper eyes, a plain rope halter. " + s.doing;
    case "RishiMuni" :
        return "- RISHI — the elder paper dragon guru from the attached character sheet: white-maned and white-bearded, pale horns, an ochre robe, a wooden staff. " + s.doing;
    case "Dadi" :
        return "- DADI — the paper grandmother bird from the attached character sheet. " + s.doing;
    case "Cheel" :
        return "- CHEEL — a great paper eagle, sharp-eyed, imposing. " + s.doing;
    case "Prop" :
        return "- " + s.what + " — " + s.doing;
    
  }
}

function castLine(s) {
  switch (s.TAG) {
    case "Dragon" :
        return "- " + nameOf(s.name) + " — " + s.doing;
    case "Gauri" :
        return "- GAURI the cow — " + s.doing;
    case "RishiMuni" :
        return "- RISHI — " + s.doing;
    case "Dadi" :
        return "- DADI — " + s.doing;
    case "Cheel" :
        return "- CHEEL the eagle — " + s.doing;
    case "Prop" :
        return "- " + s.what + " — " + s.doing;
    
  }
}

function isCharacter(s) {
  if (s.TAG === "Prop") {
    return false;
  } else {
    return true;
  }
}

function imagePrompt(s) {
  var match = s.plate;
  var tmp;
  if (match !== undefined) {
    var match$1 = s.shot;
    var tmp$1;
    switch (match$1) {
      case "Medium" :
      case "CloseMedium" :
      case "Close" :
      case "Insert" :
      case "CloseAbstract" :
          tmp$1 = "SET PLATE: the SECOND attached image is THIS SAME LOCATION, already built. This shot is closer in, so the framing differs — but the place stays itself: identical ground material and paving, identical walls, kerbs, stone and paper textures, identical palette and light, and every landmark of it that falls inside this tighter frame sits exactly where the plate puts it.";
          break;
      default:
        tmp$1 = "SET PLATE: the SECOND attached image IS this location, already built — reproduce it faithfully: the same ground, the same landmarks in the same places, the same walls, kerbs and horizon, the same camera vantage, the same architecture throughout.";
    }
    tmp = tmp$1 + (
      s.objects.length > 0 ? " The image after the plate is a locked STORY OBJECT: the same forged shape appears in other shots and is reproduced with identical form, proportion, colour and material every single time." : ""
    ) + " Every remaining attached image is a locked character design; match each EXACTLY, including the golden bracelet.";
  } else {
    tmp = "CHARACTER REFERENCES: every attached image after the first is a locked character design; match each EXACTLY, including the golden bracelet.";
  }
  return PromptGate.pass("imagePrompt", [
                "SHOT: " + shotName(s.shot) + ", LANDSCAPE 16:9, full-bleed scene, the camera is INSIDE the world.",
                "STYLE: " + styleLaw + ". The FIRST attached image is the art style; match it EXACTLY.",
                "PALETTE: " + paletteLaw + ".",
                tmp,
                "SCENE: " + s.scene,
                "SUBJECTS:\n" + s.subjects.map(subjectText).join("\n"),
                "SETTING: " + s.setting,
                "LIGHTING: " + s.lighting,
                "HARD RULES:\n" + bullets((
                        s.subjects.some(isCharacter) ? worldFacts : ["this is an object/insert shot: the frame holds the place and the named objects alone"].concat(worldFacts)
                      ).concat(s.extraRules))
              ].join("\n"));
}

var editKeepLaw = [
  "same 3D papercraft medium and layered cut-paper texture",
  "same bright vibrant palette and same lighting",
  "same character designs, poses and expressions unless the change says otherwise",
  "same composition and camera"
];

function editPrompt(e) {
  return PromptGate.pass("editPrompt", [
                "TASK: edit the attached image — apply ONLY the change below.",
                "CHANGE: " + e.change,
                "KEEP:\n" + bullets(editKeepLaw.concat(e.keep)),
                "HARD RULES:\n" + bullets(worldFacts.concat(e.extraRules))
              ].join("\n"));
}

var directionLaw = ["TRAVEL KEEPS ONE DIRECTION: whatever moves may start from rest, speed up or slow down, and its path always continues the same way."];

var travellingCameraLaw = ["the camera keeps one direction of travel too, and the ground streams past in one consistent direction the entire time"];

var paperPhysics = ["motion has real weight"];

var dragonContinuity = ["the golden कड़ा stays on the same forearm as in the start image"];

function hasDragon(cast) {
  return cast.some(function (s) {
              if (s.TAG === "Dragon") {
                return true;
              } else {
                return false;
              }
            });
}

function videoPrompt(v) {
  return PromptGate.pass("videoPrompt", [
                  "SCENE: " + v.scene,
                  v.cast.length > 0 ? "THE COMPLETE CAST OF THIS SHOT — exactly these:\n" + v.cast.map(castLine).join("\n") : "IN THIS SHOT: the place itself, empty and still.",
                  "FIRST FRAME: the provided start image IS frame one — the action begins from exactly this position.",
                  "FORMAT: one single unbroken take.",
                  "BLOCKING:\n" + bullets(v.blocking),
                  "ACTION TIMING:\n" + bullets(v.beats),
                  "CAMERA: " + v.camera,
                  "PHYSICS:\n" + bullets(directionLaw.concat(v.cameraTravels ? travellingCameraLaw : [], paperPhysics, hasDragon(v.cast) ? dragonContinuity : [], v.physics)),
                  "LIGHTING: " + v.lighting,
                  v.audio === "" ? "" : "AUDIO: " + v.audio,
                  "STYLE: every frame keeps exactly the cut-paper papercraft look of the start image.",
                  v.extraRules.length > 0 ? "HARD RULES:\n" + bullets(v.extraRules) : ""
                ].filter(function (l) {
                    return l !== "";
                  }).join("\n"));
}

var kukuRoot = "../stories/kuku/";

function boardOf(s) {
  switch (s.TAG) {
    case "Dragon" :
        var name = s.name;
        if (s.form !== "Small") {
          return kukuRoot + "ep10prod/elements/future_" + nameOf(name).toLowerCase() + "_board_bracelet.png";
        }
        switch (name) {
          case "Kuku" :
              return kukuRoot + "charsheets/kuku.png";
          case "Fyuria" :
              return kukuRoot + "charsheets/furia.png";
          case "Leda" :
              return kukuRoot + "charsheets/leda.png";
          case "Castor" :
              return kukuRoot + "charsheets/castor.png";
          case "Vesper" :
              return ;
          
        }
    case "RishiMuni" :
        return kukuRoot + "charsheets/rishi.png";
    case "Dadi" :
        return kukuRoot + "charsheets/dadi.png";
    case "Cheel" :
        return kukuRoot + "charsheets/cheel.png";
    case "Gauri" :
    case "Prop" :
        return ;
    
  }
}

function imageRefs(s) {
  var p = s.plate;
  var head = p !== undefined ? [
        styleKey,
        p
      ].concat(s.objects) : [styleKey].concat(s.objects);
  var boards = s.subjects.reduce((function (acc, sub) {
          var b = boardOf(sub);
          if (b !== undefined && !acc.includes(b)) {
            return acc.concat([b]);
          } else {
            return acc;
          }
        }), []);
  return head.concat(boards);
}

export {
  nameOf ,
  colorOf ,
  shotName ,
  styleKey ,
  styleLaw ,
  paletteLaw ,
  worldFacts ,
  bullets ,
  subjectText ,
  castLine ,
  isCharacter ,
  imagePrompt ,
  editKeepLaw ,
  editPrompt ,
  directionLaw ,
  travellingCameraLaw ,
  paperPhysics ,
  dragonContinuity ,
  hasDragon ,
  videoPrompt ,
  kukuRoot ,
  boardOf ,
  imageRefs ,
}
/* PromptGate Not a pure module */
