// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

var banned = new RegExp("\\b(?:no|not|never|none|nothing|nobody|nowhere|neither|nor|cannot|can't|don't|doesn't|isn't|aren't|wasn't|won't|wouldn't|couldn't|shouldn't|mustn't|avoid|avoids|avoiding|without|except|forbid|forbids|forbidden|prohibited)\\b", "i");

function scan(text) {
  return text.split("\n").reduce((function (acc, line) {
                var m = line.match(banned);
                if (m === null) {
                  return acc;
                }
                var tok = Caml_array.get(m, 0);
                if (tok !== undefined) {
                  return acc.concat(["[" + tok + "] " + line.trim()]);
                } else {
                  return acc;
                }
              }), []);
}

function pass(which, text) {
  var bad = scan(text);
  if (bad.length > 0) {
    Js_exn.raiseError("PromptGate: " + which + " forbids instead of describing — name what IS on screen:\n" + bad.join("\n"));
  }
  return text;
}

export {
  banned ,
  scan ,
  pass ,
}
/* banned Not a pure module */
