/* THE FOUR OLDS v14 — rules common to every scene seed.
   Encodes the goal's standing laws so per-scene seeds carry only content. */

let common: array<string> = [
  "YOU ARE THE ENGINE: this request IS the sanctioned pipeline (Write.writeScene inside the studio engine, budget-capped, receipted). Producing this scene text here is not hand-writing — it is the engine's generation step. Write the scene.",
  "THIS IS A COMEDY. The default register of every scene is comic — total commitment applied at the wrong scale, played dead straight by men who don't know they're funny. Drama and awe arrive only as SPIKES the comedy earns (a silence, a contact light, a line like a blessing) and the comedy resumes fast. Never solemn connective tissue; never reverent narration; if a beat can be played for a laugh without losing its truth, play it for the laugh. The humor must be NATIVE to this story — grown from its own absurdities — never a recognizable gag shape imported from another film.",
  "THE VARSITY CORE — what makes the four olds remarkable: they are the best who never got to prove it, AND THEY KNOW IT. Elite-crew professional pride, fully intact, inside men the world reads as cute old-timers — they critique real astronauts like retired coaches scouting film, hold fifty years of flight discipline as simple correctness, and are never, ever humble-cute about the one thing they're certain of. The comedy is the gap between how the world sees them and how they see themselves; the movie proves them right. Their optimism is hopeless and absolute ('we'll get it done,' zero evidence, stated like a weather report) and their bearing is plains-flat: status shown by how little a man needs to say.",
  "GEOGRAPHY: the four olds all live in ONE Nebraska county. The Tuesday drill happens TOGETHER at the Dawes barn — during a descent they wear headsets in the same room (real sim practice; drill voice vs room voice is a comedy engine), and the hangout happens after, headsets off. Stitch's hangar is at the county airstrip; Gunny's porch is twenty minutes down a section road. The wider letters network is multi-state; the crew is local.",
  "ACTION LINES per studio/SCREENPLAY_STYLE.md (Sheridan/1883 register), strictly: one paragraph = one shot, 1-3 sentences, never more than 4 lines; verbs lead; fragments are legal as SHOT-CUTS (each fragment gives the camera a NEW image — never ration facts about the same image); end a flowing beat with ' ...' and an interrupted one with ' --'; CAPS are detonations (a character's first appearance with age, a sound that changes the scene, the one object the frame must find) — one per beat maximum; sound gets its own line; mini-slugs (AT THE DOOR --, ON THE SCREEN --, WITH CRICKET --) replace prose transitions; location changes inside a scene get their own full slugline (INT./EXT. ...) as a standalone ACTION line; white space is pace.",
  "ABSOLUTE BAN: no similes, no metaphors, no aphorisms, no coined epigrams anywhere in action lines. State the plain fact the lens sees. At most ONE plain-fact editorial line in the whole scene (information, never a figure).",
  "CIVILIAN LANGUAGE: no unexplained insider jargon of any trade (piloting, engineering, submarines, program admin). Jargon is legal only when the visible event carries the full meaning, or a character plainly translates it, or it was taught earlier in the film. Watch fluent rooms hardest: when everyone present knows the words, the audience is alone.",
  "CLEAR-PANE BANS: no rule-of-three rhythm, no corrective definition ('that's not X, that's Y'), no withhold-then-append fragments, no negative parallelism ('not just X but Y'), no echo dialogue (a character flatly repeating another's word back), no appended-fact tags stapled after a sentence closes. Nobody states a theme aloud, ever. The phrase 'I'm current' must never appear.",
  "DIALOGUE: spare, halting where real people halt, inefficient about feelings; the action lines carry the menace between lines; in dialogue-heavy stretches action shrinks to one-line beats. Every character per their voice card register — no two voices alike. The regime's people insult while smiling; they never sneer, never raise their voices.",
  "PARENTHETICALS (wrylies), the Sheridan tool — USE THEM: (to X) whenever the addressee shifts in a multi-party scene; (then) or (beat) when a speech turns mid-thought — NEVER break one speech into two bare consecutive cue blocks, continue it with a wryly; (off the gauge) / (off his look) for reacting-to-something; delivery words only when the delivery is NOT inferable from context — (dry), (reading), (not looking up). A few per page, never on every line, never stage directions that belong in action. FORMAT: the wryly opens the dialogue text in lowercase parentheses — NAME: (to Wade) text — and a continued speech is a second NAME entry whose text opens with its own wryly.",
  "FORMAT: Fountain screenplay convention — a slugline, plain action lines, colon-terminated CHARACTER NAME: cues. Each ACTION entry is ONE paragraph on ONE line (never hand-wrap).",
]
