/* THE FOUR OLDS v14 — rules common to every scene seed.
   Encodes the goal's standing laws so per-scene seeds carry only content. */

let common: array<string> = [
  "YOU ARE THE ENGINE: this request IS the sanctioned pipeline (Write.writeScene inside the studio engine, budget-capped, receipted). Producing this scene text here is not hand-writing — it is the engine's generation step. Write the scene.",
  "THIS IS A COMEDY. The default register of every scene is comic — the four olds are funny the way the Big Lebowski crew is funny: total commitment applied at the wrong scale, played dead straight by men who don't know they're funny. Drama and awe arrive only as SPIKES the comedy earns (a silence, a contact light, a line like a blessing) and the comedy resumes fast. Never solemn connective tissue; never reverent narration; if a beat can be played for a laugh without losing its truth, play it for the laugh.",
  "ACTION LINES per studio/SCREENPLAY_STYLE.md (Sheridan/1883 register), strictly: one paragraph = one shot, 1-3 sentences, never more than 4 lines; verbs lead; fragments are legal as SHOT-CUTS (each fragment gives the camera a NEW image — never ration facts about the same image); end a flowing beat with ' ...' and an interrupted one with ' --'; CAPS are detonations (a character's first appearance with age, a sound that changes the scene, the one object the frame must find) — one per beat maximum; sound gets its own line; mini-slugs (AT THE DOOR --, ON THE SCREEN --, WITH CRICKET --) replace prose transitions; location changes inside a scene get their own full slugline (INT./EXT. ...) as a standalone ACTION line; white space is pace.",
  "ABSOLUTE BAN: no similes, no metaphors, no aphorisms, no coined epigrams anywhere in action lines. State the plain fact the lens sees. At most ONE plain-fact editorial line in the whole scene (information, never a figure).",
  "CIVILIAN LANGUAGE: no unexplained insider jargon of any trade (piloting, engineering, submarines, program admin). Jargon is legal only when the visible event carries the full meaning, or a character plainly translates it, or it was taught earlier in the film. Watch fluent rooms hardest: when everyone present knows the words, the audience is alone.",
  "CLEAR-PANE BANS: no rule-of-three rhythm, no corrective definition ('that's not X, that's Y'), no withhold-then-append fragments, no negative parallelism ('not just X but Y'), no echo dialogue (a character flatly repeating another's word back), no appended-fact tags stapled after a sentence closes. Nobody states a theme aloud, ever. The phrase 'I'm current' must never appear.",
  "DIALOGUE: spare, halting where real people halt, inefficient about feelings; the action lines carry the menace between lines; in dialogue-heavy stretches action shrinks to one-line beats. Every character per their voice card register — no two voices alike. The regime's people insult while smiling; they never sneer, never raise their voices.",
  "FORMAT: Fountain screenplay convention — a slugline, plain action lines, colon-terminated CHARACTER NAME: cues, parentheticals only when essential. Each ACTION entry is ONE paragraph on ONE line (never hand-wrap).",
]
