-- GENERATED by Drakosha_GamePlan.res — do not edit by hand.
local M = {}
M.episode = "ep1_den_rozhdeniya_ch1"
M.issued_letters = { "А", "О", "М", "С", "К", "Т", "Л", "Б" }
M.beats = {
    { kind = "story", audio = "line043_mama", still = "f24" },
    { kind = "story", audio = "line046_vasya", still = "f25" },
    { kind = "story", audio = "line050_vasya", still = "f26" },
    { kind = "spell", id = "sok", word = { "С", "О", "К" }, asker = "FROSYA", ask = "frosya_ask_sok", hints = { "frosya_hint_stroke_curve", "frosya_hint_try_again" }, praise = { "frosya_praise_1", "vasya_praise_2" }, reveal = "REVEAL-SOK", scaffold = "trace_model" },
    { kind = "story", audio = "line053_frosya", still = "f28" },
    { kind = "spell", id = "mama", word = { "М", "А", "М", "А" }, asker = "VASYA", ask = "vasya_ask_mama", hints = { "frosya_hint_stroke_down", "vasya_hint_together" }, praise = { "vasya_praise_1", "frosya_praise_1" }, reveal = "REVEAL-MAMA_author", scaffold = "trace_dots" },
    { kind = "story", audio = "line065_mama", still = "f31" },
    { kind = "spell", id = "kot", word = { "К", "О", "Т" }, asker = "VASYA", ask = "vasya_ask_kot", hints = { "frosya_hint_stroke_down", "frosya_hint_try_again", "vasya_hint_together" }, praise = { "vasya_praise_1", "frosya_praise_1", "vasya_praise_2" }, reveal = "REVEAL-KOT_author", scaffold = "trace_model" },
}
return M
